### ISSUE TITLE
How to use `setTheme` in typescript?

### ISSUE THREAD

**Issue by auryn31** [SAP/ui5-webcomponents-react#1057]
**Describe the documentation issue**

- [x] Documentation is unclear
- [x] Documentation is missing

**Description of the issue**
I have issues to use `setTheme()` in typescript. 

```js
// next line is not importable
import { setTheme } from '@ui5/webcomponents-base/dist/config/Theme';

import '@ui5/webcomponents/dist/Assets';
import '@ui5/webcomponents-fiori/dist/Assets';
```

and i cannot find any setTheme in the ts files :-/

Maybe someone knows the solution?

Tanks for the help

**Comment by MarcusNotheis** [comment]
Hey @auryn31,
I guess this is caused by the fact that the UI5 Web Components themselves do not offer any d.ts files as of now, only our "for React" wrapper has type definitions. As far as I know, the UI5 Web Components team is currently working on providing type definitions as well.
As a quick fix for know: Is it possible to make your tsconfig less strict? You can find our [tsconfig here](https://github.com/SAP/ui5-webcomponents-react/blob/master/tsconfig.json) and we can import `useTheme` without issues.

**Comment by auryn31** [comment]
@MarcusNotheis  Thanks for the advice :-)
I will test this. 
If the team needs help with the types, i think we also can help if there is time :-)
Where can i find the repo for the types? Then i can create a pr if i found it :-)

**Comment by MarcusNotheis** [comment]
I think the d.ts files will be generated from the jsdoc comments, but I guess @ilhan007 can explain their plan in a more detailed way :)

**Comment by MarcusNotheis** [comment]
Closing this issue in favor of #1136.
Please feel free to continue the conversation there.
