### ISSUE TITLE
FlexibleColumnLayout: startColumn cannot be rendered while if import from another components

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#1123]
**Describe the bug**
When I am using 'Flexible Column Layout', it has startColumn, midColumn, endColumn, and each column accept one 'ReactNode', so I want to split three columns into three different files, and import them, however, it doesn't work.

**Isolated Example**
https://codesandbox.io/s/interesting-williams-82dh2

**To Reproduce**
1. Go to the sandbox link
2. Using the `const thisWorks = <h1>Works</h1>`; Start column can be rendered. 
3.Using the `First Column`, Start Column cannnot be rendered.

**Expected behavior**
Import components should be rendered.

**Screenshots**
![Screen Shot 2020-12-31 at 2 30 36 PM](https://user-images.githubusercontent.com/5527455/103397789-c480d880-4b74-11eb-81eb-c458e1236b4c.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc10
`@ui5/webcomponents-react` version: 0.12.3

**Comment by MarcusNotheis** [comment]
Hey @rkl1994,
thanks for reporting.
Your code requires 2 adjustments to work as expected:

1. The `slot` props expect you to pass valid HTML elements, not React Components. You can fix this by using `startColumn={<FirstColumn />}` instead of `startColumn={FirstColumn}`
2. Your custom component needs to accept a `slot` prop which will be inserted by UI5 Web Components for React. So, your `FirstColumn.js` should look like:
   ```jsx
   const FirstColumn = (props) => {
     return (
       <div slot={props.slot}>
         <h1>{"Doesn't work"}</h1>
       </div>
     );
   };
   ```

You can find an updated codesandbox [here](https://codesandbox.io/s/admiring-mirzakhani-7494f?file=/src/FirstColumn.js).

**Comment by rkl1994** [comment]
cool! Thank you so much
