### ISSUE TITLE
Peer dependency of @ui5/webcomponents-fiori

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents-react#1124]
Why is `@ui5/webcomponents-fiori` not an [optional dependency](https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/main/package.json#L46)?

What if we don't use Shell Bar/Product Switch UI5 Web Components, why should we install this peer dependency in our project? Should it be marked as optional?

**Comment by MarcusNotheis** [comment]
Hey @pavelkornev,
unfortunately it depends a bit on your project setup whether the `@ui5/webcomponents-fiori` dependency is really optional or not.

Let me try to give one example where `@ui5/webcomponents-fiori` is not optional although you don't use it:
1. Setup a new app using `create-react-app`
2. Render a `Button` component and import it from `import { Button } from '@ui5/webcomponents-react';`.
3. Now, the webpack dev server will crash because it tries to resolve e.g. the ShellBar component because it is also exported via our index file and there is no treeshaking in the development mode.
4. For the prod build it would work fine again because now treeshaking is active.

Do you have any suggestions why how to overcome such a behaviour? Then I would be happy to mark the -fiori package as optional.

**Comment by pavelkornev** [comment]
Hi @MarcusNotheis,

I have created sandbox — https://codesandbox.io/s/condescending-smoke-lrtkx?file=/src/App.js

Works without crashing.

**Comment by MarcusNotheis** [comment]
Hey @pavelkornev,

yes, your codesandbox describes exactly the case where it works because you are importing the `Button` component directly. If you would change the import to `import { Button } from '@ui5/webcomponents-react';`, then the sandbox would crash - see [this example](https://codesandbox.io/s/wizardly-pare-cr96o).

**Comment by MarcusNotheis** [comment]
Closing this issue as discussed.
