### ISSUE TITLE
Bar: Nested React fragments and custom components not working correctly

### ISSUE THREAD

**Issue by jeff-fillmore** [SAP/ui5-webcomponents-react#1219]
**Describe the bug**
Nested React fragments don't work in Bar component slots
Custom Components only work in some cases.

Added more explanations in code sandbox listed in Isolated Example. 

**Isolated Example**
https://codesandbox.io/s/headless-dust-bn76y?file=/src/App.js

**To Reproduce Nested Fragments**
1. Add a Bar component
2. Add nested fragments in start, middle, or end slots
3. See results that doesn't render correctly

**To Reproduce Custom Component**
1. Add a Bar component
2. Add custom React component in start, middle, or end slots
3. See results that doesn't render correctly

**Expected behavior**
Nested fragments and custom components should render when used in Bar slots

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0.rc11
`@ui5/webcomponents-react` version: 0.13.5
Operating System: MacOS
Browser:  Chrome

**Comment by MarcusNotheis** [comment]
Hey @jeff-fillmore,
thanks for reporting, looks like we are not 100% there yet 🙂 

Let me share my first thoughts:

### Custom Components
Whenever you use custom components like your `CustomComponent` in your code sandbox as a `slot` prop (like `startContent`, `middleContent`, etc.) you have to make sure that you accept a prop called `slot` and pass that to the component you are rendering. This prop is provided by our React Wrapper and will make sure that all contents will appear in the place they should.

Example on how to fix your custom component:
```
  const CustomComponent = (props) => {
    return (
      <Breadcrumbs slot={props.slot}>
        {props.breadcrumbs.map((item) => {
          return <Link>{item.name}</Link>;
        })}
      </Breadcrumbs>
    );
  };
```

**Action Item: We must mention this in our docs**

### middleContent errors
You have a small typo in your sandbox (`middleContnet` instead of `middleContent`).
If you fix that typo and apply the fix for the `CustomComponent`, then Example 2 and Example 3 are fixed.

### Nested Fragments
If I didn't miss something I think the only open issue right now is that we don't support nested fragments yet (Example 1, `middleContent` and `endContent`).
Actually I'm not 100% sure on how to fix this because traversing the whole tree of a provided component might get too expensive in terms of CPU time, so maybe always wrapping the slots in a `div` with a slot would work? Wrapping the slots into a div would also make the first solution with adding the slot prop to your custom component obsolete.
@Lukas742 What are your opinions on that? Would there be a chance of having negative side effects when wrapping all slots into divs?

Here's my updated codesandbox: https://codesandbox.io/s/romantic-goodall-jboq4?file=/src/App.js

**Comment by Lukas742** [comment]
Hi @jeff-fillmore 

after discussing this topic with @MarcusNotheis we came to the conclusion that applying a `div` to each slot is probably the best way to achieve this. I've created a  [PR](https://github.com/SAP/ui5-webcomponents-react/pull/1221) that will add this feature. Please note that this is not supported by IE11.

**Comment by jeff-fillmore** [comment]
@Lukas742 and @MarcusNotheis 

Thanks so much for the help.  I will see if I can update our code to see if it can work with the suggests on slots and wrapping html.

Once again my team and I really appreciate the work on this project!

Jeff
