### ISSUE TITLE
@ui5/webcomponents-react-seed: input name props and formik 

### ISSUE THREAD

**Issue by Dingyj3178** [SAP/ui5-webcomponents-react#1381]
**Describe the bug**
I got following warning when I opened TodoEditForm.
![image](https://user-images.githubusercontent.com/19564695/109789312-92165900-7c53-11eb-8f88-bd3932eadc2c.png)

After importing '@ui5/webcomponents/dist/features/InputElementsFormSupport.js'.
I got another warning.
![image](https://user-images.githubusercontent.com/19564695/109789850-18329f80-7c54-11eb-8c16-9276c7a70b7f.png)

**To Reproduce**
1. run npx create-react-app my-app --template @ui5/webcomponents-react-seed
2. run yarn start
3. open TodoEditForm 
4. confirm browser console

Do you have any workaround to avoid this?
We have deeply utilized this template so we got a huge warnings in this console...

**Comment by Lukas742** [comment]
Hi @Dingyj3178 

I created a PR(https://github.com/SAP/ui5-webcomponents-react/pull/1382) that should solve the issue with the `InputElementsFormSupport` import. 

The warning you get after importing is coming from the `TextArea`, since this component is developed by the ui5-webcomponents team, I created an issue in there repo. You can find it [here](https://github.com/SAP/ui5-webcomponents/issues/2902).
