### ISSUE TITLE
Form: addEventListener listeners lost on resize

### ISSUE THREAD

**Issue by todormikov** [SAP/ui5-webcomponents-react#1398]
**Describe the bug**
When using addEventListener to listen for events thrown by components inside FormItem, resizing the browser can lead to the listeners being lost.

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/sad-stonebraker-0ur0t?file=/src/App.js) with ui5-input updating component state.

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/sad-stonebraker-0ur0t?file=/src/App.js)
2. Click on 'Open In New Window'
3. Verify that typing in the input changes the label at the bottom
4. Zoom in the browser until the input changes position and the its value is reset
5.  Verify that typing in the input no longer changes the label

**Expected behavior**
Resizing the screen should not reset event listeners added by addEventListener.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.12
`@ui5/webcomponents-react` version: 0.14.2
Operating System: Windows
Browser: Chrome, Edge, Firefox tested

**Additional context**

**Comment by Lukas742** [comment]
Hi @todormikov 

__Short answer__:
the `Form` doesn't support attaching event listeners to HTML elements. I've created a [codesandbox](https://codesandbox.io/s/restless-leaf-bphc2?file=/src/App.js) that implements this behavior without using explicit event binding.

__Long answer__:
It's hardly possible to catch e.g. event listeners directly bound to the HTML element with React. This is because, if the component changes, e.g. by a remount, the HTML element is not the same anymore. Internally this is handled by React, but when adding a listener externally the old reference is lost and has to manually be added again. 
In the `Form` we use `cloneElement` to show the different visualisations of the form items for different screen sizes. That's the reason why the `FormItem` does not keep its `value` and is also losing the attached event listener. 
If you still need to implement the `Form` with custom event listeners, then it's only possible by setting all `labelSpan` and `columns` props  to the same value. This way, the form has the same layout for all screen sizes, and therefore doesn't rerender when resizing.

**Comment by todormikov** [comment]
Hi @Lukas742 

Thank you for the quick and detailed response.
We will consider which of the provided solutions best suits our project.
