### ISSUE TITLE
DateTimePicker : On selection shows a different date and time in chrome based browsers(edge)

### ISSUE THREAD

**Issue by cruelshoes** [SAP/ui5-webcomponents-react#1418]
**Describe the bug**
I am using the DateTimePicker in states from the UI5 web component.
When i am trying to select the date and time in my Chrome browser, on selection it shows a different date and time.
The same issue i have identified in Edge Browser. It generally happens in all chromium browsers
This works fine in Firefox Browser

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**

**Expected behavior**

**Screenshots**
![ss1](https://user-images.githubusercontent.com/14087919/111437772-7cac2f00-8729-11eb-8728-e55fc1a5e2ea.png)
![ss2](https://user-images.githubusercontent.com/14087919/111437773-7cac2f00-8729-11eb-921d-ae6f2627156a.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser: Edge, Chrome

**Additional context**
    "@ui5/webcomponents-base": "^0.30.0",
    "@ui5/webcomponents-fiori": "^1.0.0-rc.12",
    "@ui5/webcomponents-icons": "^1.0.0-rc.12",
    "@ui5/webcomponents-react": "^0.14.4",
    "@ui5/webcomponents-react-base": "^0.14.4",
    "@ui5/webcomponents-react-charts": "^0.14.4",

**Comment by fifoosid** [comment]
Hi guys,

This issue was initially posted in UI5 Web Components repo(https://github.com/SAP/ui5-webcomponents/issues/2904), but we were not able to reproduce the issue with pure web component. In the application, developers are importing the datetimepicker from UI5 Web Components for React package.

The issue is reproducible on their side with the provided versions in the issue. The behaviour can be observed in Chrome 89.0 and Edge(the chromium based) 89.0, after changing the time zone to New Delhi, India(India Standart Time).

Moreover, in some cases the min-date property is not working at all.

Isolated example with UI5 Web Components: https://codesandbox.io/s/ui5-webcomponents-forked-9nstq?file=/index.html

Best regards,
FIlip

**Comment by Lukas742** [comment]
Hi @cruelshoes 

I could not reproduce the issue with the date-time selection. 
What client language are you using with the different browsers and could you also check if this is also happening with this [example](https://codesandbox.io/s/currying-tree-7qku7?file=/src/App.js)? There you can also see the current client language and timezone of your browser.

@fifoosid 
The `min-date` issue  is occurring because of the client language of the browser and the default `format-pattern`.
I prepared a [codesandbox](https://codesandbox.io/s/ui5-webcomponents-forked-g0d1e?file=/index.html) that explain this in more detail.

I also checked our implementation and we do not add any customisations to the internal functionality of the `ui5-datetime-picker`. Maybe this issue with the selection is also related to the language issue with the `format-pattern`.

**Comment by fifoosid** [comment]
Hi @Lukas742 

I tested out the problem with the ```min-date``` and it seems like it is only occurring when in the application, no format-pattern is set to the ```ui5-datetime-picker```, which leads to different locale formats to be used in different browsers/locations.

If the application explicitly sets a ```format-pattern```, then this issue is not present.

When it comes to the main issue, that is described, it will be resolved in version RC13 of UI5 Web Components

**Comment by Lukas742** [comment]
Hi @cruelshoes 

we just released our latest version ([0.15.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.15.1)) containing the rc13 of ui5-webcomponents. Could you please check if the issue is still occuring with that?
