### ISSUE TITLE
Card manifest.json

### ISSUE THREAD

**Issue by brampurnot** [SAP/ui5-webcomponents-react#1486]
Hi there!

Are there any plans to allow the use of a manifest.json for defining the cards? Within the concept of these reusable integration cards, you can specify the entire structure of the card inside a manifest.json file which can then be reused. More information can be found here:
https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/index.html

Would be great if this would be supported as well here.

Bram

**Comment by MarcusNotheis** [comment]
Hey @brampurnot,

thanks for reporting! Actually we got another request for the Adaptive Cards yesterday and which is tracked here: https://github.com/SAP/ui5-webcomponents/issues/3116.
So I would recommend closing this issue in keep tracking the progress in the UI5 Web Components repo because this will allow to use that concepts in all frameworks and not only react.

**Comment by brampurnot** [comment]
Thanks!
