### ISSUE TITLE
[SF][ObjectPage]: Ask Classname Interface for Header, Title and Badge in ObjectPage

### ISSUE THREAD

**Issue by JosephineSu** [SAP/ui5-webcomponents-react#1671]
Hi Colleague,
I am from SuccessFactor Xweb Shanghai team. We use ObjectPage to display some details and wanna add specific styles for title, badge. But the classname of these section is randomly generated. 
Could you please offer interfaces so that user can define the classname of Header, title and badge.

Best Regards

**Comment by sfsf-xweb-sh** [comment]
Hi @MarcusNotheis,

 Please add these changes to v0.131.12.
Thanks a lot.

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

I created a PR (#1848) that will merge the DynamicPage and ObjectPage changes into the `0.131.xx` branch. We will let you know once `0.131.12` is released.

Since this PR contains a major refactoring of the Object - and DynamicPage there are a few breaking changes you need to be aware of. For details please take a look at our [Migration Guide](https://sap.github.io/ui5-webcomponents-react/?path=/docs/migration-guide--page) (the Device changes and Logger removal are not included in this PR)

Also [here](https://codesandbox.io/s/lingering-frog-3uw1d?file=/src/App.js) you can find an example (in this case with JSS) on how to access different elements inside the pages.
