### ISSUE TITLE
Feature Request: Extract ThemeProvider Storybook addon as a ready-to-use package

### ISSUE THREAD

**Issue by Psidium** [SAP/ui5-webcomponents-react#1978]
**Describe the solution you'd like**

In my project we are using ui5-webcomponents-react with Storybook. A lot of the ready-to-use context/providers already have storybook addons that are just plug and play.
I've seen you already developed the decorators for your storybooks, I was wondering if you could package that into a tool and release that as a standalone npm package.

**Describe alternatives you've considered**

Otherwise I might have to just copy what you've done into my `.storybook/preview.js` files

**Comment by MarcusNotheis** [comment]
Hey @Psidium,

sorry for the very late reply. We've discussed this feature request internally and came to the conclusion that we will not offer our storybook configuration as a readymade npm module. 

This is because of two main reasons:
- Our Storybook config is currently not part of any package, so we would have to create a new package that would need maintenance, etc. in the long run
- There is lots of custom config in our preview file, e.g. a certain order of stories and globally defined argTypes. In addition to that, consumers would need certain addon-ons installed to make use of our globalTypes for example.

Having said this, I would recommend just to copy our preview file and adapt it as needed.

Best regards,
Marcus
