### ISSUE TITLE
[SF][INPUT][A11y]: aria-* not supported

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents-react#2023]
**Describe the bug**
@ui5-webcompnents's ui5-input element provides a prop [`_inputAccInfo`](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Input.js#L338) to support some kinds of aria attribute to underline `input` element. However @ui5-webcompnents-react does not support this prop.

**Expected behavior**
@ui5-webcompnents-react add a prop `_inputAccInfo` to support aria-* attribute for underline `input` html element.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.14
`@ui5/webcomponents-react` version: 0.131.13
Operating System: macOS
Browser: Chrome

**Comment by MarcusNotheis** [comment]
hey @2bno1,
how is the `_inputAccInfo` prop intended to be used? As it is an object I would assume that it should be added in an imperative way via JS and not via prop, shouldn't it?
In general I'm not sure how to handle such requests in general. On the one hand side it does definitely make sense to provide a wrapper for **all** functionalities of the UI5 Web Component , but on the other hand I have a hard time to add private UI5 Web Components props to our "public" API.

I'll also check with the Web Component whether there are any plans to add a "public" support for those aria helpers.

**Comment by 2bno1** [comment]
Hello @MarcusNotheis Is there any update on this? Thanks.

**Comment by MarcusNotheis** [comment]
Hey @2bno1,

I just had a quick chat with @vladitasev: This property is private and can only be set via JavaScript, so there is no possibility for us to offer a prop for the `_inputAccInfo` object. The main purpose of this object is for other UI5 Web Components so that they can set the correct a11y properties, but it's not intended for external usage.

If you absolutely want to use this prop, you can attach a `ref` to the `Input` component and manipulate set the `_inputAccInfo` object via JavaScript, but I would advise against that because it's a private prop.

Having said that, I'm going to close this issue. Please feel free to reopen it or to create a new one in case there is more to do on our side.
