### ISSUE TITLE
[SF] [A11y]: ariaLabel and ariaLabelledby are not supported in 0.131.x version

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents-react#2124]
**Describe the bug**
Form input elements of @ui5-webcomponents of 0.13.x version support 2 a11y related attributes: `ariaLabel` and `ariaLabelledby` (for example: https://github.com/SAP/ui5-webcomponents/blob/release-0.31/packages/main/src/Input.js#L306)
But in the corresponding @ui5-webcomponents-react of 0.131.x, there're no props for these 2 attributes: https://github.com/SAP/ui5-webcomponents-react/blob/00a99cdc9b56ed6e98e42c247dbdb3279567afd8/packages/main/src/webComponents/Input/index.tsx#L158

We have a11y requirements which require these 2 props: `ariaLabel`, `ariaLabelledby`.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version 0.13.x
`@ui5/webcomponents-react` version: 0.131.x
Operating System: macOS
Browser: Chrome

**Comment by MarcusNotheis** [comment]
Hey @2bno1,
those two props are not exposed because they are both marked as private, so in order to expose them, the UI5 Web Components would have to flag them as `public` before we can go ahead in our repository.
Using the standard `aria-label` and `aria-labelledby` won't work for you because you have to attach those props to the internal input, right?

cc @vladitasev @ilhan007

**Comment by 2bno1** [comment]
Hi @MarcusNotheis 
I tried using `aria-label` and `aria-labelledby`, they were working fine. They're passed to the underline ui5 webcomponents.

Thank you for your suggestion.
