### ISSUE TITLE
DynamicPage: Footer not placed correctly in FCL

### ISSUE THREAD

**Issue by piterPro** [SAP/ui5-webcomponents-react#2200]
**Describe the bug**
When using the floating footer as part of DynamicPage in FlexibleColumnLayout the footer is not placed correctly

**Isolated Example**
https://codesandbox.io/s/thirsty-kare-e4uwj?file=/src/App.js

**To Reproduce**
1. Go to sandbox
2. Open the sandbox in a full screen mode
3. Use dev tools to set width to 1904px or 1520
4. The floating footer is placed right after the content of the page

**Expected behavior**
The floating footer should be always at the bottom of the page as fixed in release version
"0.18.8 (2021-09-15)
DynamicPage: footer always sticks to bottom of the page (#2083) (4d291cb)"

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:"latest" - rc.15,
"@ui5/webcomponents-fiori": "latest" - rc.15,
`@ui5/webcomponents-react` version:  "latest" - 0.18.9,
Operating System: Windows 10
Browser: Chrome

**Additional context**
Changing the size of left to right page triggers visual switching of places

**Comment by texttechne** [comment]
@piterPro Actually you have to set heights manually. Ideally you calculate the correct `minHeight` for the content of the right column. Additionally you probably want to restrict the height of the left column, so that it has it's own scrollbar, when its content is getting too large...

That is my understanding of the current design philosophy...
