### ISSUE TITLE
ComponentName: node_modules/lit-html

### ISSUE THREAD

**Issue by Hazel0913** [SAP/ui5-webcomponents-react#227]
**Describe the bug**
When we use the ui5-webcomponents-react we found that there are some files used by ui5-webcomponents-react not compiled yet.
Such as:  `node_modules/lit-html`
We need our application to support IE11. Does it means that we should also compile the node_modules files?

**Desktop (please complete the following information):**
 - Browser IE11

**Comment by MarcusNotheis** [comment]
Hi @Hazel0913,

yes, UI5 Web Components and the "for React" wrapper are having some dependencies which are shipped es ES6 modules. This is due to the fact that Web Components have to be ES6 Classes per definition.
Thus you have to transpile `node_modules` as well in case you want to support IE11.

Are you using `create-react-app` or a custom setup? As far as I know `cra` should transpile `node_modules` automatically.

**Comment by Hazel0913** [comment]
@MarcusNotheis 
No, we don't use create-react-app. Our project is complex so we don't compile node_modules for now. But I got it, we can compile some of the node_modules used by react-ui5.

Thanks!
