### ISSUE TITLE
[SF] [AnalyticalTable] Is Analytical Table disabled to change column order by Drag and Drop?

### ISSUE THREAD

**Issue by ChristyFei** [SAP/ui5-webcomponents-react#2318]
**Describe the bug**
Users can drag the column header and drop to change the column's order. It's a good feature but it's unexpected for us. Does the feature be disabled by setting one property? I didn't find it in the document. 

Thank you,
Christy

**Comment by Lukas742** [comment]
Hi @ChristyFei 

at the moment you can use `canReorder: false` in your columns option array. I created a PR that will deprecate this option in favor of `disableDragAndDrop` though, so with the next release you should consider changing it accordingly. Also I added the corresponding options to our documentation.

**Comment by ChristyFei** [comment]
Hi @Lukas742 ,

We use the following version. Is it possible to cherry-pick your modification to it? 
"@ui5/webcomponents-react"： "0.131.16"

Thank you,
Christy

**Comment by Lukas742** [comment]
Hi @ChristyFei 

the changes are now available with version [0.131.24](https://github.com/SAP/ui5-webcomponents-react/blob/rel/0.131/CHANGELOG.md#013124-2021-11-23). If you want to consume the changes you will have to update your dependencies, otherwise you can just stick to `canReorder`. (`canReorder` is still working in 0.131.24 version as well, it will just throw a warning in dev mode stating that it's deprecated)
