### ISSUE TITLE
Page : not rendering content

### ISSUE THREAD

**Issue by MKraus92** [SAP/ui5-webcomponents-react#2343]
**Describe the bug**
When using the Page Component, children do not get rendered

**Isolated Example**
[https://codesandbox.io/s/trusting-diffie-umepp](https://codesandbox.io/s/trusting-diffie-umepp).

**To Reproduce**
1. Go to sandbox
2. Paste the example for Page component
3. See that Page content does not get rendered

**Expected behavior**
The content placed in a Page component should be rendered.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest - 1.0.1
`@ui5/webcomponents-react` version: latest - 0.20.0
Operating System: Windows 10
Browser: Chrome & Firefox

**Comment by Lukas742** [comment]
Hi @MKraus92 

the content is rendered, but not visible as it has a height of 0. You can add a height to the Page to prevent this. [codeSandbox](https://codesandbox.io/s/sad-browser-nielh?file=/src/App.js)

**Comment by MKraus92** [comment]
Hi @Lukas742 ,

thank you for your response. Seems like it does not work with flexible values like "auto", "percentage" or "fit-content".

I guess i wil have to open a feature request for this?

**Comment by Lukas742** [comment]
Hi @MKraus92 

sorry, maybe my answer was a bit confusing. The Page itself has a defined height and width of 100% and the content is `absolute` positioned and spreadts itself to the bottom of the page (`bottom: 0`). This is by design, since the content of the Page should be scrollable and the header should stick to the top. 

So, if you set the Page to a fixed height, or the Page is a direct child of a container with a fixed height, you can apply a dynamic height to the content container.

Here you can find an example of how you could handle this: [codeSandbox](https://codesandbox.io/s/sad-browser-nielh?file=/src/App.js)

**Comment by MKraus92** [comment]
Hi @Lukas742 ,

with this answer I now understand how the component behaves, thank you.
