### ISSUE TITLE
Analytical Table: Nested Data in Analytical Table

### ISSUE THREAD

**Issue by MKraus92** [SAP/ui5-webcomponents-react#2387]
### The Problem ### 

When rendering a Select component with nested Data inside an Analytical Table, the table renders extremly slow.

[This Sandbox demonstrates this, if you scroll fast you see that for some time the table stays blank](https://codesandbox.io/s/wonderful-jones-lssws?file=/src/App.js )

This gets worse with more data, making the rendering of 20 lines take up to 10 seconds.
![performance](https://user-images.githubusercontent.com/40430365/145166357-5cbf395f-edf8-4031-8534-b3cc1a0dc792.png)

### Use Case ### 

When having multiple data sources, linked by keys, you will need to map some components with the linked data.
The idea was, that the table functions as editable component.

I do not know if this is by design or a bug, thus i did not open as bug.

Thank you in advance for your insights.

**Comment by Lukas742** [comment]
Hi @MKraus92 

in the example you provided it is working quite well for me, even on an old mobile device it didn't take that much time. 
Here's an example when rendered with 5000 rows:
https://user-images.githubusercontent.com/9749730/145171346-1ddc22b4-026c-4bd6-ad5f-62ee2643d427.mp4

[codeSandbox](https://codesandbox.io/s/jolly-hodgkin-c230t?file=/src/App.js), [fullscreen](https://c230t.csb.app/)

The blank rows show up at first because of the virtualization, you can prevent this by setting the `overscanCount` to a very high number like `Infinity` but especially with large datasets the performance will degrade rapidly. 

Also some browser extensions can have a bad influence on performance when the dev tools are open (sometimes even the dev-tools themselves, e.g. when you output too many `console.log`s), so please make sure you use a "clean" environment when testing.

I'm not 100% sure what you mean by this:
> This gets worse with more data, making the rendering of 20 lines take up to 10 seconds.This gets worse with more data, making the rendering of 20 lines take up to 10 seconds.

Are you saying that it takes 10 seconds to render 20 lines when scrolling with large datasets? If so, could you please provide an example?

**Comment by MKraus92** [comment]
Hi @Lukas742 

thank you for your quick response.

In this example the dataset has about 50 kB and 200 lines.

![analyticalTableRendering](https://user-images.githubusercontent.com/40430365/145174716-51abf3b8-089c-4fb0-a276-a43d03af35e0.gif)

As you can see the table renders a really long time. I already tried to disable the subrows and increase the overscanCount.
Additionally i tried to memoize the Select component. These steps only increased the rendering by about 1s each.

When removing the Select component the rendering is acceptable with about 1,5s and no stuttering.

**Comment by Lukas742** [comment]
I don't know what's the equivalent of 50kb, but I'd guess that's a pretty huge dataset. Also I think only part of the issue has something to do with the AnalyticalTable, which shouldn't be responsible for the bad performance. 
Internally the table does calculations with each row, including sub-rows. So let's say that you have a table with 500 rows, each row has 4 sub-rows, and every sub-row has again 4 sub rows. This then would leave the table with around 8500 flat rows. Since these are only considered for js calculation, this shouldn't have that much of an impact though, as you can see when you e.g. return `null` or just an text as content of the cell. 
The rendering is different on the other hand. As mentioned before the table is virtualized, so only a part of the rows are initially rendered. Per default this value is  `Math.floor(visibleRows / 2)` so 7 rows are rendered before and after the visible rows. In total there should initially be 22 rows visible. Each of the rows have 4 Select fields, which makes it a total of 88 Select fields with each 6 Options rendered. When new rows get rendered and the old rows, outside of the `overScanCount` get unmounted. So if you scroll fast you render 29 rows, with 116 Select fields and 696 Options. This is of course too much for the browser and it needs processing time.

Summarised: The main reason is in my opinion that you render too many elements at the same time. You need to check if you can reduce the initial elements count rendered by each row.

The easiest way to reduce the number of elements would be either showing the Select fields only on click (row or cell or button in the cell, etc.) or rendering the Options only when needed. Also you could try to implement lazy loading somehow.

**Comment by MKraus92** [comment]
Sorry for not responding earlier.

The problem was the Select component, once removed the whole thing works as intended and quick at that.
I moved the edit options into a seperate Dialog so the Select is only rendered when absolutly needed.
