### ISSUE TITLE
AnalyticalTable: Dynamic row height

### ISSUE THREAD

**Issue by adeptb** [SAP/ui5-webcomponents-react#2394]
**Is your feature request related to a problem? Please describe.**
I need to display 3-5 lines of text in table cell

**Describe the solution you'd like**
Non-required prop, if passed - all rows in table will calculated dynamically, based on row content

**Additional context**
Example 
https://autodesk.github.io/react-base-table/examples/dynamic-row-heights

**Comment by Lukas742** [comment]
Hi @adeptb 

Dynamic setting of the row height is not supported due to virtualization and the resulting performance losses.
You can change the height of all rows by using the `rowHeight` prop and customize your Cell with the `Cell` column option.
Maybe you can take a look at the `Table` component, there you can fully customize each `TableRow` and thus each row height.
