### ISSUE TITLE
DynamicPageTitles overlapping when using FlexibleColumnLayout

### ISSUE THREAD

**Issue by KimParise** [SAP/ui5-webcomponents-react#2416]
Hello Colleagues,

I have an issue regarding the DynamicPageTitle component. When using the FlexibleColumn layout with a list (clicking on an item in the list will open a new column from the layout next to the list with the item details) the DynamicPageTitle of the second column will cover the DynamicPageTitle of the original page when scrolling down on the original page. You can refer to https://codesandbox.io/s/ui5-flexible-layout-with-analytical-table-forked-wnoyx?file=/src/ObjectPageTest.js to see the issue.

**Comment by KimParise** [comment]
This has been created while working closely with our UX Colleagues.

**Comment by Lukas742** [comment]
Hi @KimParise

didn't setting the `zIndex` as I suggested in Slack work for you? ([codeSandbox](https://codesandbox.io/s/ui5-flexible-layout-with-analytical-table-forked-i4it4?file=/src/ObjectPageTest.js)) If so, please elaborate why.

Also, are the UX experts that you are referring to in alignment with the Fiori Design guidelines team? I just didn't find anything in the guidelines that says that it should be possible to use a `FlexibleColumnsLayout` inside a page component. I would really appreciate if you could point me to where I can find out more about this.

**Comment by KimParise** [comment]
Hi @Lukas742 

Setting the zIndex would work using that library but after discussion with my PO, he would rather not use another library to change directly using the classes. I tried to update it using the styling in styled-components but it cannot adjust for the section tabs since those are not they're own separate component and are connected with each section instead.

**Comment by Lukas742** [comment]
You don't have to add another library, since you can use standard CSS to achieve this. [codeSandbox](https://codesandbox.io/s/ui5-flexible-layout-with-analytical-table-forked-593h4?file=/src/ObjectPageTest.js) 

Also, JSS is used by the ui5-webcomponents-react internally, so it actually is already installed. (You can see that I didn't add another dependency to the `package.json` in my first  codeSandbox example, while still importing `createUseStyles` from `jss`)
