### ISSUE TITLE
[FilterBar]: provide a way to customise a text values of an action buttons (Clear/Go)

### ISSUE THREAD

**Issue by apryviazentsau** [SAP/ui5-webcomponents-react#2467]
**Is your feature request related to a problem? Please describe.**
From usability testing we find that, when "Go" /  "Hide FilterBar / Show FilterBar" buttons are hidden, the only remaining "Clear" button confusing to the users.

**Describe the solution you'd like**
If it's possible, please provide a customisable prop for "Go"/"Clear" to make them with different text

**Additional context**
Thanks!

**Comment by Lukas742** [comment]
Hi @apryviazentsau 

the label of the buttons are implemented according to [UX guidelines](https://experience.sap.com/fiori-design-web/smart-filter-bar-annotations/) and are translated by our translation experts. Also, since offering customizations to the caption would mean that we would have to enable customizations for all other static button texts as well, that's why we decided not to offer this option.

If you feel that a translation is not fitting, please feel free to open another issue. We will then forward it to our translation experts.
