### ISSUE TITLE
Can Analytical Card be provided with an option to highlight?

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents-react#2497]
### **I am using multiple Analytical Cards on a single page and for the selection of one I want to highlight one Analytical Card**

I am using multiple Analytical Card on a web page and I need to create a selection out of the multiple Analytical Cards available and for onClick event I want to highlight the card just like outlined card in [Card](https://mui.com/components/cards/)
 
Is it possible to provide this functionality to outline the Analytical Card

**Comment by Lukas742** [comment]
Hi @Arora05 

since this is not a spec of the UX guidelines ([Card](https://experience.sap.com/fiori-design-web/cards/), [AnalyticalCard](https://experience.sap.com/fiori-design-web/analytical-card/)), you will have to use custom css to achieve this.

For example, you can overwrite the internal styles of the `AnalyticalCard` and `AnalyticalCardHeader`. E.g. `border`, `background-color`, `box-shadow`, etc. [codeSandbox example](https://codesandbox.io/s/mystifying-banzai-jodm4?file=/src/App.js)

**Comment by Arora05** [comment]
Thank You @Lukas742 for quick response.
