### ISSUE TITLE
ResponsivePopover: Popup Missing Padding  in Responsive Layout

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#2531]
**Describe the bug**
Hi colleague,
When we click icon under responsive model, the padding-top and padding-right are missing. Please take a look, Thanks!

**Isolated Example**
Normal view: padding exist:
![image](https://user-images.githubusercontent.com/78520316/151095305-71ab6dcc-dd1b-4ceb-919b-82731230c016.png)

Responsive view: padding disappear:
![image](https://user-images.githubusercontent.com/78520316/151095373-5b9e9f14-7079-4bf6-ada5-48cc90b4e1c5.png)

**To Reproduce**
1. Go to https://github.wdf.sap.corp/xweb/assignment;
2. Scroll down to 'QACAND INFO' to get login information, please use AO's info;
3. Click https://qacand.hcm.ondemand.com/sf/ompassignment?mock#/application-detail/16 or Assignment Detail Page (IC) ( Approval Pending view ) in README;
4. login in qacand, then you will see mock page, click icon in header under responsive model.

**Expected behavior**
Expect padding in responsive model.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.0.2"
`@ui5/webcomponents-react` version: "0.20.5"
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

since this has nothing to do with the `Icon` component (as you stated in your description as well), I changed the title of this issue accordingly.

Per default there is no padding applied on the content of the `ResponsivePopover` and when adding a padding yourself the styles are applied for both the popover in desktop mode and the dialog in mobile mode, so for me it's working as intended. Please add a reproducible example since I have no access to the page you provided.

**Comment by sfsf-xweb-sh** [comment]
@Lukas742  Thanks a lot. I'll check adapt in our app.
