### ISSUE TITLE
Dialog + Button: Missing margins for Buttons in footer of Dialog using design Emphasized

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#2772]
**Describe the bug**
Missing margin with two buttons using design "Emphasized" in footer component of Dialog.

**Isolated Example**
https://codesandbox.io/s/condescending-wave-e0zdre?file=/src/App.js

**To Reproduce**
1. Open the codeexample
2. See the two buttons without margins side by side

**Expected behavior**
The buttons should have a margin.

**Screenshots**
![image](https://user-images.githubusercontent.com/44802503/162691895-5c528812-e387-4799-ac57-bb2e246dee86.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: Latest
`@ui5/webcomponents-react` version: Latest
Operating System: Windows
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @C3ntraX 

there's no margin applied by design. You could either set a margin yourself or use the `Bar` component.

**Comment by C3ntraX** [comment]
Hi @Lukas742,

ok that was unexpected, because in OpenUI5 this was the case with toolbars.

**Comment by Lukas742** [comment]
If you feel like a margin or padding should be applied to the children of the `footer` and `header` of the dialog, you can open a [feature request](https://github.com/SAP/ui5-webcomponents-react/issues/new/choose) in the UI5 Web Components repo, since the `Dialog` is implemented by them. They'll let you know if this is something they'd consider as an enhancement.
