### ISSUE TITLE
Dialog: stretch is set to true, but the content of Dialog is not full stretched

### ISSUE THREAD

**Issue by gnseo** [SAP/ui5-webcomponents-react#285]
**Describe the bug**
Stretch is set to true, but the content of Dialog is not full stretched

**To Reproduce**
Installed version 0.7.1 of @ui5/web-components-react

**Expected behavior**
The content of Dialog should be full stretched.

**Comment by MarcusNotheis** [comment]
Hi @iamuan 
it looks like as it is intended that the Dialog is only streched to 90% of viewport width according to the [UI5 Web Components Documentation](https://sap.github.io/ui5-webcomponents/playground/components/Dialog/):
> strech: Determines whether the ui5-dialog should be stretched to fullscreen.
Note: The ui5-dialog will be stretched to aproximetly 90% of the viewport

@MapTo0: Do you know why it was implemented this way?

**Comment by iamuan** [comment]
@MarcusNotheis The 90% is good since this width is set for dialog container. What I mentioned was content of dialog which is div element has class name "ui5-popup-content". I update its style on debugging tool, and then the Input and Table in dialog was full sized. (The Table's width is calculated by resizing its parent element, so after update the style in debugging tool, I had to trigger some event to update state to re-render the Table.)

Please see the screenshot.
![Screen Shot 2020-01-23 at 6 54 26 PM](https://user-images.githubusercontent.com/12092761/72974094-d0ff9b80-3e11-11ea-8338-d54ecf66f22f.png)

![Screen Shot 2020-01-23 at 6 51 29 PM](https://user-images.githubusercontent.com/12092761/72973979-9433a480-3e11-11ea-9ef7-b65af9626138.png)

**Comment by MarcusNotheis** [comment]
Hi @iamuan 
sorry, I didn't see the content part of your issue.
Unfortunately, there is not much we can do to fix this issue as this is coming from the underlying UI5 Web Components - I saw you already commented the corresponding issue https://github.com/SAP/ui5-webcomponents/issues/920 as well.

**Comment by gnseo** [comment]
Thanks, @MarcusNotheis. I'm closing this issue and waiting from SAP/ui5-webcomponents#920.
