### ISSUE TITLE
Webpack: Failed to parse source map

### ISSUE THREAD

**Issue by dwwinters** [SAP/ui5-webcomponents-react#2876]
**Describe the bug**
Getting close to 200 warnings from webpack with the latest version of ui5-webcomponents-react (v0.23.1) when I run `npm run start` on a CRA starter shell.  Most warnings are with respect to failing to load source maps from `@zxing/library`.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. `npx create-react-app my-app`
2. `cd my-app`
3. `npm install @ui5/webcomponents-react @ui5/webcomponents @ui5/webcomponents-fiori --save`
4. Add `ThemeProvider` per [instructions](https://github.com/SAP/ui5-webcomponents-react#add-ui5webcomponents-react-to-an-existing-app)
5. `npm run start`

**Expected behavior**
App should launch via dev server without warnings from webpack.

**Screenshots**
Example of one of the warnings:
WARNING in ./node_modules/@zxing/library/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '<path>/my-app/node_modules/@zxing/src/index.ts' file: Error: ENOENT: no such file or directory, open '<path>/my-app/node_modules/@zxing/src/index.ts'

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.3.1
`@ui5/webcomponents-react` version: 0.23.1
Operating System: MacOS
Browser: Chrome

**Additional context**
Just trying to add react web components to an existing app per instructions: https://github.com/SAP/ui5-webcomponents-react#add-ui5webcomponents-react-to-an-existing-app
I do not get these errors when using the web components directly from a react application.

**Comment by MarcusNotheis** [comment]
Hey @dwwinters,

thanks for reaching out.
Unfortunately, I think there nothing we can do to fix this issue as the warnings are originated from a third-party node module (`@zxing/library`). There is also an issue reported for this library stating the exact same issue: https://github.com/zxing-js/library/issues/512

I would assume that you don't see these warnings in your existing application because it is still running on react-scripts v4 (= webpack v4). 
When creating a new application, you're using react-scripts 5 (= webpack 5) and these warnings have started to come up with webpack v5.

**Comment by dwwinters** [comment]
Thanks for information @MarcusNotheis.  I'll close the issue.
