### ISSUE TITLE
Filterbar: Button Placement is not consistent in Filterbar

### ISSUE THREAD

**Issue by nidhi0104** [SAP/ui5-webcomponents-react#2990]
In filterbar the placement of buttons(eg-Go,Filters,Clear etc) is not consistent.If we don't use variants property, all buttons are placed after the filter. But when we use the variants property for implementing Variant Management for the filters, the buttons placement changes and it appears on the top of all filter not after the filter. So apps with variant management and without variant management looks inconsistent.

**Expected behavior**
The buttons placement should be consistent for both the mentioned cases.

**Screenshots**
![image](https://user-images.githubusercontent.com/105447668/170231807-a7315270-0f09-4b8e-a4ec-1922aeff10d0.png)

![image](https://user-images.githubusercontent.com/105447668/170232223-f8baefcc-5d49-46c8-9982-b0db87c08038.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ~1.3.1
`@ui5/webcomponents-react` version: v0.24.0
Operating System:M1
Browser:Chrome

**Comment by Lukas742** [comment]
Hi @nidhi0104 

the buttons are only displayed in the bottom section of the FilterBar if `useToolbar` is set to `false`. So if you want to display the variant (or view) selection e.g. in a DynamicPage instead of the FilterBar itself, you can use `useToolbar` for this. Otherwise the default is preferable. 

Examples of the SAP UI5 implementation for both cases:
- [with VariantManagement inside the FilterBar (`useToolbar={true}` --> default)](https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar/sample/sap.ui.comp.sample.smartfilterbar.example1)
- [with VariantManagement inside the DynamicPage  (`useToolbar={true}`)](https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar/sample/sap.ui.comp.sample.smartfilterbar.example2)
