### ISSUE TITLE
Filterbar: Buttons not translated to different languages

### ISSUE THREAD

**Issue by KimParise** [SAP/ui5-webcomponents-react#2991]
We are using the component on our application but when we change the language the button do not change. We have implemented i18n but since we do not have access to the button text, we cannot update them.

**Expected behavior**
The buttons texts should change to the respective language when the user changes their account settings to a different language.

**UI5 Web Components for React Information**
`@ui5/webcomponents` 1.0.2:
`@ui5/webcomponents-react` 0.20.5:
Operating System: Windows 10
Browser: Chrome

**Comment by MarcusNotheis** [comment]
Hey @KimParise,
thanks for reporting this issue!
Could you please share a reproducible sample (e.g. a codesandbox using this [template](https://codesandbox.io/s/rough-snow-sdtesq)?)

**Comment by KimParise** [comment]
Hi @MarcusNotheis 
Please follow the link below to the reproducible sample.
https://codesandbox.io/s/filterbar-language-issue-fmnvqh?file=/src/index.js

**Comment by MarcusNotheis** [comment]
Hey @KimParise,

in order to change the language for UI5 Web Components, you'll have to call the corresponding function:
```
import { setLanguage } from "@ui5/webcomponents-base/dist/config/Language.js";
setLanguage("fr-FR");
```
[UI5 Web Components Docs](https://github.com/SAP/ui5-webcomponents/blob/main/docs/2-advanced/01-configuration.md#language)

I've also updated your codesandbox example: https://codesandbox.io/s/filterbar-language-issue-forked-ji860c?file=/src/App.js

Does that work for you in your app?
