### ISSUE TITLE
MultiComboBox : Item not shown properly because of white area

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents-react#3033]
**MultiComboBox : Item not shown properly because of white area**
Visibility of selected items is reduced as there is white space shown in MultiComboBox as seen in [CodeSandbox](https://codesandbox.io/s/elegant-lichterman-vysi7j?file=/src/App.js) and
![Screenshot (309)](https://user-images.githubusercontent.com/89779778/172341420-dfea9ae8-bc02-431a-b0de-64c72bd97e2f.png)

**Comment by Lukas742** [comment]
Hi @Arora05 

this behavior is implemented by [design](https://experience.sap.com/fiori-design-web/multi-combobox/#multiple-selected-items). When the MultiComboBox field is focused and there is not enough space to display all tokens, the tokens are displayed in a scrollable row. And the text area is necessary because users wouldn't be able to enter anything without it.
