### ISSUE TITLE
[SF][0.23.2][DynamicPageTitle] Page title should display as much as more text when it's very long

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#3089]
When in mobile screen or a very narrow screen, there's only an overflow button in the toolbar. But the div `data-component-name="DynamicPageTitleActions"` which wraps toolbar actually wider than the overflow button's width, which makes the page title could not make fully use of the spaces given by the toolbar.

Is there any possibility that you could maybe increase the shrink value of `data-component-name="DynamicPageTitleActions"` (increasing shrink value was just what I thought, any other working solution would be great) so that the page title on the left side can have more spaces to display? We have very long page title sometimes, that's why we ask.

Will provide demo link and infos separately.

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

the `flex-shrink` factor is the same as with [SAPUI5](https://sapui5.hana.ondemand.com/#/entity/sap.f.DynamicPage/sample/sap.f.sample.DynamicPageFreeStyle), that's why we decided against chaining it in our implementation.

To change it on your side you can use the mentioned `data-` attribute to select the container and set the custom styles there. --> [codeSandbox](https://codesandbox.io/s/dynamicpage-custom-title-tx0m5z?file=/src/App.js&resolutionWidth=390&resolutionHeight=844)
