### ISSUE TITLE
Menu is not available

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents-react#3096]
Hi everyone,

In the SAP ui5 web components web site it says there is a `Menu` and `MenuItem` components, but when I try to use them I get an error saying they are not available. I checked and they are not inside the package.

https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-menu--default-story

Am I doing something wrong or are these components not available?

Thank you!

**Comment by vital487** [comment]
Hi @MarcusNotheis,

I'm using `"@ui5/webcomponents": "~1.0.2"` and `"@ui5/webcomponents-react": "^0.20.5"`.

**Comment by MarcusNotheis** [comment]
Thanks for getting back.
In this case your versions of UI5 Web Components (for React) are too old, the `Menu` is a quite new component.
In order to use the Menu, you'll need to update to `@ui5/webcomponents@~1.3.0` and `@ui5/webcomponents-react@^0.23.0` or later.

I'll create a follow up issue to add the versions when a component was added our documentation.

**Comment by vital487** [comment]
Thank you. It worked!
