### ISSUE TITLE
[Select] expose `Option` value as `e.target.value`

### ISSUE THREAD

**Issue by jens-ox** [SAP/ui5-webcomponents-react#3110]
Hi!

I have the following setup:

```jsx
<Select onChange={onChange}>
  <Option value="1">Option 1</Option>
  <Option value="2">Option 2</Option>
</Select>
```

For `onChange`, I'd like to be able to do something like
```js
const onChange = (e) => setThing(e.target.value)
```

The only way I could find to achieve that is by doing
```js
const onChange = (e) => setThing(e.detail.selectedOption.value)
```

I think this is subpar as
1. it doesn't adhere to standards and
2. it's currently not typed.

**Comment by Lukas742** [comment]
Hi @jens-ox 

since under the hood the `Select` component is still a web-component it doesn't offer the same behavior as a native `select`. 
The recommended way of setting and accessing custom values (which are not included in the `children` of the `Option`) is to use the data attribute of the `Option`. See [codeSandbox](https://codesandbox.io/s/old-waterfall-ef3mgw?file=/src/App.tsx)

I also noticed that our typings are wrong for the events. For the `target` I created a [PR](https://github.com/SAP/ui5-webcomponents-react/pull/3111) that should fix that, for elements returned in `event.detail` we have to stick to `HTMLElement` for the time being as the API of the UI5 Web Components currently doesn't give us the correct type of the elements.

Is this approach sufficient for you, or do you still feel that the `Select` web-component should be enhanced in this matter?

**Comment by jens-ox** [comment]
Hi @Lukas742, wow, that was quick! ☺️ 
I think if the typings work fine it's ok. One option would also be to extend the `Select` component a bit (assuming that `Option` is the only valid type of child inside `Select`):

```tsx
import { Option, Select as S } from '@ui5/webcomponents-react'

interface Option {
  text: string
  value: string
  disabled?: boolean
}
interface SelectProps {
  onChange: (value: string) => void
  value: string | null
  options: Array<Option>
}
export const Select: React.FC<SelectProps> = ({ options, onChange, value }) => (
  <S onChange={(t) => onChange(t.detail.selectedOption.value)}>
    {options.map((o) => (
      <Option key={o.value} value={o.value} selected={value === o.value} disabled={o.disabled}>
        {o.text}
      </Option>
    ))}
  </S>
)
```

But this would significantly change the API.

One thing that could be done though is to extend the docs with information on how to use the `value` field (or explicitly state that `data-*` fields should be used instead of `value`).

**Comment by Lukas742** [comment]
Thanks for the suggestion, we have discussed this internally before about another component and came to the conclusion that we will not extend web-components. This is mainly due to the following reasons:

- We want to avoid discrepancies between "pure" ui5-web-components and our wrapper implementation, because this would mean that we are no longer a wrapper per se.
- The maintenance of the components would increase a lot, because we have to check after each update if everything still works with the extended logic and also if features that have been added are supported.


We actually mention the data attributes in our documentation already (here under [Recipes](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-select--default-story)) ;)

**Comment by jens-ox** [comment]
> We actually mention the data attributes in our documentation already (here under [Recipes](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-select--default-story)) ;)

Yeah, I saw that, I'd just add that one should use `data-*` instead of `value` explicitly.

**Comment by Lukas742** [comment]
We'll look into that, thanks for the suggestion. 
Since the original issue has been resolved I'm going to close this issue.
