### ISSUE TITLE
Analytical Table Height issue with DynamicPage

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents-react#3115]
When we use an AnalyticalTable inside a DynamicPage, two scrollbars are loaded in the page, which shouldn't happen. 
- [Code SandBox](https://codesandbox.io/s/hidden-dawn-60040x) 

If we have UIFilterbars loaded on the page and the entire page is wrapped inside the startColumn of a FlexibleColumnLayout, then on pop-in, it becomes difficult to navigate through the page. 

Expected Behaviour - 

When we are using the property - adjustTableHeightOnPopIn in our AnalyticalTable, the table shouldn't have a scrollbar, but the container must have a scrollbar instead.

**Comment by Lukas742** [comment]
Hi @I516406 

I'm not sure if I understood the problem. In your description you talk about the `adjustTableHeightOnPopIn`, but you don't use it in the codeSandbox. Also this prop takes only effect if a column is "popped-in", so it actually has nothing to do with the initial table container.
If you want the table to display all it's rows without having to scroll, you can set `visibleRows` to a very high number like `Infinity` but this will disable the virtualisation of the table rows, so you may face performance issues with tables with a large dataset.

**Comment by I516406** [comment]
Hi @Lukas742 

If you look at the [Code SandBox](https://codesandbox.io/s/hidden-dawn-60040x) now, I have updated it to elaborate my concern. 
We actually can't set the visibleRows to a very high number as you said it will affect the performance. 
If you try clicking on the table row, you'll notice what I am saying about. Let me know if you need any further clarifications.

**Comment by Lukas742** [comment]
Sorry, but I'm still not clear what behavior you want to achieve.

The table always receives a scrollbar if more rows are rendered than set in `visibleRows` (defaults to 15), without `adjustTableHeightOnPopIn` the container keeps the height of the non "popped-in" rows (in this case 44px per row), so it doesn't take into account that the row heights increase when columns are popped-in. If you set the prop to `true` the container increases its height according to the updated visible row heights (in this case 104px per row). 

As you add 21 rows to the table, there always will be a scrollbar inside the table, because of the default `visibleRows` number of 15 and since the table increases its height when popped-in the section of the FlexColLayout also is scrollable.

**Comment by I516406** [comment]
Now I got it. What we are trying to achieve isn't possible without putting visibleRows to a greater number, which will in turn affect the performance. 
Thanks for your time and effor @Lukas742
