### ISSUE TITLE
Support SAPUI5 Flexibility for the VariantManagement control

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-webcomponents-react#3168]
When using SAP Fiori Elements there is support for SAPUI5 Flexibility out-of-the box. This allows the user to save search variants, hide or add search filters and configure the table layout of an app based on the List Report Object Page (LROP) floorplan. As described in [Bootstrapping SAPUI5 Flexibility](https://sapui5.hana.ondemand.com/#/topic/642dab291a7b47ec9d46c39b3c482aba) the SAPUI5 Flexibility support also Locale Storage which can be used during local development. When deployed to SAP BTP the [SAPUI5 Flexibility service](https://help.sap.com/viewer/product/UI5_FLEXIBILITY/Cloud/en-US?expandAll=true) can be used for persistence.

I would expect that the UI5 Webcomponents for React would add the functionality that SAP Fiori Elements has also in the [VariantManagement](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--default-story) control. The complexity of storing the personalization information should be abstacted away like it's already done in SAPUI5.

**Comment by Lukas742** [comment]
Hi @gregorwolf 

unlike SAPUI5, OpenUI5 or Fiori Elements, UI5 Web Components for React is a pure component library. Therefore, we unfortunately cannot provide any interface for data processing or data binding.

**Comment by gregorwolf** [comment]
During UI5con 2022 @bendkt and @martinhaeuser presented the Workshop [P13nify Everything - Personalization for Any Control](https://bendkt.github.io/ui5con2022-p13n-ws/) which is also available as a recording on YouTube: [UI5con HYBRID 2022: P13nify Everything - Personalization for Any Control (Workshop)](https://www.youtube.com/watch?v=LclKOae-ts0). I would like to know if it is possible to use the sap.m.p13n.modification.FlexModificationHandler in the UI5 Webcomponent for React VariantManagement?

**Comment by Lukas742** [comment]
Hi @gregorwolf 

we think that such issues can’t be solved in a library which is only targeting the React ecosystem - otherwise we would need to rebuild the same functionality for Vue, Angular, Svelte and all the other frameworks which might get relevant in the future.
In our opinion the best way to solve this issue would be that a central team maintains some kind of an official JS Client, e.g. bound to the BTP Flexibility Service. Then we could discuss if offering an “react-optimized” adapter for this client is something we can offer. (only our personal opinion, not part of any roadmap!)
