### ISSUE TITLE
onKeyDown property missing on Input documentation

### ISSUE THREAD

**Issue by stefanomantova** [SAP/ui5-webcomponents-react#3212]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Description of the issue**
onKeyDown property missing on [Input documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--default-story). This is a valid JSX Attribute (React.KeyboardEventHandler<HTMLElement> | undefined) under UI5-Webcomponents Input component and therefore might be able to mention and detail in on the respective documentation.

**Comment by MarcusNotheis** [comment]
Hey @stefanomantova,

thanks for reaching out!
You're totally right, `onKeyDown` is a valid prop for the Input Component, as well as for all other Web Components as well.
We have decided not to list all standard HTML Props in our Props Table, because this would add hundreds of props which would make this table unreadable.
Do you think an additional note like below would make it better?
> **In addition to these props, all standard HTML props are supported as well**

Or would you have another proposal?

**Comment by stefanomantova** [comment]
Hi @MarcusNotheis,

Thanks for your quick answer! 

Sounds good! I didn't know that the Web Components could also carry the standard HTML Props. For me, it does make sense to add this additional note in the documentation. Should the same approach be followed for the documentation of other components which are similar to HTML?

**Comment by MarcusNotheis** [comment]
Yes, in general, almost all of our components are supporting all HTML (with the exception of FormItem and FormGroup).

We'll add that note then to all the components 🙂
