### ISSUE TITLE
FilterBar: Adapt Filters label is wrong in Portuguese

### ISSUE THREAD

**Issue by anfavretto** [SAP/ui5-webcomponents-react#3259]
**Describe the bug**
The label of the Adapt Filters button on the FilterBar is wrong. 

**Isolated Example**
 -

**To Reproduce**
1. Add the FilterBar component in a screen
2. Set the language as Portuguese (key "pt")
3. See the Adapt Filters label as "Ajustar filtros"

**Expected behavior**
[Adapt Filters label](https://github.com/SAP/ui5-webcomponents-react/blob/2b1b1cb0e5d4306b1daa502850751d84b1d0211e/packages/main/src/i18n/messagebundle_pt.properties#L56) should be "Adaptar filtros" in Portuguese instead of "Ajustar filtros"

**Screenshots**
![Screen Shot 2022-07-18 at 20 17 06](https://user-images.githubusercontent.com/18503607/179632550-d572c867-82b8-4883-b965-4fd0c5c9aeb4.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0
Operating System: macOS Monterey 12.4
Browser: Chrome

**Additional context**
This is a request for our internal SAP project.

**Comment by MarcusNotheis** [comment]
Internal Incident created: 2280143894

**Comment by MarcusNotheis** [comment]
Hey @anfavretto,
can you try setting the language to `pt_PT` instead of `pt`? Then the label should be correctly translated.

**Comment by anfavretto** [comment]
Hi @MarcusNotheis, actually right now we are setting as "pt-BR".

**Comment by MarcusNotheis** [comment]
I've just compared our translations with the SAPUI5 translations and it looks like both libraries are using `Adjustar filtros` for `pt_BR` and `pt` in general ([see here](https://ui5.sap.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.ui.comp.sample.smartfilterbar.example2&sap-ui-xx-sample-origin=&sap-ui-xx-dk-origin=https%3A%2F%2Fui5.sap.com&sap-ui-theme=sap_horizon_dark&sap-ui-rtl=false&sap-ui-density=sapUiSizeCompact&sap-ui-language=pt_BR).

If I would change the language to `pt_PT`, then the label would be adjusted to `Adaptar filtros`. ([see here](https://ui5.sap.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.ui.comp.sample.smartfilterbar.example2&sap-ui-xx-sample-origin=&sap-ui-xx-dk-origin=https%3A%2F%2Fui5.sap.com&sap-ui-theme=sap_horizon_dark&sap-ui-rtl=false&sap-ui-density=sapUiSizeCompact&sap-ui-language=pt_PT)).

I would assume that this is caused by the fact that we have no explicit translation for `pt_BR`, so we're falling back to `pt`.
@ilhan007 @vladitasev Would it make sense to add translations for `pt_BR` as well?

**Comment by MarcusNotheis** [comment]
Hey @anfavretto,
we had another internal discussion and we think there is nothing we can do here to change the translation.
The translation is in sync with SAPUI5 and the translation system is not offering any more possibilities to allow for additional translation for `Portuguese - Brazil`.

Sorry that I can't give you a more positive answer here.
