### ISSUE TITLE
Console errors reported with test case execution using React Testing Library for createUseStyles [React JSS]

### ISSUE THREAD

**Issue by pawannchawla** [SAP/ui5-webcomponents-react#3275]
**Describe the bug**
We observe with the latest upgrade there are several console errors reported with test case execution using React Testing Library for createUseStyles [React JSS]

Old[Currently in use] vs New Versions of UI5 Libs[Targetted Upgrade]:
![image](https://user-images.githubusercontent.com/88163844/180252079-199592fc-3f2c-428b-9a87-aa4cbe5f922a.png)

**To Reproduce**
1. Add the react testing library in the project for testing
2. Work with styling module from react i.e. createUseStyles
![image](https://user-images.githubusercontent.com/88163844/180190061-e6c70413-3772-4f29-9183-4fd98bea9817.png)
![image](https://user-images.githubusercontent.com/88163844/180190127-c454919f-b56e-4f8b-9b80-7d02fce48cfa.png)

4. Run the tests on the components created
5. See error for each test case [The test passes but logs are full with below]

![image](https://user-images.githubusercontent.com/88163844/180188968-9c7bf95d-0ee6-42bb-80c7-a0e96f86be9b.png)
6. Also attaching the project which can be used to reproduce the issue.
[UI5Upgrade.zip](https://github.com/SAP/ui5-webcomponents-react/files/9160552/UI5Upgrade.zip)

8. Please download it, run npm install and npm run test to see the failure logs

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0
Operating System: Windows 10
Browser: Google Chrome

**Comment by MarcusNotheis** [comment]
Thanks for reporting!
This error is caused by the css variables which are part of the `@sap/theming-base-content` package and I've already opened an issue there: https://github.com/SAP/theming-base-content/issues/9

It looks like that those CSS Variables are actually valid and those errors are caused by the underlying JSDOM library which is not capable of parsing them, so I guess there is nothing we can do on our side.

Sorry that I can't give you a better answer here.
