### ISSUE TITLE
AnalyticalTable: Grouped table jumps to focused cell on horizontal scroll bar click.

### ISSUE THREAD

**Issue by codingfabi** [SAP/ui5-webcomponents-react#3285]
### **Bug Description**
If you group a table multiple times and then focus a cell, scroll further down and click on the horizontal scrollbar, the table jumps back to the previously focused sell.

### **Expected Behavior**
I would the table expect to scroll just normally. 

### **Steps to Reproduce**
1.  removed internal link
2. Add the "longColumn" to the columns.
3. Select scaleWidthMode to "Grow"
4. Group the table by at least two columns (e.g. "name" and "age")
5. Select a expanded column such that the browser focus is in the column.
6. Scroll down until the focused column is not visible anymore.
7. Click the horizontal scrollbar:

-> The table jumps back to the focused column.

```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by Lukas742** [comment]
This issue does not only happen when grouping a row, just is more noticeable there. 

To reproduce it:

1. Table needs to overflow horizontally so that the horizontal scrollbar is displayed.
2. focus a cell either by click or by keyboard navigation
3. vertically scroll the table, so that the previously focused cell is unmounted due to virtualization
4. See that when clicking the horizontal scrollbar, the table focuses a cell which is now available in the DOM (probably the first cell of the middle row of all currently rendered rows)
