### ISSUE TITLE
[SF][Text][0.27.0]custom styles for Text component overwritten by internal Text styles

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents-react#3304]
**Describe the bug**
Styles add to Text component overwritten by internal Text styles

**Isolated Example**
https://codesandbox.io/s/text-component-classname-o8e9b7?file=/src/App.js

**To Reproduce**
1. Go to [codesandbox example](https://codesandbox.io/s/text-component-classname-o8e9b7?file=/src/App.js)
2. Inspect the style add to Text component
3. See the custom `font-size` attribute is overwritten by internal Text `font-size`

**Expected behavior**
Custom styles should override internal component styles correctly.

**Screenshots**
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/27538066/181528323-fd073c3e-d545-4c1a-a695-27f47a7ae052.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.0
Operating System: MacOS
Browser: Chrome

### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

**Comment by MarcusNotheis** [comment]
Hey @ksblklu,

I've looked into this issue but I don't think there is a solution available from UI5 Web Components for React side.
Our CSS Selector has a specificity of 1, so we can't get really lower on that one (except using `:where()` but I haven't found a solution using react-jss).

I can't open the codesandbox at the moment due to firewall restrictions, but I can you check whether the import of your CSS Module is happing after the import of our `Text` component? Then the order should be fine and your custom styles should work.
