### ISSUE TITLE
Grid: Memory Leak

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#335]
**Describe the bug**
It looks like if you rapidly mount and unmount a grid component, there is a timeout which tries to update a component state after the component has been unmounted.

**To Reproduce**
1. Render a grid in a component
2. Mount and unmount that component rapidly

**Expected behavior**
No error should be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/8775211/75604274-390f6480-5ad7-11ea-909c-2a7a29aa7d29.png)

**UI5 Web Components for React Information**
Operating System: MacOS
`@ui5/webcomponents-react` version: 0.8.5
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: 1.0.0-rc.5

**Additional context**
https://openui5.slack.com/archives/CSQEJ2J04/p1581978699027800

**Comment by LuisValgoi** [comment]
Hi Marcus, I saw that you have mentioned that this bug was fixed, but I'm still receiving this error.

![image](https://user-images.githubusercontent.com/8363610/77856695-48b1c400-71cf-11ea-9a74-679914576499.png)

![image](https://user-images.githubusercontent.com/8363610/77856698-50716880-71cf-11ea-9674-87f119ab3a01.png)

**Comment by MarcusNotheis** [comment]
Finally found the root cause and fixed it.
Released in `@ui5/webcomponents-react@0.9.0-rc.9`
