### ISSUE TITLE
[SF][0.27.3][ActionSheet]Adopt external accessibleName of ActionSheetButtons  

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents-react#3370]
**Is your feature request related to a problem? Please describe.**
For buttons in `ActionSheet`, we noticed that it has an internal `accessibleName` attribute:https://github.com/SAP/ui5-webcomponents-react/blob/d14a631c72fa3672656a5ccb69da830ddaf0c363/packages/main/src/components/ActionSheet/index.tsx#L92.
But if the button has its own `accessibleName` attribute, it would override the internal "button child text, index of total" accessibleName. 

**Describe the solution you'd like**
So can we merge both the internal and external accessibleName, and set it to the `Button` element? For example:
```
<ActionSheet>
    <Button accessibleName="a11y text">text</Button>
    <Button>text 2</Button>
</ActionSheet>
```
then the expected accessibleName of the first Button is "a11y text,  text item 1 of 2"

**Describe alternatives you've considered**

**Additional context**

**Comment by Lukas742** [comment]
Hi @ksblklu 

we had a discussion about this when we implemented the `accessibleName` and we came to the conclusion that if the `accessibleName` is controlled by the app developer, they should take full responsibility of it. The main reason for this is that some may want the "item x of y" announcement and some may not. To differentiate between these two options we would need to add another interface so this could be controlled as well. So this would add another layer of complexity which we decided against implementing, since most app developers only use default behavior and the behavior you describe is more of an edge case.

**Comment by ksblklu** [comment]
@Lukas742  Thanks for the information! I'll add the expected accessibleName manually.

**Comment by ksblklu** [comment]
Hi @Lukas742 I also have a question about the structure of action sheet. In WC Menu, I see ul/li being used for structuring. Wondering why we are not adapting the same list structuring in this action sheet?

**Comment by Lukas742** [comment]
A Menu ist a popover holding list elements which you can customize by setting props to the `MenuItem` and also it allows you to nest its children. An ActionSheet is a simpler component, which you should only use if you don't need much customizations. 

We didn't implement it as list because we followed the implementation of the SAPUI5 ActionSheet, where also only buttons are rendered. Also I noticed that the Design team now states, that you should use a Menu whenever possible as the ActionSheet comes with limitations (See [here](https://experience.sap.com/fiori-design-web/action-sheet/)), since I'm not aware what these limitations are I unfortunately cannot tell you more.
