### ISSUE TITLE
Toolbar: Missing close function on ui5-popover can lead to application crash

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents-react#3499]
**Describe the bug**
[The `useEffect` hook of the `Toolbar` `OverflowPopover` calls the `close` function on a ref to a `ui5-popover` element.](https://github.com/SAP/ui5-webcomponents-react/blob/f4bf7bf8c15c72b030503e0b0a731d1791e063a2/packages/main/src/components/Toolbar/OverflowPopover.tsx#L63)
However, for whatever reason, `ui5-popover` doesn't always expose a `close` function; leading to a function call on `undefined`, resulting in an application crash.

I propose adding an additional check for the existence of `popoverRef.current.close` and escalating this issue upstream.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.7.1
`@ui5/webcomponents-react` version: 0.28.0
Browser: Chrome 104

**Comment by Lukas742** [comment]
Hi @goodefroi 

thanks for reporting. The root cause for the crash is most probably, that the underlying customElement of the `ui5-popover` web-component is not yet defined and therefore the `close` property is not yet registered. The linked PR fixes the issue, as we now control the open state by leveraging the `open` property of the component.

**Comment by goodefroi** [comment]
That was quick, thanks a lot. <3
