### ISSUE TITLE
[SF][Feature Request][DynamicPage] Provide us a parameter to get the height of DynamicPageTitle DOM

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#3550]
Dear colleagues,
I am from SuccessFactors Web Experience Shanghai team.

Provide us a parameter to get the height of DynamicPageTitle DOM

![Screen Shot 2022-09-21 at 10 51 27 AM](https://user-images.githubusercontent.com/78520316/191428178-c2efb15c-01f1-4a36-a1d3-e977cd87bf92.png)

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh

you can get the height by accessing the HTMLElement of the `DynamicPageTitle`. You can achieve that by either using a React Ref (recommended way) or by using e.g. a `querySelector`. If you want to update the component corresponding to the height of the DynamicPageTitle you could use a `ResizeObserver`.

Since not everyone will need this feature and implementing e.g. a callback that is fired each time the height of the `DynamicPageTitle` changes, would require us to implement another ResizeObserver, we decided not to offer this option and leave it up to the app developer to implement.
