### ISSUE TITLE
AnalyticalTable: "Sort column by" popover not adapting to compact mode.

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#3559]
**Describe the bug**
The UI's default density mode is 'Cozy', but we have set it to 'Compact' by adding `className="ui5-content-density-compact"` to our outermost component. This works fine, except for the AnalyticalTable, where when clicking on a column header, the "sort by" popover is still shown in cozy mode.
We've had the same problem with a popup which we rendered with a `ReactDOM.createPortal(popup, document.body);`, and which was therefore outside the DOM hierarchy of the app, so the setting wasn't inherited. We had to set the above className on the popup as well, which made it work. Maybe it's the same problem here.

**Isolated Example**
If it worked, here's a [sandbox](https://codesandbox.io/s/broken-firefly-dt4nk3?file=/src/App.js).
Otherwise, here's the code:
```
import React from "react";
import { AnalyticalTable, ThemeProvider } from "@ui5/webcomponents-react";

export default function App() {
  return (
    <ThemeProvider>
      <AnalyticalTable
        className="ui5-content-density-compact"
        data={[
          {
            name: "Germany",
            path: ["Germany"],
            country: undefined,
            description: undefined
          },
          {
            name: "France",
            path: ["France"],
            country: undefined,
            description: undefined
          }
        ]}
        columns={[
          { id: "name", accessor: "name", Header: "ID" },
          { id: "description", accessor: "description", Header: "Description" }
        ]}
        subRowsKey={"children"}
        style={{
          inlineSize: "100%",
          blockSize: "100%"
        }}
      />
    </ThemeProvider>
  );
}
```

**To Reproduce**
Click on a column header of the table

**Expected behavior**
The popover should be in compact mode, but it's in cozy.

**Screenshots**
Let me know if you need one.

**UI5 Web Components for React Information**
@ui5/webcomponents version: "1.7.1"
@ui5/webcomponents-react version: "0.28.1"
Operating System: Win10
Browser: Chrome

Thanks a lot in advance!

**Comment by Lukas742** [comment]
Hi @ej612 

the `AnalyticalTable` uses a [React Portal](https://reactjs.org/docs/portals.html) to render the `Popover` inside the `document.body`. Because of that the element is not inside the context of the `class` which is applied to the component. 

If you want to only display the `AnalyticalTable` in compact mode, then you can add a container where the `Popover` should be mounted yourself and set the CSS class name there as well. I edited your [codeSandbox](https://codesandbox.io/s/agitated-raman-nechk6?file=/public/index.html) to give you an example how this can be achieved.

The linked PR will also add a Knowledge Base entry explaining this.
