### ISSUE TITLE
AnalyticalTableHooks: Error with NextJS framework

### ISSUE THREAD

**Issue by irodrigob** [SAP/ui5-webcomponents-react#3693]
**Describe the bug**
A project created with NextJS when starting it gives the following error:

"error - D:\github\test-nextjs\node_modules\@ui5\webcomponents-react\dist\index.js:1
import * as AnalyticalTableHooks from './components/AnalyticalTable/pluginHooks/AnalyticalTableHooks';
^^^^^^

SyntaxError: Cannot use import statement outside a module"

**To Reproduce**
1. Create NextJS project:  npx create-next-app test-nextjs
2. Install UI5 packages: npm install @ui5/webcomponents @ui5/webcomponents-fiori @ui5/webcomponents-icons @ui5/webcomponents-icons-tnt @ui5/webcomponents-react
3. Run the project: npm run dev
4. When entering localhost:3000 the error occurs.

**Expected behavior**
Which works just like React.

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "^1.8.0",
    "@ui5/webcomponents-fiori": "^1.8.0",
    "@ui5/webcomponents-icons": "^1.8.0",
    "@ui5/webcomponents-icons-tnt": "^1.8.0",
    "@ui5/webcomponents-react": "^1.2.2",
    "next": "^13.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"

In versions of nextJS 12.x.x the same error also occurs.

Operating System: Windows 10
Browser: Chrome 107.0.5304.87

**Comment by MarcusNotheis** [comment]
Thanks for reaching out @irodrigob!

When using Next 12, you'll need to install the [`next-transpile-modules`](https://www.npmjs.com/package/next-transpile-modules) plugin and add all ui5-web-components packages there:

```js
// next.config.ts
const withTM = require('next-transpile-modules')([
  '@ui5/webcomponents',
  '@ui5/webcomponents-fiori',
  '@ui5/webcomponents-base',
  '@ui5/webcomponents-icons',
  '@ui5/webcomponents-react',
  '@ui5/webcomponents-react-base'
]); // pass the modules you would like to see transpiled

module.exports = withTM({
  // rest of your next config 
});
```

Regarding Next 13:
Are you using the `pages` directory or the `app` directory?
I'm just about to transfer one application to the `app` directory and most things are working out of the box for me (I had to add `'use client';` to the top of almost every file in the `app` directory due to the nature of Web Components).
If you could share a sample repository it would be highly appreciated.

**Comment by irodrigob** [comment]
Thank you very much for the help. 

The truth is that I had to make the project in React due to the problem with the components.

When I have an example mounted I will inform you so that you can see it.

Greetings and thanks

**Comment by MarcusNotheis** [comment]
There is one thing I forgot to mention: As UI5 Web Components for React is using Custom Elements in most of our components, we only support client side rendering and SSR. 
When using UI5 Web Components for React with NextJS, I usually have one catch-all page, e.g. `pages/[[...app]].tsx` where I use a `next/dynamic` import with the `{ ssr: false }` option to load my whole application.

Having said that, I think there is currently no way of using the full feature set of NextJS, with my setup it's rather a drop-in replacement for `create-react-app`.

In order to support SSR in the future, we need to have https://github.com/SAP/ui5-webcomponents/issues/2240 solved first.

**Comment by irodrigob** [comment]
I had looked at the solution you mention but had not implemented it, but I see that it is the only solution.

Luckily, I don't need the SSR at the moment. So I'll test to see how it works.

Thanks for everything.

**Comment by MarcusNotheis** [comment]
Hey @irodrigob,

just wanted to let you know that we've started working on an improved support for static site generators like Next.
I would recommend following the progress in #4091, so I would close this issue now.

Thanks!
