### ISSUE TITLE
AnalyticalTable: When set to fill surrounding container, only shows entire rows

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#3743]
**Is your feature request related to a problem? Please describe.**
When setting `visibleRowCountMode={TableVisibleRowCountMode.Auto}` on the AnalyticalTable, it takes up the height of the surrounding container. Our table is in a resizable dialog, and so as the user resizes the dialog, the table resizes along with it.
This works perfectly well, except that the table will only grow or shrink in steps of entire rows. If, say, the surrounding container has a height of 108px, and each row a height of 10px, the table will resize to 100px, as the remaining 8 are not enough to display a full row.
However, our UX department is of the unanimous opinion that the expected behavior would be for the table to take up all the available space, i.e. 108px, and for the last row to be displayed partially, comparable to the behavior of the list on a [SelectDialog](https://sapui5.hana.ondemand.com/#/entity/sap.m.SelectDialog/sample/sap.m.sample.SelectDialog).

**Describe the solution you'd like**
Is it possible to add a setting to the AnalyticalTable component that specifies whether the table will grow continuously as opposed to in steps of entire rows only? Maybe as an additional TableVisibleRowCountMode?

**Describe alternatives you've considered**
I can't think of a way to work around this issue.

**Additional context**
I have created a [sandbox](https://codesandbox.io/s/focused-bouman-rx6h9p?file=/src/App.js) visualizing the current behavior.
I will provide more context via DM.

Thanks a lot in advance!

**Comment by Lukas742** [comment]
Hi @ej612 

this is the intended behavior and we would like to keep it that way, because even if it makes sense in your use case, in most cases this leads to a bad UX. (Two scrollbars, hidden content, etc).
If you want the table to not implement internal scrolling inside the table body, you can set `visibleRows` to `Infinity` for example. This will then render all rows into the container, but will not virtualize them anymore, which may cause performance problems.
Maybe even the `Table` component is more suitable here.

**Comment by Lukas742** [comment]
Hi @ej612 

Without virtualization, fixed header, etc. this would be possible, but since this is not an option it would break our current implementation or we would need to completely refactor the whole table for this feature.

The table always needs to know how many rows there should be displayed, as only the table body is scrollable. The header row, header section and extension section are fixed to the top of the container. Also virtualization wouldn't work otherwise.

Here's an example of what I mean:

_red background = container_

Current behavior:

https://user-images.githubusercontent.com/9749730/202145066-ca128765-0375-4d73-8c96-af6d8ffba8aa.mp4

With overflow:

_container has overflow: auto_

https://user-images.githubusercontent.com/9749730/202145624-bd1c1f46-5a7c-451f-8757-e96e33a802b0.mp4

--> double scrollbar

_container has overflow: hidden;_

https://user-images.githubusercontent.com/9749730/202145933-c0ec6ac0-4335-4ceb-9c99-9e65a5f604d7.mp4

--> row is never completely accessible
