### ISSUE TITLE
Standard CSS-Styling is to small 

### ISSUE THREAD

**Issue by bjwie** [SAP/ui5-webcomponents-react#3859]
Hi SAP-Team,

Your standard Font-Size is 0.875rem, its to small. I think the standard is 16px which is 1rem.
Its cumbersome to override all these values.
Every component looks like its shrinked. The same is with the Icons and lists. 
Is there an option to make the size everywhere "normal"? Or could you try to improve this?
![image](https://user-images.githubusercontent.com/14150169/206913660-c87d328a-f4d1-4841-8ef1-1c5f230b5121.png)
![image](https://user-images.githubusercontent.com/14150169/206913759-45c850e6-4f83-4b6b-87c0-27717aeb0de5.png)

Best regards
Björn

**Comment by Lukas742** [comment]
Hi @bjwie 

we're not involved in creating the SAP (Fiori) design standards, so I can't give you an answer to why this font-size was chosen as default. Maybe because of the custom font-family, maybe because you can show business content in a clearer and cleaner way if the font-size isn't too large, maybe for other reasons.

There is no other way of changing the font-size than to either overwrite the respective property, or to set a new value for the respective CSS Var. (See [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-styling--page))

You can ask the question on the [community platform ](https://answers.sap.com/index.html)of SAP, there you will most probably get the answer.
