### ISSUE TITLE
Table: The 'Select All' checkbox in multi-select mode is checked by default when there is no data

### ISSUE THREAD

**Issue by hhhhzs** [SAP/ui5-webcomponents-react#3864]
**Describe the bug**
The 'Select All' checkbox in multi-select mode is checked by default when there is no data, which doesn't make sense from my point of view. It seems that there is no available method to uncheck this checkbox by default.

**Isolated Example**
<img width="757" alt="image" src="https://user-images.githubusercontent.com/57512939/207067422-bf5942c4-5133-443d-822f-37f8920f2949.png">

**Expected behavior**
The 'Select All' checkbox is unchecked by default or provide a parameter to control its default behavior

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.25.5
Operating System: Mac OS
Browser: Chrome

**Comment by Lukas742** [comment]
This was fixed in [v1.6.0](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.6.0) of `@ui5/webcomponents` (https://github.com/SAP/ui5-webcomponents/issues/5294). To consume the fix you will have to update `@ui5/webcomponents-react` to at least [v0.27.0](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.27.0).
