### ISSUE TITLE
Actionsheet: Keyboard focus is not moving during navigation when JAWS is on

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents-react#3887]
**Describe the bug**
When JAWS is on, Keyboard focus is not moving during navigation. JAWS focus is moving, but keyboard focus is stuck at first item. This issue occurs when Actionsheet role is changed to 'menu' as shown in below example.
```
  <ActionSheet
        horizontalAlign="Center"
        ref={popoverRef}
        **a11yConfig={{
          actionSheetMobileContent: {role: "menu"}
        }}**
        opener="actionSheetOpener"
        placementType="Right"
        verticalAlign="Center"
      >
```

**Isolated Example**
https://codesandbox.io/s/react-playground-forked-zrm65p

**To Reproduce**
1. Go to https://codesandbox.io/s/react-playground-forked-zrm65p
2. Enable JAWS
3. Use keyboard to open actionsheet and navigate using arrow key.

**Expected behavior**
Keyboard and JAWS focus should move together during navigation as it works without a11yConfig attribute.

**Screenshots**
<img width="983" alt="Screen Shot 2022-12-16 at 5 33 10 PM" src="https://user-images.githubusercontent.com/67934622/208217549-4c71dc71-b8d7-4088-ba45-1d91830a31c7.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: All
`@ui5/webcomponents-react` version:  All
Operating System: Windows
Browser: All

**Additional context**
JAWS2022 is used for testing.

**Stakeholder**
Organization: {SuccessFactors}
Business impact: {a11y issue}

**Comment by Lukas742** [comment]
Hi @pankajpandey01 

are you using the reading mode or the application mode (virtual cursor off) in JAWS? 
In reading mode it's not expected that the internal navigation of the web-components works.

**Comment by pankajpandey01** [comment]
Hi @Lukas742 
We are using browse/read mode. We have observed that with this mode enabled, keyboard focus works fine without "a11yConfig" attribute.

**Comment by Lukas742** [comment]
We're setting `role="application"` to the content of the ResponsivePopover. That's why it's working fine without the `a11yConfig`, because Screen Readers then use the application mode automatically. Since this is not how standard ui5 web components are handling this, we're going to remove this in our [next major release](https://github.com/SAP/ui5-webcomponents-react/issues/3857) (since it will be a breaking change). 
So if you want to enforce the behavior, you have to set `role="application"` yourself - either on application level or component level.
