### ISSUE TITLE
Unable to change the input data on click of "show more item" button implemented in the subrow of tree table(analytical table)

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents-react#3905]
**Describe the bug**
I am trying to change the value change the data given to treatable when clicked on show more button
**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Go to 'https://codesandbox.io/s/silly-lamport-fv1bv9?file=/src/App.js'
2. Click on a row item.
3. see a "see more item" button at the end of the list.
4. on clicking the data sent to the tree table should be set to something else.

**UI5 Web Components for React Information**
`@ui5/web components version: "1.9.3",
`@ui5/web components-react` version:"1.7.0"
Operating System: macOS
Browser: chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @roshnijalan97new 

you're setting the table data via a React Ref, which will not update the component. Refs will never update the component, which is [standard React behavior](https://reactjs.org/docs/refs-and-the-dom.html). You will need a state for this.

Not related (or only partially) to the issue, but worth mentioning in my opinion:

Both the `columns` and the `data` prop should be memoized, otherwise it can lead to unintended behavior. (See [docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story))


See [codeSandbox](https://codesandbox.io/s/elastic-frog-pxs81d?file=/src/App.js).

**Comment by roshnijalan97new** [comment]
what is the meaning of memoized?

**Comment by roshnijalan97new** [comment]
It is causing re-renders in my local and not loading the table itself

**Comment by Lukas742** [comment]
> what is the meaning of memoized?
- https://en.wikipedia.org/wiki/Memoization
- https://www.syncfusion.com/blogs/post/what-is-memoization-in-react.aspx

> It is causing re-renders in my local and not loading the table itself
Did you take a look at the codeSandbox? Without rerendering you can't update the component.
