### ISSUE TITLE
AnalyticalTable: The min width for a single column table header is set to a low value.

### ISSUE THREAD

**Issue by AkshitaDhiman77** [SAP/ui5-webcomponents-react#3939]
**Describe the bug**
For a single column table the header width is not satisfying the necessary condition for 'scaleWidthMode.Grow' to get the horizontal scroll enabled.

The column header's width is not getting adjusted with reference to the column element's width. the column header width is set to minimum width in the single column table.

**Expected behavior**
The column width should be referring the column elements width, it should stretch as per the requirement. 

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.0
Operating System: windows 11
Browser: Microsoft edge

**Comment by Lukas742** [comment]
Hi @AkshitaDhiman77 

are you using a custom component as header or just text? Components are not supported by this mode (see [docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story#properties)).

**Comment by AkshitaDhiman77** [comment]
Hi @Lukas742 

I'm using a simple text in the header.

**Comment by Lukas742** [comment]
Does this also happen with the latest version?
If so, could you please add a reproducible example, preferably by leveraging this[ codeSandbox template](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)?

**Comment by AkshitaDhiman77** [comment]
Yes, this is also happening with the latest versions. Sure, I'll reproduce the scenario and send you the example.

**Comment by AkshitaDhiman77** [comment]
Hi @Lukas742 ,
 I've reproduces the scenario "horizontal scrollbar not shown even when the row data is big and exceeding the table width" and attaching the codesandbox link:
[horizontal scrollbar not shown]((https://codesandbox.io/s/cool-field-bwxtl6?file=/src/App.js))

**Comment by Lukas742** [comment]
This has more to do with the max-width than the min-width, since the min-width is never used here, unless the column is reduced, right?

To prevent bad UX with huge header texts, per default a max-width is set here. Normally you would be able to overwrite it by setting the respective column property, but currently this is not possible because of a bug. This [PR](https://github.com/SAP/ui5-webcomponents-react/pull/3941) will fix it though and also adds a note to the prop description.

**Comment by AkshitaDhiman77** [comment]
Hi @Lukas742,
Please confirm me once the required changes are released so that I can check the functionality required. 
Thanks

**Comment by Lukas742** [comment]
Hi @AkshitaDhiman77 

as you can see in our [release log](https://github.com/SAP/ui5-webcomponents-react/releases) and the mentioned PR, the changes have already been released. I kept the issue open, since I asked you a question (hence the "author action" label). By the way, we're still waiting for your input in https://github.com/SAP/ui5-webcomponents-react/issues/3965 as well.

**Comment by AkshitaDhiman77** [comment]
Hi @Lukas742 ,
I've checked the release log and found the mentioned fix, but I'm unable to apply the particular suggestions you gave to add the maxWidth.

It would be really helpful if you could please provide the said implementation in the code sandbox where I reproduced the issue.
https://codesandbox.io/s/cool-field-bwxtl6?file=/src/App.js

**Comment by Lukas742** [comment]
1. update the codeSandbox to the respective version the fix is available in (so at least to[ v1.7.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.7.2))
2. Set the `maxWidth` [column property](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story#column-properties) of the respective column to a any number you like

**Comment by AkshitaDhiman77** [comment]
Hi @Lukas742,

I have tried the suggested approach, but I'm unable to achieve the required functionality.

**Comment by Lukas742** [comment]
You can't use React v17 with React v18 syntax (`createRoot`). I've updated your codeSandbox to React v18 and then it's working for me. Also, even though js is casting strings, which are only containing numbers (e.g. `"5000"`) to numbers, it's considered bad practice. Please make sure that you always use the correct type.

https://codesandbox.io/s/hardcore-cache-s5ubxu?file=/src/App.js
