### ISSUE TITLE
Intellisense in VSCode with Typescript project should suggest only important properties

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents-react#3984]
**Is your feature request related to a problem? Please describe.**
Yes, when I am using VSCode with a typescript project, and then I type something like this: `<FlexBox` the intellisense will try to suggest me some attributes; however, it lists out so many options, such as dozens of `aria-XX` ones right at the top. In my case I'm trying to remember the attribute `direction` but I can't remember the first letter of this property. So I need to scroll through a large list of other properties that I don't care about.

**Describe the solution you'd like**
Can we improve the intellisense at all to provide the important suggestions at the top so that if you don't know what property to set you can see the list of available ones you can see the important ones right away. The other ones are still good to have in case there was a particular aria-attribute that we need.

**Describe alternatives you've considered**
Open the storybook on my other screen and read the documents to find the attribute name that I'm looking for.

**Additional context**
Probably this is less important for the more intuitive property names - but I find "direction" particularly hard to remember.

**Comment by Lukas742** [comment]
I would also very much welcome this feature, unfortunately after some research I now think that this will not be feasible. In VSCode it's not possible to configure autocompletion to prioritize types by inheritance, for example.

Also, our TypeScript types for components are correct (since they do accept `HTMLAttributes`), so it would be wrong to change them for this feature. 

Since improved auto-complete sorting capabilities are not on the roadmap of VSCode (see [here](https://github.com/microsoft/vscode/issues/80444)), I'm closing the issue as it's unlikely to be resolvable in the foreseeable future.

However, if you do find a way to make sorting/filtering possible, we would be very happy if you could let us know.
