### ISSUE TITLE
In Analytical table autoselect index value with different name.

### ISSUE THREAD

**Issue by Rahishsaifi** [SAP/ui5-webcomponents-react#3999]
**Describe the bug**
In Analytical table autoselect index value with different name.

**To Reproduce**
1. Search for any record & select it (Ex. Argamassa refratária)
2. Search for different record (Ex. Odorante para Gás)
3. Note that checkbox is auto selected

**Expected behavior**
Checkbox should be checked based on the user selection

**Screenshots**

**UI5 Web Components for React Information**
@ui5/webcomponents version:
@ui5/webcomponents-react version:
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
Hi @Rahishsaifi 

please add a reproducible example, preferably by using this [codeSandbox ](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34) template.

**Comment by roshnijalan97new** [comment]
Hi @Lukas742, Please refer- https://codesandbox.io/s/sleepy-wood-ovdjhu?file=/src/App.tsx 
for a reproducible example,
<img width="677" alt="Screenshot 2023-02-02 at 4 43 28 PM" src="https://user-images.githubusercontent.com/120740457/216309679-181a3feb-b029-474e-a826-473436cdc74f.png">
Initially, I selected the row at index 1,
Now if I Search "Rose" and click on Go,
<img width="668" alt="Screenshot 2023-02-02 at 4 44 27 PM" src="https://user-images.githubusercontent.com/120740457/216309879-712cf742-ff80-4178-a357-10c7fdd828d8.png">
We can see in the above image, There is a selection being made at index 1 irrespective of the data.

**Comment by roshnijalan97new** [comment]
The selection at the index should be according to the data.

**Comment by Lukas742** [comment]
Hi @roshnijalan97new 

since you're using `selectedRowIds` it will be applied every time you update the data, so you have to make sure to set it to the respective value when updating the `data` array.

https://codesandbox.io/s/admiring-bell-bzcbux?file=/src/App.tsx

**Comment by Rahishsaifi** [comment]
HI @Lukas742 , I have tried above solution, but this is also not working.

**Comment by Lukas742** [comment]
"This is no working" doesn't really help in finding the issue. Could you please either add another reproducible example, or describe exactly what is not working when programmatically changing `selectedRowIds`?

**Comment by roshnijalan97new** [comment]
Hi @Lukas742, If Suppose I unselect the 1 index element manually by clicking on the box, 
![image](https://user-images.githubusercontent.com/120740457/217759589-d41c1e44-6d75-42bf-9b13-8ab7bc5bf4cb.png)
Then I search for "Rose" and click on Go and do nothing.
![image](https://user-images.githubusercontent.com/120740457/217759821-b4b1c369-90f3-47d4-8212-16b5025ffac6.png)
then remove the search and place "" and click on Go. Then I can see the element at index 1 is still selected.
https://codesandbox.io/s/admiring-bell-bzcbux?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/120740457/217760144-07ce9192-7835-4d54-8d06-25826b924d80.png)

**Comment by Lukas742** [comment]
The codeSandbox was just an example for showing how to programmatically change the `selectedRowIds`, not a final implementation, you have to adjust it to your use case.

The AnalyticalTable behaves in the correct way in the described case:
1. The component is mounted, so `selectedRowIds` is an empty object. 
2.  In the `getData` function `setSelectedRowIds` is only called when no `value` is set and since `value` is an empty string in this case, `selectedRowIds` is set to `{1: true}`.
3. You deselect a row, `selectedRowIds` won't change, as it's not updated on selection change, so only the internal state is taking control of the selected state of this row.
4. You search for something resulting in calling `handleOnChange`, making `setSelectedRowIds` set the state to an empty object. 
5. You click "Go" and `onGo` is called with a `searchValue` and therefore the data is updated, resetting the internal disabled state, but `setSelectedRowIds` is not called again as it's not an empty `value`.
6. You reset the value and press "Go" and as `value` is an empty string, `selectedRowIds` is set to `{1: true}`.

[Here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story#how-to-stop-the-table-state-from-automatically-resetting-when-the-data-changes) you can find out on how to prevent the __internal__ table state from resetting.

**Comment by roshnijalan97new** [comment]
Hi @Lukas742 Lukas742, I understand why it is caused. I just want to know if there is a way we can memorize the changes and solve the above problem.

**Comment by Lukas742** [comment]
I'm not sure what you mean with memorize the changes, if you want to keep the previous value of a state, you can do that with a React Ref for example (see [here](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state)).

I'm still not 100% sure what you're trying to accomplish, but I can't think of a use case that couldn't be solved by a combination of programmatically adjusting the `selectedRowIds` to the value you need and saving the state you want to use later in a Ref. 

If you, for example, want to fully control the selected state, you can update your `selectedRowIds` every time `onRowSelect` is called.

**Comment by Rahishsaifi** [comment]
Hi @Lukas742 ,

If the data is initially loaded in table in **treeview** so index of row is like this 

**0.0.0
  0.0.1
     0.0.2**

Now if i want to select third row the index is
**0.0.2**
which is fine

if i am getting in normal mode , not in tree view

so the index looks like this

**0
1
2
3
4**

Now the issue is if i select **normal mode** row, means **0** index, and switch to **treeview** without page load, then it automatically select 0.0.0

this is the issue we are facing.

**Comment by Lukas742** [comment]
Hi @Rahishsaifi 

the number you describe there are the ids of the rows and not the index. The index describes the position of the row inside a list, so for example when the first row is collapsed, index 1 is the second row with an id of `1`, but when the first row is expanded, then the second row is the first subrow of the first row with an id of `0.0`. Below you can find an example for this.
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/9749730/220279996-5eb4f9c1-d9b4-4e71-904d-e00abb26065c.png">

As your explanation is lacking a lot of necessary information (e.g. which props do you use, how do you set the `selectedRowIds`, etc.), I ask you again to reproduce the issue in a codeSandbox, or only if that doesn't work, to give us a detailed (setp-by-setp) explanation of the problem. Otherwise, unfortunately, we cannot help you.
