### ISSUE TITLE
Storybook: "Show Code" not showing original code

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#4000]
When clicking on "Show Code" on the code example of the [Menu component](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-menu--default-story), Storybook gives us the following code:
```
<>
  <Button
    ref={{
      current: '[Circular]'
    }}
    onClick={function noRefCheck(){}}
  >
    Show Menu
  </Button>
  <Menu
    ref={{
      current: '[Circular]'
    }}
    onItemClick={function noRefCheck(){}}
  >
    <MenuItem
      icon="add-document"
      text="New File"
    />
    <MenuItem
      disabled
      icon="add-folder"
      text="New Folder"
    />
    <MenuItem
      icon="open-folder"
      startsSection
      text="Open"
    />
    <MenuItem text="Close" />
    <MenuItem
      icon="action-settings"
      startsSection
      text="Preferences"
    />
    <MenuItem
      icon="journey-arrive"
      text="Exit"
    />
  </Menu>
</>
```
This is, however, not the real code of the example. The original code is the following, as can be found in [Menu.stories.mdx](https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/webComponents/Menu/Menu.stories.mdx):
```
<Canvas>
  <Story name="Default">
    {(args) => {
      const ref = useRef(null);
      const btnRef = useRef(null);
      useEffect(() => {
        if (isChromatic) {
          ref.current.showAt(btnRef.current);
        }
      }, []);
      return (
        <>
          <Button
            ref={btnRef}
            onClick={(e) => {
              ref.current.showAt(e.target);
            }}
          >
            Show Menu
          </Button>
          <Menu {...args} ref={ref}>
            <MenuItem text="New File" icon="add-document"></MenuItem>
            <MenuItem text="New Folder" icon="add-folder" disabled></MenuItem>
            <MenuItem text="Open" icon="open-folder" startsSection></MenuItem>
            <MenuItem text="Close"></MenuItem>
            <MenuItem text="Preferences" icon="action-settings" startsSection></MenuItem>
            <MenuItem text="Exit" icon="journey-arrive"></MenuItem>
          </Menu>
        </>
      );
    }}
  </Story>
</Canvas>
```
This is not the first but only the most recent time that I had to dig in the source files to find a working code example. I found a bug report about this and apparently, [Storybook transforming the original code can be turned off](https://github.com/storybookjs/storybook/issues/12843#issuecomment-720157480).

Maybe this could be interesting to you.
Thanks a lot in advance!

**Comment by Lukas742** [comment]
Hi @ej612 

the problem with `type: 'code'` is that it doesn't update the props set by the args table of the storybook, also we sometimes include code that is only for our story generation. That's why we decided against using the raw code as example, as there could be overhead that is even more confusing (especially for complex components).
Normally we only include the component of the story, but for modals in general this would lead to bad UX/DX as per default all modals are not displayed and even if we would show them initially, they would have to be opened manually by setting the `open` prop and for some components it wouldn't be possible at all, as they don't offer a `open` prop yet.

For the `Menu` for example, the raw code would look like this.
```

args => {
  const ref = useRef(null);
  const btnRef = useRef(null);
  useEffect(() => {
    if (isChromatic) {
      ref.current.showAt(btnRef.current);
    }
  }, []);
  return <>
          <Button ref={btnRef} onClick={e => {
      ref.current.showAt(e.target);
    }}>
            Show Menu
          </Button>
          <Menu {...args} ref={ref}>
            <MenuItem text="New File" icon="add-document"></MenuItem>
            <MenuItem text="New Folder" icon="add-folder" disabled></MenuItem>
            <MenuItem text="Open" icon="open-folder" startsSection></MenuItem>
            <MenuItem text="Close"></MenuItem>
            <MenuItem text="Preferences" icon="action-settings" startsSection></MenuItem>
            <MenuItem text="Exit" icon="journey-arrive"></MenuItem>
          </Menu>
        </>;
}
```

You can see that only the `ref` is exposed here and the rest is coming from the `...args` spread and the `useEffect` with the `isChromatic` check is something we only use for our `Chromatic` snapshots.

In my opinion, only the rendered component should be displayed, as any logic set by developers (e.g. handlers, functions, refs), doesn't belong in the story. 

The problem with events showing `function noRefCheck(){}` will be fixed with storybook, then it will only show an empty arrow function (`()=>{}`). I'm not aware of any fix for refs that show `current: '[Circular]'` though, so I guess we have to live with it for the time being.

**Comment by Lukas742** [comment]
We actually did disable the generated code example for some stories (e.g. `AnalyticalTable`), and created a static example. This was mainly done to reduce overhead, which was polluting the output (data, irrelevant props, etc.). In general, however, we would prefer the sample code to adapt to changes users are making. 

>I would argue against this, as to make the Menu work, you need to pass a ref to it, which is something that is not obvious for people who are new to react. 

You are right, all modal-like components should document how to open them. We just merged a commit that will outline how to achieve this. You can find our "next" documentation [here](https://sap.github.io/ui5-webcomponents-react/main/?path=/docs/modals-popovers-menu--default-story#opening-menus). Do you think that is sufficient?
