### ISSUE TITLE
unclear documentation and TypeScript types for `valueStateMessage`

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents-react#4012]
**Describe the bug**
valueStateMessage must be a `ReactNode | ReactNode[]` - passing a string will throw a very obscure error message and does not fail any typescript validation. I wasted 2 hours of my life trying to figure out this error.

**Isolated Example**
https://codesandbox.io/s/pensive-almeida-c5n2oz?file=/src/App.js

**To Reproduce**
1. See the error in isolated example

**Expected behavior**
Either the component should allow string as the valueStateMessage, or it should not compile.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
Hi @codefactor 

with the linked PR we will add a note to all props that are internally rendered as `slot`. We'll also change the type of slots to be more restrictive as `string`, `number` and `true` doesn't make sense to be passed there. The same goes for `ReactPortal`, but since we didn't find a way to exclude it with TypeScript, we decided it's best to filter out the portal and display a warning in the console. If you happen to find a way how this can be achieved with TypeScript, please let us know.
