### ISSUE TITLE
ToggleButton: Losing clicked state in toolbar overflow container

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#4041]
**Describe the bug**
We have a Toolbar containing a ToggleButton. The Toolbar is in a resizable Dialog, so we can change its width. If we click on the ToggleButton so it turns blue, and then resize the dialog until the ToggleButton disappears in the Toolbar's overflow container, the ToggleButton will lose its clicked state.

I made a [sandbox](https://codesandbox.io/s/awesome-sanne-oe2wf8?file=/src/App.js).

Thank you very much in advance!

**Comment by Lukas742** [comment]
Hi @ej612 

you have to fully control the component to bring the state to the newly created button inside the popover. You can do that by adding a state (e.g. `pressed`) and update it when invoking the `onClick` event. 
It's generally recommended to fully control components in React, as otherwise you could face side-effects in the UI which aren't connected to any logic and could therefore confuse the user.


https://codesandbox.io/s/infallible-chaum-4wbuqs?file=/src/App.js

**Comment by Lukas742** [comment]
Hi @ej612
The linked PR will add a description to the `Toolbar` component stating, that the overflow popover is only mounted when opened and therefore remounting all children when they're moved into it.
