### ISSUE TITLE
MultiComboBox: Component truncated when used with a splitter

### ISSUE THREAD

**Issue by davidmobbssap** [SAP/ui5-webcomponents-react#4071]
**Describe the bug**
When reducing the size of the component using a splitter (SplitterLayout), the side of the MultiComboBox gets truncated

**Isolated Example**
Use https://codesandbox.io/s/fast-surf-pf4eiv

**To Reproduce**
1. Open the attached code sandbox
2. The MultiComboBox is truncated on the right side
3. Using the splitter, you can have a normal MultiCombo if the right side is a bit bigger, or get it truncated again if you reduce the right side

**Expected behavior**
The MultiComboBox should always draw correctly

**Screenshots**
![Field Columns](https://user-images.githubusercontent.com/101794684/216028945-51a575e5-4e4e-499e-8258-3d469db76944.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.3
`@ui5/webcomponents-react` version: 1.7.2
Operating System: MacOS 13.2
Browser: Edge 109.0.1518.70

**Additional context**

**Comment by Lukas742** [comment]
Hi @davidmobbssap 

the `MultiComboBox` has a `minWidth` and `width` attached, in your codeSandbox you've only overwritten the `width` property, but not the `minWidth`. --> [codeSandbox](https://codesandbox.io/s/bold-shape-ll1bog?file=/src/App.js)

**Comment by davidmobbssap** [comment]
Thanks @Lukas742  I have implemented the change in my code. It does work better, however in my browser when the sandbox is loaded, and also sometimes when I move the splitter around (not in all cases), the truncation is back. I am attaching a screenshot.

Any further advice ?

Thanks !

![screenshot](https://user-images.githubusercontent.com/101794684/216262752-ecff6a97-5b27-4e33-8d51-79f68fa91bfe.png)

**Comment by Lukas742** [comment]
Unfortunately, I couldn't reproduce this, but sometimes iframes can cause strange behavior, especially when initially loaded. Is this issue reproducible in you local app or when using the fullscreen mode of codeSandbox (no iframe there)?

**Comment by davidmobbssap** [comment]
Thanks Lukas. The issue occurs intermittently in my app, and disappears when in fullscreen mode, so this confirms your analysis.
So is this a browser bug ? Do you know if there is an issue with the Chromium team about these erratic iframe behaviors ?
Thanks !

**Comment by Lukas742** [comment]
I don't think that it's a browser bug, but I'm not sure either. it could have many root causes (implementation inside codeSandbox, general shortcoming of iframes (which are many), etc.)
Since iframes are generally considered a bad approach for customer facing websites (one of many examples for this is explained [here](https://support.trekksoft.com/5-reasons-to-better-not-use-iframe-integration-in-your-website)), we don't plan to investigate this behavior further. 
Imo, iframes are great for rendering a window for component previews like codeSandbox, or Storybook does it, but not for a "standard" web application.
