### ISSUE TITLE
VariantManagement: Label of the dropdown of variant management is not getting updated when name is updated

### ISSUE THREAD

**Issue by nidhi0104** [SAP/ui5-webcomponents-react#4072]
The label of the dropdown is not getting updated when user is updating the name of the variant view from the 'Manage Views' Tab, it is showing the older variant name.

1. Go to Variant Management Dropdown
2. Click on 'Manage' Button
3. Change the name of the variant whose 'Default' property is set as true
4. Click on save

Current Behaviour: The name of the label is not getting updated

**Expected behavior**
The name of the label of dropdown should be updated after the save.

**Screenshots**
![image](https://user-images.githubusercontent.com/105447668/216031218-3025f52a-6121-45e9-ac8a-d531b39f3146.png)
![image](https://user-images.githubusercontent.com/105447668/216031322-dad00325-e62c-4559-bad1-119a0df5c5a6.png)
![image](https://user-images.githubusercontent.com/105447668/216031385-003b0dd7-86ad-47d3-a837-1482f69675f9.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:"1.6.0"
`@ui5/webcomponents-react` version:"0.27.5
Operating System:Mac OS
Browser:Chrome

**Comment by Lukas742** [comment]
Hi @nidhi0104 

I could not reproduce this issue with the version you provided or the latest version.

- video: https://user-images.githubusercontent.com/9749730/216040418-d692c5ee-3d24-40a6-89b2-365d9e8d965e.mp4
- [codeSandbox](https://codesandbox.io/s/blue-bush-7c3gj3)

Could you please create a reproducible example? You can leverage the codeSandbox I posted above for this.

**Comment by I506645** [comment]
Hi @Lukas742 

We're not able to reproduce this in codeSandbox for some reason but one thing we've observed is that its not reproducible even in our app for the very first time but it's reproducible only 2nd time onwards. We can confirm that the variantListItem has the updated data when the save is completed, and the component is being re-rendered. The names of the variant list items are updated (as shown in screenshot) with the updated data when the component is being rendered but not the label and there's no property with which we can update the label except for the "selected" property which we believe only highlights the selected variant item in the list and has nothing to do with the label.

We can also have a call to discuss more on this. Let me know.

Best Regards,
Raghav

**Comment by Lukas742** [comment]
Hi @I506645 

you probably need to fully control the React state and persist it. Here you can find a basic example on how this can be achieved: [codeSandbox](https://codesandbox.io/s/jovial-clarke-kdkglt?file=/src/App.js)

In the codeSandbox, when you press the "rerender" button, the component is unmounted and remounted again, resulting in all internal state to be lost. With `onSaveManageViews` the state is persisted between renders making the component fully controlled for this specific case.

Please note, that the `variantItem` property of the `onSaveManageViews` callback is currently always returning `null`, which is not intended. It shouldn't affect your use-case though and a [fix](https://github.com/SAP/ui5-webcomponents-react/pull/4149) is on its way.

**Comment by I506645** [comment]
Hi @Lukas742 

As discussed over the call, I tried to change the web-components version to latest but that didn't help as there were lot of changes to adapt in the app since our app is currently running on 0.27 version and that would take time. However, I was able to reproduce the issue in codeSandbox with a simple setTimeout instead of an API call which is similar to the approach (in terms of variantListData during each rendering of the VariantManagement component) used in our app. I've sent you a video over mail showing the steps to reproduce the issue in this [codeSandbox.](https://codesandbox.io/s/recursing-nightingale-wy36x0?file=/src/App.js)

Could you please have a look at it again?

Best Regards,
Raghav

**Comment by Lukas742** [comment]
Hi @I506645 

I just noticed, that I missed an important factor in my example which is also solving the issue in your updated codeSandbox. 
When React is rendering a list, the `key` prop has to be set as otherwise react doesn't know when to update the component in some cases like in this case. You can find more information about this [here](https://beta.reactjs.org/learn/rendering-lists#keeping-list-items-in-order-with-key).

[Here](https://codesandbox.io/s/blissful-fog-wjmhzu?file=/src/App.js) you can find the updated codeSandbox which adds a `key` to the `VariantItem`. Could you please check if this solves the issue in your implementation as well?

**Comment by I506645** [comment]
Hi @Lukas742 
Thanks for the solution. Adding a Key to the VariantItem worked. 

Best Regards,
Raghav

**Comment by Lukas742** [comment]
Glad to hear :)
