### ISSUE TITLE
Wizard: Could't add Icon to WizardStep

### ISSUE THREAD

**Issue by Matheus-Mont** [SAP/ui5-webcomponents-react#4082]
**Describe the bug**
I've been trying to use Wizard, but the Icons don't appear, even with the correct use of the icon prop.

**Isolated Example**
Here is the example: [codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).

**Expected behavior**
It was expected that, once added a string with the name of the icon, it would appear in the component.

**Screenshots**
![image](https://user-images.githubusercontent.com/87338913/216422494-9b5be99f-da2b-49c4-be95-ffc0cb2899ea.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.10.3
`@ui5/webcomponents-react` version: 1.8.1
Operating System: Windows 11
Browser: Google Chrome and Firefox

**Comment by Lukas742** [comment]
Hi @Matheus-Mont 

your codeSandbox doesn't include a Wizard, it's just the plain template. Did you forget to save or fork it?

For the icon, did you import the respective icon, either by importing all icons or just the used one? If not you should see a warning about this in the console.

**Comment by Matheus-Mont** [comment]
Hi there!
I forgot to fork it: [CodeSandBox](https://codesandbox.io/s/quizzical-framework-b45r0e) .
In the CodeSandBox example it works perfectly. Though, in my project it doesn't. I use next.js, if it might be a relevant information.

![image](https://user-images.githubusercontent.com/87338913/216608296-afabc08a-3754-4cfc-a201-d2e025ccbb80.png)

My main objective is actually to use numbers in the component, instead of UI5 icons.

Any suggestions about the problem?

**Comment by Lukas742** [comment]
Would it be possible for you to create a reproducible example for this, or is there a repo I can checkout to see the behavior myself?

Currently only icons are supported there, so it won't be possible adding numbers, for this the web component would needs to be extended. Since this component is developed by the UI5 Web Components' team, you can create a [feature request](https://github.com/SAP/ui5-webcomponents/issues/new/choose) about it in their repo. Then they can check if this is something they'd consider adding.
