### ISSUE TITLE
Icon: new property 'design' of ui5-icon released @1.9.2 does not have corresponding prop 'design'  in version @~1.7.0

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents-react#4113]
**Describe the bug**
The new property 'design' of ui5-icon released @1.9.2 does not have corresponding prop 'design'  in version @~1.7.0

Could you please have a prop 'design' in the component Icon and downport to 1.7.x?

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.3
`@ui5/webcomponents-react` version: 1.7.3

**Comment by Lukas742** [comment]
Hi @BennyHuang 

we only consider downporting critical/app-breaking bugs and no features, because this would increase maintenance tremendously and also mess up semantic versioning. 

Also the `design` prop is only available since [1.10.0](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.10.0) and not since 1.9.3.
