### ISSUE TITLE
[SF][1.11.3][DynamicPage]: ResponsivePopover and Dialog display wrong position in DynamicPage

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#4381]
### Describe the bug

After upgrade to @ui5/webcomponents-react@1.11.3,  ResponsivePopover and Dialog in DynamicPage display with wrong position and z-index.

### Reproduction steps

1. this [codeSandbox](https://codesandbox.io/p/sandbox/distracted-haibt-25rchx?file=%2Fsrc%2FApp.tsx) example to reproduce by click the "Open Popover inside Dynamic Page" button.

![image](https://user-images.githubusercontent.com/78520316/226567225-bbce5eae-cb2a-4d20-834e-d625ab11e2fd.png)

...

### Expected Behaviour

ResponsivePopover and Dialog should display correctly in DynamicPage.

### UI5 Web Components for React Version

1.11.3

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by sfsf-xweb-sh** [comment]
Hi team,
I think this issue may be caused by DynamicPage setting a css property container so position: fixed elements relative the DynamicPage element not viewport. Once I cancel the container property of DynamicPage. ResponsivePopover and Dialog display correctly.
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/78520316/226529193-5dee5005-1a16-49a4-8fec-bcf9c50ea53e.png">

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

I don't have access to the site you've posted, and even if I had it's always easier to have a minimal example that shows the issue instead of a complete app where many things could be the root cause. So, please use this [codeSandbox](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx) template to reproduce this behavior. Additionally to that and since these look like custom implemented Dialogs/Popovers, maybe our [portal section](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-working-with-portals--docs) in our documentation might help here.

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742 

please use this [codeSandbox](https://codesandbox.io/p/sandbox/distracted-haibt-25rchx?file=%2Fsrc%2FApp.tsx) example to reproduce by click the "Open Popover inside Dynamic Page" button.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/78520316/226549097-994f31a1-8f81-4705-8b43-abb5c7a22e99.png">

**Comment by Lukas742** [comment]
Shouldn't make a difference: https://codesandbox.io/p/sandbox/tender-sound-92gftx?file=%2Fsrc%2FApp.tsx

**Comment by sfsf-xweb-sh** [comment]
@Lukas742 In our use case, our project includes some ui which is widget which is not an react project. Once include the widget in DynamicPage, popover inside the widget will display wrong position.

**Comment by alex-zhang** [comment]
@Lukas742  we also have some web modules which are on top of ui5-webcomponent directly (not react), i don't think you mentioned is a good solution.

**Comment by Lukas742** [comment]
Using portals is the recommended way, of opening/mounting popups or modals with React, but there are other options of course. Unfortunately we can't remove the container query, as it is responsible for the responsive padding which we now can implement without js and therefore with performance improvements of the component. 

I understand that it's unfortunate that this container query has caused this side-effect, but I see no way around it and we outlined it in our documentation, that this can happen when nested inside components. Can't you encapsulate the popover inside the widget in a portal as well or just mount it with plain js to e.g. the `body` or a dedicated modal/popover container? It's always kind of risky when mounting popovers deep down in your application, because a single line of CSS change (which isn't bound to semantic versioning), could cause unwanted positioning, alignment, etc. 

Container queries are now supported by all major browsers, so I would expect it to be used more and more, because it's so much more performant than using `ResizeObserver`s. Are you only referring to the popup issue or other issues when you say "broken the UI"?

Also including @ilhan007: maybe the calculation of the position of modals can be improved when being used in container queries? I can also open an issue for it if it's considered.
