### ISSUE TITLE
[Analytical Table(TreeTable)]: Expanded row should remain expanded after the search

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents-react#4407]
### Describe the bug

Expanded row should remain expanded after the search

### Reproduction steps

Please refer: https://codesandbox.io/s/silly-dream-cxoer2
1. Expand row at index 1, i.e, "Rosaline Francisco" 
<img width="683" alt="Screenshot 2023-03-24 at 11 52 25 AM" src="https://user-images.githubusercontent.com/120740457/227441676-903a20ac-4022-49b7-baba-4ac067bc0a5a.png">

2. Search "Rosaline Francisco" in the search box and click on "go".

Currently, after searching, the Row is collapsed.
![image](https://user-images.githubusercontent.com/120740457/227441809-21519440-d79b-4bfe-9c7e-69b7247641f9.png)

### Expected Behaviour

Expected: The row should remain expanded.
![image](https://user-images.githubusercontent.com/120740457/227442115-17f70edb-0bbb-4182-b893-f195b19f955a.png)

### UI5 Web Components for React Version

1.7.3

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Operating System

Mac Os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @roshnijalan97new 

since you're changing the data array when filtering, it's not possible to keep the expanded state of the row, as the table has no indicator which row should be expanded. You can solve this in different ways, depending on your use-case. 
- Using the `manualExpandedKey` `reactTableOption`. With the help of it you can expand the row via a property in your `data` array. ([react-table v7 docs](https://react-table-v7.tanstack.com/docs/api/useExpanded))
- Leveraging the `toggleRowExpanded` tableInstance method to programmatically collapse/expand rows. ([react-table v7 docs](https://react-table-v7.tanstack.com/docs/api/useExpanded))
- Chaning the internal `expanded` table state, e.g. by hooking into it (with a custom plugin hook, or by creating a custom stateReducer) on every data change.
