### ISSUE TITLE
[SAP][Analytical Table]: Deselecting all the child nodes does not deselect the parent node.

### ISSUE THREAD

**Issue by rdharsan30** [SAP/ui5-webcomponents-react#4414]
### Describe the bug

Deselecting all the child nodes does not deselect the parent node.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--plugin-indeterminate-row-selection

### Reproduction steps

1. Select a Parent node with multiple child nodes.
2. Deselect all the child nodes of the parent selected above,
3. Ideally parent node should get deselected (but parent is selected)
...

### Expected Behaviour

Parent node should also get deselected when all its child nodes are deselected.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/129058179/227919833-97ef70d1-c2d5-4134-8d29-8f3ccb8631a1.png)

### UI5 Web Components for React Version

1.10.3

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rdharsan30 

as outlined in our [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable-plugin-useindeterminaterowselection--docs), the "indeterminate" state has a higher priority then the "selected" state. Since you're actively selecting the parent-row, it's still selected even though no child rows are selected. To prevent this, you can deselect the row yourself when necessary.
