### ISSUE TITLE
[DynamicPage]: Page not responsive at 320 CSS px viewport

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents-react#4488]
### Describe the bug

The following do not show up properly when used together in 320px viewport:
1. `DynamicPageTitleHeader` and `DynamicPageTitleActions` when used together:
<img width="1680" alt="Screenshot 2023-04-12 at 8 45 06 PM" src="https://user-images.githubusercontent.com/32254036/231644098-8193df09-8993-4a7e-8b8d-d5d2ab0df657.png">

2. `header` of `Panel` does not show up properly when used in 320px viewport.
<img width="1680" alt="Screenshot 2023-04-12 at 8 47 45 PM" src="https://user-images.githubusercontent.com/32254036/231644416-4d44ecc2-7b3f-4b2f-a136-2d1b1521a5c8.png">

### Reproduction steps

For `DynamicPageTitleHeader` and `DynamicPageTitleActions` when used together:
1. Find the credentials related to this issue in https://sap-successfactors.slack.com/archives/CTHEMAZ8C and log in to qacand. Search for "Script-based integration settings" in global search. Verify this page in 320px viewport                                                                                                            by resizing the viewport to 320 px. Change the page viewport to responsive width 320 x 700 height https://wiki.wdf.sap.corp/wiki/display/Acc/ACC-282+Details#ACC282Details-TestPreparationMethods
2. Notice that "Script-Based Integration Settings" heading does not show up within the 320px viewport and the action button does not show up as well as shown in the screenshot above

For `header` of `Panel` does not show up properly when used in 320px viewport:
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-panel--docs
2. Resize the viewport to 320 px. Change the page viewport to responsive width 320 x 700 height https://wiki.wdf.sap.corp/wiki/display/Acc/ACC-282+Details#ACC282Details-TestPreparationMethods
3. Replace "Countries" in "More Examples with Custom Header" with "WalkMe Integration" and notice that it does not show up properly and overlaps with the action button as shown in the screenshot above

### Expected Behaviour

For 1 above, "Script-Based Integration Settings" heading and the action button should show up within the 320px viewport
For 2 above, the panel heading should show up properly without overlapping with the action button

### UI5 Web Components for React Version

1.5.1

### UI5 Web Components Version

1.9.1

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rama1990br 

the linked PR will fix the first issue.

The second issue has nothing to do with the DynamicPage and additionally I wasn't able to reproduce it. In general, please don't create a single issue for different components if the root cause is not the same. So please create another issue covering this topic and add a reproducible example leveraging this [codeSandbox template](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx). Also, if you only edited the HTML inside the browser's dev tools, then it's not considered a bug, because components don't necessarily react to DOM changes outside their lifecycle.
