### ISSUE TITLE
[SF][Select Dialog]: Select dialog cannot be opened properly in dynamic page

### ISSUE THREAD

**Issue by yuyuCream** [SAP/ui5-webcomponents-react#4522]
### Bug Description

Select dialog cannot be opened and rendered properly in dynamic page
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/32004690/233606560-e02c8ef6-42f5-48af-910d-f3309bc5529c.png">

### Affected Component

Select Dialog

### Expected Behaviour

Select dialog can be opened properly in dynamic page

### Isolated Example
https://codesandbox.io/s/billowing-sound-9c1dzm?file=/src/App.js

### Priority

High

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Operating System

mac

### Additional Context

I am from SAP Successfactors. And issues are for b2311 released project.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @yuyuCream 

mounting pop-ups inside other components can lead to unintentional side-effects (alignment, positioning, z-index, etc.) that's why we recommend mounting them outside. (See [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-working-with-portals--docs))

--> [codeSandbox](https://codesandbox.io/s/little-fog-igfpbk?file=/src/App.js)
