### ISSUE TITLE
Build: Caught ReferenceError: require is not defined  

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4548]
### Describe the bug

It seems, you are using require in your sourcecode, which prevents me from running your ui-libaray in production.
See the text below the error in the screenshot: ui5-static-area

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44802503/234873785-76210568-840a-4544-97ac-58f3dc7b3e55.png)

![image](https://user-images.githubusercontent.com/44802503/234873639-05e6caf7-394d-4f11-8e21-341c1852d1d2.png)

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

1.12.1

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

this issue seems to be the same as raised [here](https://github.com/SAP/ui5-webcomponents/issues/6916). Could you please check if updating `@ui5/webcomponents-react` to v1.13.1, `@ui5/webcomponents` to v1.12.2 and maybe also adjusting the `browserslist` field as explained [here](https://github.com/SAP/ui5-webcomponents/issues/6916#issuecomment-1506854058) will solve the issue for you as well?

**Comment by Lukas742** [comment]
Glad to hear :) 

With [v1.13.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.13.1) we updated the `@ui5/webcomponents` deps to fetch v1.12.2 and newer patches. Usually it works, but sometimes for some reason it doesn't :D 

```
    "@ui5/webcomponents": "~1.12.2",
    "@ui5/webcomponents-base": "~1.12.2",
    "@ui5/webcomponents-fiori": "~1.12.2",
    "@ui5/webcomponents-icons": "~1.12.2",
```
