### ISSUE TITLE
[Table]: TableColumn will mask bar component when set stickyColumnHeader property 

### ISSUE THREAD

**Issue by mengqiuleo** [SAP/ui5-webcomponents-react#4586]
### Describe the bug

When bar component design is FloatingFooter，stickyColumnHeader property makes the z-index of tableColumn too high，so TableColumn will mask bar component.

### Isolated Example

https://codesandbox.io/s/hopeful-borg-v5t8ep?file=/src/App.js

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![11](https://user-images.githubusercontent.com/85825776/236738358-77f92f9f-521c-448b-af3f-4d2d4df52532.jpg)
![12](https://user-images.githubusercontent.com/85825776/236738380-038115ce-d4e7-4942-825e-5b10845d60d2.jpg)

### UI5 Web Components for React Version

1.13.1

### UI5 Web Components Version

1.12.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @mengqiuleo 

Please try to specify all the components you are using in the issue description so that we can better assess which components might be the cause of this issue.

The `Table` component sets its header to `z-index: 99`, so the z-index of the footer component's container used in the `DynamicPage` must be higher than this. I've created an example of how you can achieve this with simple CSS, which you can find [here](https://codesandbox.io/s/objective-fire-xdehqv?file=/src/styles.css).
