### ISSUE TITLE
[Component Name]: List

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-webcomponents-react#4588]
### Describe the bug

When the role='button' property is set on a component in the `ui5-webcomponents-react` library, accessibility software like JAWS reads the list twice instead of once.

### Reproduction steps

```
import { List, StandardListItem } from 'ui5-webcomponents-react';

const MyComponent = () => {
  return (
    <List role="button">
      <StandardListItem>Item 1</StandardListItem>
      <StandardListItem>Item 2</StandardListItem>
      <StandardListItem>Item 3</StandardListItem>
    </List>
  );
};
```
After adding the above property role="button"  the accessibility software reads the list item twice.

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

1.12.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @nipun0212 

Please follow the guidelines for opening issues. "[Component Name]: List" doesn't give information of what the issue is about.

The `List` offers a `accessibleRole` prop. Please set the role there. Also I'm not sure if "button" should really be used as a role for a list, as "The button role is for clickable elements that trigger a response when activated by the user" ([source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role)), since this should probably never be the case for a list it may not be the right choice here.
