### ISSUE TITLE
Analytical Table: Highlight Rows

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#461]
**Is your feature request related to a problem? Please describe.**
The Fiori specifications for Analytical Table detail a "highlight rows" functionality. It can be found here: https://experience.sap.com/fiori-design-web/analytical-table-alv/#personalization under "Highlight Items." The React Analytical Table does not provide this functionality at this time.

**Describe the solution you'd like**
That this functionality can be provided based on the Fiori specifications.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/8508119/80553113-885dfe00-897d-11ea-8aa1-861f03eb61da.png)

**Comment by MarcusNotheis** [comment]
Hi @agauyeung 
our `AnalyticalTable` is providing such a feature since [0.9.0-rc.6](https://github.com/SAP/ui5-webcomponents-react/blob/master/CHANGELOG.md#090-rc6-2020-03-31):
You can enable row highlights by setting the prop `withRowHighlight` on the `AnalyticalTable` and pass a field accessor `highlightField` where the corresponding row state can be found, e.g. `status`. The status should be part of the rows and an instance of `ValueState`, e.g. `ValueState.None, ValueState.Information, ValueState.Success, ValueState.Warning, ValueState.Error`.

Example:
```jsx
const data = [ { row: 1, status: ValueState.Error } ];
const columns = [ { Header: 'Row 1', accessor: 'row' } ];
return (
  <AnalyticalTable columns={columns} data={data} withRowHighlight highlightField="status"/>
)
```
This code would render a row with a red row indicator.
Or do you need more flexibility and pass custom hex codes or something similar?

**Comment by agauyeung** [comment]
Thanks for pointing this out. This is helpful!
Is there a way to provide a custom hidden column header for the highlight column so that it will be read by screenreaders? (i.e. if I wanted a highlight to indicate that the row is "New")

**Comment by MarcusNotheis** [comment]
Unfortunately not, but I have a really hard time to come up with an intuitive API for that issue. Would you have any proposal?
