### ISSUE TITLE
Framework: UI5 Webcomponents do not mount and unmount correctly

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4656]
### Describe the bug

I found a really stange behaviour with ui5-webcomponents.

It seems, that as soon as your components are in a shadowdom of a component, the dom does not unmounts the components correctly. 

I had several bugs regarding this issue because If I use `CodeMirror` as library, the CodeMirror attaches himself a div reference and will unmount if the div components correctly unmounts. But it seems that the div components does not unmount because if you follow the "Reproduction steps" then you will see, if I open the page 1 you see that the codemirror has problem with ui5 webcomponents to initialize. (Why??)
Then as soon as you switch to page 3 without ui5 webcomponents the codemirror mounts correctly. If you switch back again to page 1 the page is also correctly mounted (Why???)

This may also lead in a memory leak?

### Isolated Example

https://codesandbox.io/p/sandbox/page-bad-performance-forked-ug741s?file=%2Fsrc%2FApp.tsx%3A54%2C5

### Reproduction steps

1. Click on Page 2 - See that the Codemirror is not rendered correctly
2. Click on Page 3 - See that the Codemirror is correctly rendered
3. Click on Page 2 - See that now the Page 2 does also correctly rendering the Codemirror

The same behaviour is with other components as well.

### Screenshots or Videos

![GIF 30 05 2023 14-36-37](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/05bb05d3-b874-476e-8afc-d03fb0a35013)

### UI5 Web Components for React Version

1.15.1"

### UI5 Web Components Version

1.13.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

I tested the mounting/unmounting behavior and it's working as intended.

And after reading the documentation, I think I found the issue. It seems like that the editor is looking up the "root" if not defined by the [root](https://codemirror.net/docs/ref/#view.EditorConfig.root) option. Since this is the case here (because of the shadow-root), the styles are probably injected in the wrong place and therefore not applied.

[Here](https://codesandbox.io/p/sandbox/page-bad-performance-forked-lijiwl?file=%2Fsrc%2FApp.tsx%3A109%2C60) you can find a working example. Please note that I also removed the `editorRef.current` from the dependency arrays as it's considered bad practice and only triggered an unnecessary rerender for me.

**Comment by C3ntraX** [comment]
Hi @Lukas742,

thank you!!

The behavior of the shadowdoms in the HTML tree is sometimes really a mystery to me. And even more, how react is interacting with the shadowdom.

The "editorRef.current" as dependency array is used as example in the documentation. 
And with the memorized values, I know how it works but sometimes I wrap everything in memos xD
