### ISSUE TITLE
[AnalyticalTable]: Dynamic table column width based on content

### ISSUE THREAD

**Issue by Lultik** [SAP/ui5-webcomponents-react#4657]
### Is your feature request related to a problem?

 I am currently using the UI library, and I came across a limitation that I believe could benefit from a new feature: the ability to automatically adjust the width of table columns based on the content within them. Right now, it seems we are required to define fixed column widths, which can lead to unnecessary whitespace or truncated content, depending on the data being displayed.

### Describe the solution you'd like

- Add functionality to allow table columns to automatically resize based on the width of the content they contain.
- Provide an option to enable/disable auto resizing of columns for each individual table.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Lultik 

this feature is already available for text content (see `[scaleWidthMode](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--docs#properties)` description for more information and limitations). For custom cell content, this will not be supported out of the box, mainly because it'd affect performance too much, but also because it can be implemented by developers (e.g. via `ResizeObservers`), since the `width` of columns are controllable.
