### ISSUE TITLE
[SF] Add background color  in the Input component  under the Read-only mode.

### ISSUE THREAD

**Issue by hxempty** [SAP/ui5-webcomponents-react#4685]
When I use  input component,the component style is different from the  design.
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/3ad925e2-4485-4dc1-93ad-ec42556f6296)

### Describe the solution you'd like

fiori Guidelines:
https://experience.sap.com/fiori-design-web/input-field/
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/b5a4827f-93e8-4500-9e1c-b9fe32df25fe)
Background has color  under the Read-only mode.

Now ,
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--docs
There is no color   under the Read-only mode.
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/710016f7-2f5c-47e1-9a8f-39421d747e44)

### Declaration

- [ ] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @hxempty 

the example at experience.sap.com, is using the Quartz Light theme whereas you're probably using Morning Horizon.

Screenshots taken from our [storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--docs):

Quartz Light:
<img width="317" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/9749730/2e8f0e41-922e-43b6-8c6f-2ceb590cd615">

Morning Horizon:
<img width="301" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/9749730/13f37c3c-6023-4a18-b903-9b2792df2fd4">

We're not responsible for the content of experience.sap.com.
So, if you feel like this should be changed or better outlined please either leave feedback via the feedback button directly on the page, or leave your feedback at[ SAP Commuity](https://answers.sap.com/questions/ask.html?primaryTagId=73554900100700000977), since we're not responsible for the content of these pages.
