### ISSUE TITLE
[Popover]: Popover position misplaced on click of button after ui5-webcomponents upgrade when Shellbar is present

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents-react#4703]
### Describe the bug

The position of the popover is below it's expected position (next to its opener) on click of the opener button as seen in the screenshot below. This issue is present after upgrade of ui5-webcomponent libraries to the following versions:
```
"@ui5/webcomponents": "~1.13.3",
"@ui5/webcomponents-fiori": "~1.13.3",
"@ui5/webcomponents-react": "~1.14.0"
```

<img width="1680" alt="Screenshot 2023-06-07 at 8 26 35 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/32254036/903603f9-88ce-42bc-ade5-cafa36346fd5">

It used to be displayed next to it's opener on click of the opener button before the ui5-webcomponent library upgrade:

<img width="1680" alt="Screenshot 2023-06-07 at 8 31 57 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/32254036/a2d2ca44-4000-4757-a727-12d45b25ccc9">

### Reproduction steps

1. Log in to qacand (credentials provided in #sap-tech-ui5-wc-sfsf slack channel)
2. Search for "script-based integration settings" in global search and click on the link to be navigated to the Script-Based Integration Settings page.
3. Click on "Add Vendor" button and enter the vendor id as "walkme". Click on "Add" button.
4. Click on the question mark icon next to "GUID" and notice that the popover is displayed to the button right of the button instead of being displayed right next to it.

### Expected Behaviour

The popover should be displayed right next to the button instead of being displayed to its bottom right.

### UI5 Web Components for React Version

1.14.0

### UI5 Web Components Version

1.13.3

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rama1990br 

I see that you're mounting the dialog deeply in your DOM tree. Could you try if the same happens when mounting it below the root element of the document (e.g. `body`) as explained [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-working-with-portals--docs).


Next time, please consider creating a reproducible example using this [codeSandbox template](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx). The main advantage is that it is much easier for us to isolate the problem, show you what went wrong with your implementation, or provide a workaround until a fix is available. Also, for other users, these types of issues have no value because the necessary information is hidden in our internal systems, so duplicates can occur, which in turn increases the support effort on our end.

**Comment by rama1990br** [comment]
Hi @Lukas742 ,
Thanks for your quick response! Using `createPopover` to mount the popover right under the document body worked.

Also, I had tried to reproduce this issue using the code sandbox, but wasn't able to since this issue only happens with the shellbar and the shellbar that we are using is [xweb-shellbar](https://github.wdf.sap.corp/xweb/shellbar) and I wasn't sure how to include it in the sandbox. Please let me know if there is a way to do that.

Thanks for your help again!

**Comment by Lukas742** [comment]
Hi @rama1990br 

glad to hear that it worked. :)
Since the public codeSandbox instance only works for public modules and the `xweb-shellbar` is only available internally, you can't include it.
