### ISSUE TITLE
[Toolbar]: Toolbar overflow does not work correctly if the toolbar is not 100% of the screen width

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4810]
### Describe the bug

If you put `SideNavigation` on the left (or right) site and a `toolbar` on the right site, then the `toolbar` overflow does not work anymore.

### Isolated Example

https://codesandbox.io/p/sandbox/cranky-fire-v8jtwm?file=%2Fsrc%2FApp.tsx%3A21%2C32

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

I think a ResizeObserver is missing?

### Screenshots or Videos

![OverflowNotWorking](https://github.com/SAP/ui5-webcomponents/assets/44802503/a21f1f4e-7cff-4bd6-91ef-004fe305e22c)

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
See: https://github.com/SAP/ui5-webcomponents/issues/7268

**Comment by C3ntraX** [comment]
Hi @Lukas742,

another small topic. I found wrong css selectors in your toolbar:

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/d420dbf0-db6c-47af-bd2f-8824d59cde30)

The css for: `.Toolbar-toolbar-0-2-62 > *:not(first-child):not(last-child):not(.spacer)` is not working because `(first-child)` needs to be `(:first-child)` and the same for `(last-child)`

Pls look into other css as well, there may be wrong selectors.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

this is the expected behavior of the Toolbar, as the container doesn't shrink. (See [codeSandbox](https://codesandbox.io/p/sandbox/mystifying-feather-8hqn8m?file=%2Fsrc%2FApp.tsx%3A56%2C18))

> another small topic. I found wrong css selectors in your toolbar:

Thank you for noticing, the linked PR will fix this.

**Comment by C3ntraX** [comment]
Hi @Lukas742 

pls see again the example.
https://codesandbox.io/p/sandbox/cranky-fire-v8jtwm?file=%2Fsrc%2FApp.tsx%3A27%2C17

I dont know, why this is expected, but can I make a PR and this may be implemented? 
Because the current state makes no sense to me, Im confused lol

**Comment by Lukas742** [comment]
Hi @C3ntraX 

this is standard CSS behavior. 

I've edited your [codeSandbox](https://codesandbox.io/p/sandbox/hardcore-sutherland-q8flxl?file=%2Fsrc%2FApp.tsx%3A29%2C169) to explain this better.

**Comment by C3ntraX** [comment]
HI @Lukas742,

thank you, I didn't know when your `Toolbar` puts the buttons in the overflowcontext until now 👍

**Comment by C3ntraX** [comment]
It the sidebar always 15 rem or does this change with different themes? I may need a variable?

**Comment by Lukas742** [comment]
Currently it seems to be 15rem in width with every theme, since no CSS variable is used there. Without overriding the value, however, it's not guaranteed to stay that way, and besides, depending on the use-case, the SideNavigation can also be collapsed, which then naturally leads to a smaller width. That's why I would try to avoid setting a fixed value there and rather solve this with CSS. E.g. with a grid this should be possible.

[codeSandbox](https://codesandbox.io/p/sandbox/divine-morning-hvwgvq?file=%2Fsrc%2FApp.tsx%3A17%2C39)

**Comment by C3ntraX** [comment]
Thanks & Nice CSS skills 💯

**Comment by C3ntraX** [comment]
Hmm its somehow not working with your example in my app:

![OverflowNotWorking](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/0b806dde-ae5c-4ba5-82cf-57c05d367b56)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/b87dcd10-9f26-488e-8a76-5e20884bc716)

If you know whats wrong tell me otherwise I can try to reproduce this in sandbox.

**Comment by Lukas742** [comment]
Looks like similar behavior as before (container doesn't decrease its width and therefore the toolbar doesn't go into overflow). You have to make sure that the toolbar itself would overflow, otherwise (as it's not overflowing) no overflow button will be displayed. 

I can take a look at a codeSandbox if you like, but most probably only next week then ;)
