### ISSUE TITLE
[SplitterLayout,Label &Icon]: Moving the splitter bar has different behavior on flexbox (depending flexbox content)

### ISSUE THREAD

**Issue by Damien9222** [SAP/ui5-webcomponents-react#4884]
### Describe the bug

(see isolated example)
Using the SplitterLayout, create 2 flexbox (on the right SplitterElement) containing:
1. CheckBox & Icon
2. Label & Icon
Moving the splitter bar on the right (using the mouse) make disappear the icon of the flexbox with label, not the other.

### Isolated Example

https://codesandbox.io/s/loving-shape-k753rl?file=/src/App.js

### Reproduction steps

1. Open the codesandbox: https://codesandbox.io/s/loving-shape-k753rl?file=/src/App.js
2. In the UI, you see a SplitterLayout compnent with on the right 2 Flexbox
3. If you move the Splitter bar to the right with the mouse, you see (screenshot 1):
  a. The first FlexBox (with the CheckBox) truncate the text of the CheckBox (adding'...') and the icon do not move
  b. The second FlexBox do not truncate but the icon move to the right
4.  If you continue to move the Splitter bar to the right (screenshot 2):
  a. The first FlexBox (with the CheckBox) truncate the text of the CheckBox (adding'...') and the icon do not move
  b. The second FlexBox truncate the text of the Label (adding'...') while the icon has disappeared

### Expected Behaviour

The expected behaviour is the behaviour we of the FlexBox containing CheckBox & Icon:
The icon should not move & disappear ; only the label text should be truncated with an '...'.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/99638859/9208301a-3412-4681-a78e-b68414f6c4a9)
![image](https://github.com/SAP/ui5-webcomponents-react/assets/99638859/1c776d3d-bb1a-499b-a4cf-ed352e46368c)

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Damien9222 

this is not connected to the `SplitterLayout`, but the `Label` component and how standard CSS works.
The label of the `CheckBox` is using `overflow: hidden` per default, that's why the element is icon is not "pushed" outside of the container in this case, whereas the default `Label` does not implement this style per default. When added you can observe the same behavior as with the checkbox. --> [codeSandbox](https://codesandbox.io/s/great-andras-4yyhd8?file=/src/App.js) 

If you feel like this CSS property should be enabled per default for the `Label` component, please let me know. I will then transfer this issue to the ui5-webcomponents repo, as the component is developed there.

**Comment by Damien9222** [comment]
Hi @Lukas742,

Thanks a lot for your quick answer.
Indeed, setting the overflow to hidden fix my problem. It's just the default behaviour that is different. So,I close this issue.
Thanks a gain.
Regards.
