### ISSUE TITLE
[ObjectPage]: PaddingBottom causes flickering

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents-react#4885]
### Describe the bug

When a padding bottom is set on object page, it can cause flickering

### Isolated Example

https://codesandbox.io/p/sandbox/bold-germain-9hgx3y?file=%2Fsrc%2FApp.tsx%3A53%2C56

### Reproduction steps

1. Open example in a new window
2. Set your window height to 1045
3. check flickering
...

### Expected Behaviour

no flickering when custom styles provided

### Screenshots or Videos

![Kapture 2023-07-13 at 13 17 28](https://github.com/SAP/ui5-webcomponents-react/assets/32869456/0009ef28-563b-4351-acaa-c2fa32497f5f)

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rvsia 

setting a `padding` is not supported on the `ObjectPage`, since paddings are implemented according to our design guidelines. If you still need to set a `padding-bottom` you could probably add it the the last section of the page.

Please also note, that you didn't set the mandatory `id` prop of each section. This could also lead to unintended behavior.

 --> [codeSandbox](https://codesandbox.io/p/sandbox/nervous-dust-rzfvld?file=%2Fsrc%2FApp.tsx%3A51%2C61)

**Comment by rvsia** [comment]
Thank you for response @Lukas742 :) We removed the custom padding,
