### ISSUE TITLE
Worklist Floorplan component

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents-react#4909]
### Is your feature request related to a problem?

We are currently trying to implement the Worklist Floorplan, but we're experiencing difficulties with the provided standard components. We're always frustrated when we encounter this problem because it hinders our progress.

### Describe the solution you'd like

There are two potential approaches that we can consider:

1. **Introducing a Specialized Worklist Floorplan Component**: Much like the existing Objectpage, we could design and add a dedicated Worklist Floorplan component. This could specifically cater to our unique requirements, making it an intuitive and efficient solution for us.
2. **Enhancing the Flexibility of Existing Components**: Rather than creating an entirely new component, we could also opt to extend the customization options for our existing components. This approach would involve:
    - The ability to deactivate the standard content padding within a Page component, thereby enabling us to incorporate a tab container seamlessly.
    - The option to disable the dropshadow or border of a bar component, providing a cleaner and more customized visual appearance.

### Additional Context

- [Fiori Worklist Floorplan](https://experience.sap.com/fiori-design-web/work-list/)

The wanted solution: 
![Worklist_with-tabs_L_1 82](https://github.com/SAP/ui5-webcomponents-react/assets/61137799/89cf347b-079b-4932-bb01-0cf548a19c7b)

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @skowrons 

I think this should already be possible.

> The ability to deactivate the standard content padding within a Page component, thereby enabling us to incorporate a tab container seamlessly.

You can use the `::part(content)` pseudo element to style the content of the `Page` component inside the shadow root. I noticed that this is missing in the UI5 Web Components [documentation](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-page--docs) and therefore it's missing in ours as well. I'll raise an issue about this in their repo.
Since the Object- and Dynamicpage are directly developed by us and are therefore plain React components, which are leveraging web components, you can use simple CSS to remove the padding there. E.g.:
```css
[data-component-name='ObjectPageContent'] {
  padding-inline: 0;
}

[data-component-name='DynamicPageContent'] {
    padding-inline: 0;
}
```

> The option to disable the dropshadow or border of a bar component, providing a cleaner and more customized visual appearance.

Where do you need to use the `Bar` component? I looked into the specs and I didn't find that there should be a Bar somewhere.

[Here](https://codesandbox.io/p/sandbox/elegant-joji-9mj5fp?file=%2Fsrc%2FApp.tsx%3A23%2C45) you can find a very simple example how the WorklistFloorplan could look like with an ObjectPage. If you want to control the section via the `TabContainer` component yourself, you could either use the DynamicPage or the Page component.

**Comment by skowrons** [comment]
Hello @Lukas742,

Firstly, I'd like to extend my sincerest thanks for your swift response. The solution you have put forward has been implemented seamlessly and has successfully rectified the issue at hand. I feel confident in stating that, with the provision of your example, we can now consider this issue resolved.

If I may add a suggestion for future reference. It could potentially be very beneficial if there were an example available for each floorplan within the framework. I believe this could significantly ease the onboarding process for newcomers.

Once again, thank you for your effective support and your time. Keep up the excellent work! 👍🏻
