### ISSUE TITLE
SplitterLayout in a Dialog: make the SplitterLyout remind the proportion set by the user

### ISSUE THREAD

**Issue by ehn-sap** [SAP/ui5-webcomponents-react#4926]
### Is your feature request related to a problem?

As a user of a Splitter Layout in a Dialog, after I changed the layout proportion, I want to keep the chosen proportion even after a resize of the Dialog.

### Describe the solution you'd like

Make the SplitterLayout remind the chosen proportion, and apply it again after a Dialog resize.

### Describe alternatives you've considered

Adding a SplitterLayout property "options" object with "resetOnSizeChange" does not give a satisfying behavior.
The layout proportion is reinitialized to its initial value, despite the choice of the customer.

[This sandbox](https://codesandbox.io/s/dialog-splitter-xvwwrs) shows the two different behaviors using resetOnSizeChange true and false.
None is considered to be satisfying.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @ehn-sap 

please don't only send the "app view" (iframe) page as example, as it's not possible for us to look at or edit your implementation.

I'm not 100% sure if I understood what you want to achieve. Do you want to keep the dynamic initial `size` value of the SplitterElements as calculated (fixed) value when the SplitterLayout is resized? 
E.g.: 
- initial `size` value of the first element is  `30%`, the respective calculated (fixed) value is `120px`
- on resize the element should keep its width of `120px` and don't use `30%`

If this is the case, then this behavior is by design. Since you can just set the `size` prop to control the width/height of the element. You can for example watch for size changes by adding a ResizeObserver and persist the calculated `size` value yourself.

**Comment by ehn-sap** [comment]
Hi @Lukas742 

Thanks for your quick answer.

> please don't only send the "app view" (iframe) page as example, as it's not possible for us to look at or edit your implementation.

Sorry for that, I didn't pay attention and am not an expert using Code Sandbox. I edited the sandbox link in the description.

> I'm not 100% sure if I understood what you want to achieve. Do you want to keep the dynamic initial `size` value of the SplitterElements as calculated (fixed) value when the SplitterLayout is resized? E.g.:
> 
> * initial `size` value of the first element is  `30%`, the respective calculated (fixed) value is `120px`
> * on resize the element should keep its width of `120px` and don't use `30%`

I'll try to be clearer.

- Let's say we have a `SplitterLayout` with 2 elements. Their size are expressed as percentages.
- Let's say they are 30% for the 1st one, 70% for the second.
- This is the initial layout.
- The user uses the splitter bar to change this proportion for, eg, 50% for the 1st one, 50% for the second one.
- The user then resizes the dialog
    - If `resetOnSizeChange` is true, the sizes of the elements are forced back to apply the initial proportion, ie 30%-70%.
      The proportion chosen by the user is lost.
    - If `resetOnSizeChange` is false, the size of the first element is unchanged, but the size of the second element "takes all" of the size change. The new proportion can be, eg, 20%-80% (the dialog became wider), 80%-20% (the dialog had been narrowed)... Anyway, the proportion chosen by the user is lost.

The point our UX disagrees on is that the proportion chosen by the user is lost in both cases.
So we would like to maintain the proportion (in percentages, not sizes in pixels) of the elements even after a dialog resize.
For example, we could have an option named `onSizeChangePolicy`, with 3 possible values:
- `resetInitialRatio` (behavior equivalent to `resetOnSizeChange === true`),
- `maintainActualRatio` (the behavior I just described, preserving the ratio chosen by the user),
- `changeRatio` (behavior equivalent to `resetOnSizeChange === false`)


> If this is the case, then this behavior is by design. Since you can just set the `size` prop to control the width/height of the element. You can for example watch for size changes by adding a ResizeObserver and persist the calculated `size` value yourself.

You're right, we could probably do that.
We considered it would be cleaner and safer (regarding possible changes in future versions) to rely on the `SplitterLayout` capabilities, and our UX considered it would be a consistent behavior.

Thank you
Enrick

**Comment by Lukas742** [comment]
Hi @ehn-sap 

unfortunately we decided not to implement this feature. This has mainly two reasons:

- SAP/OpenUI5 doesn't offer this feature as well, so there could be discrepancies when using the [Splitter](https://sapui5.hana.ondemand.com/#/api/sap.ui.layout.Splitter) layout of SAP/OpenUI5 and our React implementation if this feature was a default feature of this component.
- Currently we're calculating the size of our `SplitterElements` by increasing/decreasing the size of the elements that are next to the splitter. If we would offer a behavior that let's you keep the ratio instead of a fixed value, we would need to persist each size of the splitter to calculate the ration corresponding to the total size of the layout and also taking into consideration whether a splitter has a `minWidth` attached or is not resizable at all. Because of that the complexity of the component would increase noticeably and if the layout includes many elements, probably also the performance would suffer.
