### ISSUE TITLE
[Menu Component]:  Submenu options are getting overlapped and misaligned in toolbar

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents-react#4931]
### Describe the bug

Submenu options are getting overlapped and misaligned in toolbar.

### Reproduction steps

1. Open SubMenus in Menu 
2. There we can see the overlapping and mis alignment
3.
...

### Expected Behaviour

There shouldn't be any misalignment or overlapping.
  

### Screenshots or Videos

<img width="487" alt="Screenshot 2023-07-31 at 3 30 35 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/107616257/71e05631-b621-473f-a95b-9f6ea37457f1">

<img width="678" alt="Screenshot 2023-07-31 at 3 30 29 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/107616257/6ffd934e-3dd2-463d-a89b-97e08bf85387">

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @ShivamGuptaSap 

Please follow the guidelines for opening issues. "Menu:" doesn't give information of what the issue is about.

Also, please add a reproducible example as described in our template. From the screenshots, I can't assess the implementation details or the height and width of the viewport, which is important since popovers are supposed to overlap their "opener" element when there is not enough space to fully display both of them.

**Comment by ShivamGuptaSap** [comment]
Hi @Lukas742,
Please check the dummy code
https://codesandbox.io/s/charming-bash-jk5phm

**Comment by Lukas742** [comment]
The overlapping of the sub-menu seems to be implemented by design (see [here](https://experience.sap.com/fiori-design-web/button/#menu-button))
![image](https://github.com/SAP/ui5-webcomponents-react/assets/9749730/6bc4cc20-e5bf-4d96-b205-1255796196bd)

The reason that the popover is misaligned has two reasons:
- `e.target` is not always the `ui5-toggle-button` element, but the actual element where the user clicks on. E.g. if you click on the icon, then the target is `ui5-icon`. You can prevent that by using [currentTarget](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) instead.
- Depending on the state of the button, you're defining the opener on the `body` of the page, which then will lead to misalignment. 

In general, I would recommend using the [declarative way](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-menu--docs#since-180) of opening popovers in React instead of the imperative one.
