### ISSUE TITLE
[Button]: Attribute "hidden" hides the button when set to "false"

### ISSUE THREAD

**Issue by chrstief** [SAP/ui5-webcomponents-react#4937]
### Describe the bug

Using the attribute hidden on the button hides it, even when set to false.
`<ui5-button hidden={false}>UI5 Button</ui5-button>`

I can see hidden="false" as a string when I check the button in the Devtools. It can't be set like this, because setting it to any string evaluates as true on this boolean attribute.

### Isolated Example

https://codesandbox.io/p/sandbox/inspiring-pike-rdcyy8?file=%2Fsrc%2FApp.tsx%3A15%2C52

### Reproduction steps

Set hidden={false} on any button

### Expected Behaviour

When hidden is set to false, the button should not be hidden. It should be visible.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/65469300/0f919ef7-caa9-4427-a2ba-16771809e245)

### UI5 Web Components for React Version

1.17.2

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @chrstief 

web-components are still not well supported in React, that's one of the reason this library exists. We wrap all public properties of the ui5 web components, so they can be used as you would expect in the React eco system. 
This does not apply to (global) HTML attributes though, that's why it doesn't work with `hidden` and other boolean attributes that are not exposed by the web component itself. 
Basically, React also changes how standard HTML attributes are applied to standard HTML elements like `button`, `div` etc. but as web-components are custom build, this logic doesn't apply to them.

With standard html, the element will be hidden when the `hidden` attribute is specified, meaning it doesn't matter what value you pass to the attribute. 

```html
<ui5-button design="Default" type="Button" hidden="false" _ui5rt0="" _ui5host="" ui5-button="">UI5 Button</ui5-button>
```
`hidden="false"` will give you the same result as `hidden="true"` or `hidden`, as this is the standard behavior of that attribute.

If you want to use `hidden` conditionally, you could use the following syntax:
```jsx
<Button hidden={hidden ? hidden : undefined}>
```
That way the attribute will be removed if hidden is false.

In my opinion using conditional rendering is preferable in React though, as then the element won't show up in the DOM at all (depending on the use-case of course):
```jsx
{!hidden && <Button />}
```

I've prepared a[ codeSandbox example](https://codesandbox.io/p/sandbox/quizzical-paper-7stc4j?file=%2Fsrc%2FApp.tsx%3A30%2C9), that should explain this more.

**Comment by chrstief** [comment]
Hi @Lukas742, 

The `disabled` attribute works in exactly the same way. 
It, however works perfectly well and just like expected in ui5-webcomponents-react.

I'm hiding and disabling buttons in conjunction with user permissions and application state. While I'm currently using the more verbose conditional rendering as you suggested as a workaround,  it doesn't seem right that `hidden` and `disabled` are treated differently.

**Comment by Lukas742** [comment]
Hi @chrstief 

we discussed this internally and decided to support `boolean` HTML attributes with our wrapper.

The linked PR will remove all html attributes (except for `data-` and `aria-`) with the value of `false` (boolean __not__ string) from web-components. The attribute should then act more like a boolean attribute of a standard HTML element in React.

___

The difference from `hidden` to `disabled` is that `disabled` is a attribute/property directly implemented by the web-component, whereas `hidden` is not. (See [properties table](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-button--docs#properties))

`hidden` only hides the element from the UI (similar to CSS `display:none`) and can also be affected by CSS `display` values. Since it's in the DOM all logic within the component/element will still be executed and also it's possible for users to  reveal the hidden element, since they can remove the attribute in the dev tools. (see [here](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute)) With conditional rendering all these pitfalls aren't relevant, as the component/element doesn't get mounted. If you are aware of this and your use-case should be implemented with `hidden`, then of course that's alright. I just wanted to let you know.

Also `hidden` is currently not implemented with all its features in React, as `"until-found"` cannot be applied. (See [here](https://github.com/facebook/react/issues/24740))

**Comment by chrstief** [comment]
Hi @Lukas742 ,
thanks a lot, I appreciate it!
