### ISSUE TITLE
Adoption of overflow toolbar - always stay in overflow area

### ISSUE THREAD

**Issue by doruskova** [SAP/ui5-webcomponents-react#4959]
### Is your feature request related to a problem?

During the object page implementation, we found out that we have to manually restrict the width of the toolbar because the React version doesn't support the option to choose items that always will be in the overflow area. If you create a button that looks like overflow and resize the screen, you'll get and overflow within the overflow and that's not ideal behavior. The situation becomes more difficult with access rights on these items because the width of the area dynamically changes. 

### Describe the solution you'd like

We would like to have a toolbar that allows you to select items that will always stay in the overflow area like here https://ui5.sap.com//#/entity/sap.m.OverflowToolbar/sample/sap.m.sample.OverflowToolbarSimple

### Describe alternatives you've considered

We manually restricted the width of the toolbar area and we forced to show the overflow icon. 

### Additional Context

If there is any access rights applied, it's difficult to specify a fixed width of this area.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Thanks for reaching out!
This issue is unfortunately quite complex to solve on our end due to the following reasons:
1. As you already stated, our `Toolbar` component is currently not supporting the overflow priorities and adding this logic would result in massive changes in the component.
2. The UI5 Web Components Team has already build a new [Toolbar](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-toolbar--docs) component (exposed as `ToolbarV2` in Web Components for React) which is supporting the `overflowPriority` prop (not exposed in the docs yet), but unfortunately this new toolbar is only accepting a limited set of children (`ToolbarButton`, `ToolbarSelect`, `ToolbarSeparator` and `ToolbarSpacer`), so we can't use this new toolbar in our `DynamicPage` or `ObjectPage` yet.

We'll sync up with the UI5 Web Components Team on how we should proceed with the Toolbar (enhancing ours vs. supporting more children for Toolbar Web Component) - we'll keep you posted as soon as we know more.

**Comment by Lukas742** [comment]
Hello everyone,
with v2.0.0 of `@ui5/webcomponents-react` our Toolbar will be replaced with the Toolbar of ui5 web components were this feature is already available.
We will still keep our Toolbar in a separate package, but it won't receive any new features and only fixes for critical bug, so the requested feature will unfortunately not be implemented in our component.

Here is the updated link for the ui5 web components Toolbar: https://sap.github.io/ui5-webcomponents/components/Toolbar/

I'm going to close this issue now, as we decided not to offer this feature with our implementation of the Toolbar.
