### ISSUE TITLE
ObjectPage: header is always rerendered

### ISSUE THREAD

**Issue by nodari-dev** [SAP/ui5-webcomponents-react#4960]
### Describe the bug

By scrolling though the object page, header is always re-rendered, but there is no visual change, it causes performance issues.
Calculation of changing the style of the header is triggered on scroll event, but even when style should not be changed, header is anyway re-rendered

### Isolated Example

https://codesandbox.io/p/sandbox/charming-breeze-5zv6t9?file=%2Fsrc%2FApp.tsx%3A30%2C20

### Reproduction steps

1. Create a component with `ObjectPage`
2. Provide `headerContent` and `headerTitle` props
3. add child blocks into `ObjectPage` to make it scrollable
4. Scroll up and down when header is collapsed and check re-render of component

### Expected Behaviour

Header should not be re-rendered on each scroll event. Re-render should be triggered only when header will need to change style from collapsed to expanded.

### Screenshots or Videos

![Kapture 2023-08-10 at 16 10 41](https://github.com/SAP/ui5-webcomponents-react/assets/32438959/ba7a4d03-7f72-41e4-aeba-33fa061dd822)

### UI5 Web Components for React Version

Latest

### UI5 Web Components Version

Latest

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @nodari-dev 

there was a small issue with applying a property to the DynamicPageTitle, which the linked PR will fix. However, this should not have caused any performance issues.

Preventing the component from updating completely while scrolling is not feasible, as we need to calculate the currently selected section using the scroll position, because if a user scrolls too fast, this will not be noticed by the IntersectionObserver, so we need to use a fallback for this. Since this calculation is always done when the user is finished scrolling and not, for example, at every pixel, this calculation should not take much computing time (<10ms).

Also, you have not used `ObjectPageSection` as a child of `ObjectPage` in your example, which is not supported because then the tab bar is empty and users cannot scroll to specific sections.
