### ISSUE TITLE
StepInput valueState not reflecting state

### ISSUE THREAD

**Issue by brampurnot** [SAP/ui5-webcomponents-react#4969]
### Describe the bug

Hi there!

I have a StepInput component where the valueState is managed by React state. The logic is quite simple: if the value equals to the "min" value, then show an error. Else show a success valueState. 

For some reason, when I increase the step from 0 to 1, then the success valueState is correctly displayed. When I increase it again from 1 to 2, then it goes back to None. 

I created this little env here to show you:
https://codesandbox.io/p/sandbox/young-haze-xmn32w?file=%2Fsrc%2FApp.tsx%3A4%2C17

### Isolated Example

https://codesandbox.io/p/sandbox/young-haze-xmn32w?file=%2Fsrc%2FApp.tsx%3A4%2C17

### Reproduction steps

1. Increase the stepper to 1 
2. The valueState success is shown
3. Increase the stepper to 2
4. The valueState is back to None (even though the state shows Success)

### Expected Behaviour

The valueState should always be Success/green. 

### UI5 Web Components for React Version

1.18.0

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @brampurnot 

the reason for this behavior is the web component internally resetting the `value-state`, but since the React state doesn't "know" that, it keeps the same state and therefore doesn't update the component again. 

Currently you can only reset the state yourself e.g. by checking when the internal change is happening or by using an observer. Since web components aren't developed by us, I will create a feature request in the [ui5-webcomponents](https://github.com/SAP/ui5-webcomponents) repo asking our colleagues there if they'd consider offering a public event where it's possible to handle internal value-state changes and making internal value-state changes preventable.

Here you can find a workaround for this behavior: https://codesandbox.io/p/sandbox/stepinput-issue-forked-c74khq

**Comment by brampurnot** [comment]
Awesome, that workaround works like a charm 👍

**Comment by Lukas742** [comment]
Glad to hear :) 
I've now also opened a [feature request](https://github.com/SAP/ui5-webcomponents/issues/7444).
