### ISSUE TITLE
AnalyticalTable: No way to remove horizontal or vertical borders and scroll looks occupying a column

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents-react#4994]
### Describe the bug

1. AnalyticalTable should expose some props to show or hide borders.
2. Column under scroll bar gives wrong impression to the user. There seems to be another column that look half hidden under the scroll bar

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--docs

### Reproduction steps

1. Navigate to https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--docs
2. Check table example

### Expected Behaviour

1. There should be some props to handle hide and show or borders
2. Border should not cross last column

### Screenshots or Videos

<img width="1108" alt="Screenshot 2023-08-23 at 11 41 45 AM" src="https://github.com/SAP/ui5-webcomponents-react/assets/18447407/02086acb-4ae6-4837-91d4-d7ba913e35c7">

### UI5 Web Components for React Version

v1.18.0

### UI5 Web Components Version

NA

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @lateefsofi 

the AnalyticalTable is implemented by design and border customization is not part of it. Also I don't quite get what you mean with your 2nd point. Do you feel like there is some misalignment, or is it just because there's another vertical border? If it's only the border then this is by design as well (e.g. see [here](https://experience.sap.com/fiori-design-web/analytical-table-alv/#context-menu)(Quartz theme)).

Since you can just apply your own styles, you can of course change that in your application, but please note that internal CSS is not part of semantic versioning and can change without notice.
