### ISSUE TITLE
[AnalyticTable]: [Component ToolbarV2 not display in header prop]

### ISSUE THREAD

**Issue by irodrigob** [SAP/ui5-webcomponents-react#5060]
### Describe the bug

In the "header" prop I am passing a component with the ToolbarV2 and the toolbar is not displayed. But if I use the old version: Toolbar it works for me.

In the following example: https://codesandbox.io/p/sandbox/frosty-water-hdp83r?file=/src/App.tsx:8.57

You can see two components created with both toolbars. V2 does not display the table (in my project at least the table is displayed) but with the old version it is displayed.

Greetings and thanks

### Isolated Example

https://codesandbox.io/p/sandbox/frosty-water-hdp83r?file=/src/App.tsx:8,57

### Reproduction steps

1. Run the example as is and the table is displayed
2. Change the component from the "header" prop to the "CustomToolbarV2" component and the table will not be displayed.

### Expected Behaviour

The same as the old toolbar.

### UI5 Web Components for React Version

1.19

### UI5 Web Components Version

1.17

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @irodrigob 

since the `ToolbarV2` is a web-component, it has a different API as the `Toolbar`. In this case the `ToolbarV2` only allows `ToolbarButton`, `ToolbarSelect`, `ToolbarSeparator` and `ToolbarSpacer` as direct child of the component. 
The prop description doesn't reflect that very well, that's why I created a PR in the `ui5-webcomponents` repo to improve this.

You can find a working example [here](https://codesandbox.io/p/sandbox/modest-nobel-p7c42d?file=/src/App.tsx:29,21).

**Comment by irodrigob** [comment]
Thanks for you help, but if I want to use an Input (which I am using in another component i have) or any other component i cannot use ToolbarV2. I have to use the Toolbar that is marked as deprecated.

I think the two components should coexist until ToolbarV2 has the same functionality as the old one.

best regards

**Comment by Lukas742** [comment]
Hi @irodrigob 

thanks for your feedback. I agree that web-component `ToolbarV2` is currently limited in most features compared to the React `Toolbar`. We marked it as deprecated because `ToolbarV2` will be the new standard with our next major release (not yet on the roadmap) and will replace the old toolbar. So the main reason for us to use the `deprecation` annotation is so that developers know when they start a new project that it is better to use `ToolbarV2` instead of `Toolbar`, because otherwise they will have to adjust their implementation once we release v2.  

Nevertheless, I will discuss internally whether we should keep the annotation or just add a note so that it is not crossed out in IDEs that support JSDoc annotations.
