### ISSUE TITLE
MessageItem subtitle text should have text wrapping capability

### ISSUE THREAD

**Issue by KattiAkshay** [SAP/ui5-webcomponents-react#5063]
### Is your feature request related to a problem?

Hi 
We are consuming the `MessageView` component to render errors, warning and information. 
The requirement is not to use the `additionalText` in the MesssageView component but to make sure the text displayed as `subTitleText` be wrapped. so that user will not be navigating to the details panel.

### Describe the solution you'd like

Solution would be to provide the option to wrap the label here https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/components/MessageView/MessageItem.tsx#L189

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @KattiAkshay 

the `subTitleText` prop is not wrapping by design. For a more detailed view you can set `children`, if `children` are found then the `MessageItem` is interactive and users can find out more on the view that is displayed when selecting the corresponding item. 
To prevent discrepancies with other implementations of the component (e.g. [Sap](https://sapui5.hana.ondemand.com/#/entity/sap.m.MessageView)/OpenUI5) we therefore won't offer this behavior.
