### ISSUE TITLE
FlexBox Component Needs A Flex Child Component

### ISSUE THREAD

**Issue by NPKompleet** [SAP/ui5-webcomponents-react#5073]
### Is your feature request related to a problem?

The FlexBox component exists in the library and is used a lot. Unfortunately, it is impossible to make the children have Flexbox properties like flex-grow and order without adding them as in-line styles to the children.

### Describe the solution you'd like

Create a component named FlexChild or FlexItem that can be used as a child of the FlexBox and supports properties similar to flex-grow, order, flex-shrink etc.. as props.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NPKompleet** [comment]
Hi,
I also just realized that the SplitterLayout is somewhat of a flex-box itself. So the new component could probably also be used with it too.

**Comment by MarcusNotheis** [comment]
Hi @NPKompleet,

thanks for reaching out.

After discussing internally, we decided that we will not implement this feature due to three main reasons:
1. As the `FlexBox` component is accepting arbitrary children, you pass `div` or any other React component and add your custom styles with `className` or `styles`. Here you can use all flex box css properties in order to achieve your desired layout.
2. API Consistency with SAPUI5: SAPUI5 is offering a `FlexBox` control as well, but like in our implementation you can pass any children to it without wrapping them in a dedicated FlexBoxChild component.
3. If we would implement something like `FlexBoxItem`, we would need to offer a `GridItem`, etc. as well. This would add many components to our library and make it harder to maintain.

Thanks
Marcus
