### ISSUE TITLE
[SF][AnalyticalTable]: Row selection checkboxes missing accessible name

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents-react#5075]
### Describe the bug

Row selection checkboxes in `AnalyticalTable` are missing accessible name. The checkboxes do have tooltip property set which should be also applied to `accessibleName` property.

### Reproduction steps

1. Go to https://sap.github.io/ui5-webcomponents-react/iframe.html?viewMode=docs&id=data-display-analyticaltable--docs#display-indicator-for-navigated-rows
2. Open dev tools and select any checkbox in selection column
3. Check the `uit-checkbox` component and no accessibleName is set.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/1867889/c6af85c8-5753-4b4e-8e04-352fe577d0f5)

### UI5 Web Components for React Version

1.19.0

### UI5 Web Components Version

1.17.0

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @zhangliangyi 

the checkbox is only a visual indicator and cannot be focused by keyboard navigation, also the `title` is never displayed because of the same reasons. This [PR](https://github.com/SAP/ui5-webcomponents-react/compare/fix/at-cell-header-title?expand=1) will remove the unnecessary attribute.

**Comment by zhangliangyi** [comment]
@Lukas742 
You are right, thanks for the clarification.
