### ISSUE TITLE
[SAP][Analytical Table]: Parent row remains selected even when all the child rows are unselected

### ISSUE THREAD

**Issue by chiragSAP** [SAP/ui5-webcomponents-react#5128]
### Describe the bug

1.when all the child rows of a parent row are unselected, the parent row is shown as selected.
2.when all the child rows of the table are selected, the parents gets selected which means all the rows of the table are selected but the table header shows that the table is partially selected.

### Isolated Example

https://codesandbox.io/p/sandbox/kind-waterfall-jw3q78?file=%2Fsrc%2FApp.tsx

### Reproduction steps

1. Select the parent row
2. Unselect a child row (parent row is shown as partially selected)
3. Unselect all the child rows (parent row is shown as fully selected)

1. Select all the child rows

### Expected Behaviour

1.Parent row should be unselected
2.Table should be fully selected

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/129057796/efe511b8-ced3-4a7f-8772-c914fceba81a

https://github.com/SAP/ui5-webcomponents-react/assets/129057796/d7444657-001f-456f-b6b9-bcdbdb3c1c38

### UI5 Web Components for React Version

1.20.0

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by chiragSAP** [comment]
Hi Team,
any updates regarding this issue ?

Regards,
Chirag

**Comment by Lukas742** [comment]
Hi @chiragSAP 

> 1.Parent row should be unselected

Since you select the parent row, it's also selected, only the `indeterminate` state of the checkbox has a higher priority than the `selected` state. So this behavior is intentional.

> 2.Table should be fully selected

Unfortunately I wasn't able to reproduce this issue. I tried it with your codeSandbox (using v1.20.0) and also locally (using the latest version):

https://github.com/SAP/ui5-webcomponents-react/assets/9749730/27ad02db-8098-4c92-992a-bc6142b7c07c

Could you please check if this issue is still up to date?

**Comment by chiragSAP** [comment]
Hi @Lukas742 ,
I am also not able to reproduce the second issue now, 
Thanks a lot for the support.

Regards,
Chirag
