### ISSUE TITLE
[Planning Calendar]

### ISSUE THREAD

**Issue by Qcyk** [SAP/ui5-webcomponents-react#5146]
### Is your feature request related to a problem?

It is not related to any problem.

### Describe the solution you'd like

Hi, have you considered adding **Planning Calendar** component and **Single Planning Calendar**? Simillar ones that exist in SAPUI5 sap.m.PlanningCalendar and sap.m.SinglePlanningCalendar.

https://sapui5.hana.ondemand.com/#/entity/sap.m.PlanningCalendar
https://sapui5.hana.ondemand.com/#/entity/sap.m.SinglePlanningCalendar

It would be very helpfull :) 

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @Qcyk,

thanks for your feature request.
After careful consideration, we have come to the conclusion that we will not be offering a component such as the `PlanningCalendar` in the near future. The main reason for this decision is the complex requirements of this component and the resulting maintenance effort, which could exceed our capacities in this project.

In order to "bridge the gap", I would recommend to render the SAPUI5 Planning Calendar component within your react app.
Here's a quick example in StackBlitz: https://stackblitz.com/edit/github-2jrbjb?file=src%2FApp.tsx%3AL9-L18
The main part is happing in the `App.tsx`, line 9-18 where the SAPUI5 core is loaded, and then initialising the UI5 Component which is placed in the `ui5-planning-calendar` folder.

In case our project setup is getting more resources, we might reconsider our decision and then we'll reopen this ticket.

Thanks for your understanding!

**Comment by MarcusNotheis** [comment]
Additionally, should this component be available as a [UI5 Web Component](https://github.com/SAP/ui5-webcomponents/issues/7811) sometime in the future, we will of course wrap it and include it with our project as well.
