### ISSUE TITLE
[AnalitycalTable]: AnalyticalTableScaleWidthMode.Grow does not work for bold fonts

### ISSUE THREAD

**Issue by Lultik** [SAP/ui5-webcomponents-react#5189]
### Describe the bug

This bug appears if use bold font family for header and `scaleWidthMode={AnalyticalTableScaleWidthMode.Grow}` in `AnalyticalTable` component.

### Isolated Example

https://codesandbox.io/p/sandbox/objective-snow-j8l7fk?file=%2Fsrc%2FApp.tsx%3A18%2C15

### Reproduction steps

1. Use bold font for headers in AnalyticalTable
2. Use `scaleWidthMode="AnalyticalTableScaleWidthMode.Grow"`

### Expected Behaviour

Every column gets the space it needs for displaying its **_full_** header text and full text content of all cells without cropping endings of words.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/60568127/ac4317ed-21da-4d99-abcc-ef2089b9ae41)

### UI5 Web Components for React Version

1.21.1

### UI5 Web Components Version

1.18.0

### Browser

Chrome, Firefox

### Operating System

MasOS, Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Lultik 

in general we cannot support custom CSS that alters the size of content or heading text, because we're not using the actual cell for measuring (because that would hurt performance by a lot), but the text inside of it.

The good news is that after this [PR](https://github.com/SAP/ui5-webcomponents-react/pull/5188) is merged and published, you will be able to achieve this on your end. I.a. the PR changes the measurement for both the `Smart` and `Grow` mode to use a `div` for measuring the width of the content or header cells. So, if you added custom CSS to either the header, or the content, you can style the respective div in the same way to achieve the desired calculation.

The good news is that after this PR is merged and published, you will be able to accomplish this on your site. Inter alia, the PR changes the measurement for both Smart and Grow modes to use a div for measuring the width of the content or header cells. So if you add custom CSS to either the header or the content, you can style the respective div in the same way to achieve the desired calculation.

__Example:__

These are the two measure-divs that are responsible for calculating the corresponding column width:

```html
<span class="Text-text-0-2-49 AnalyticalTable-hiddenSmartColMeasure-0-2-281" aria-hidden="true" id="scaleModeHelper-:r7:" data-component-name="AnalyticalTableScaleModeHelper">1</span>
<span class="Text-text-0-2-49 AnalyticalTable-hiddenSmartColMeasure-0-2-281 AnalyticalTable-hiddenSmartColMeasureHeader-0-2-282" aria-hidden="true" id="scaleModeHelperHeader-:r7:" data-component-name="AnalyticalTableScaleModeHelperHeader">Einzelhändlerumsatz </span>
```

So in your case, you could add the `font-weight` like this for example:

```css
[role='columnheader'] > div > span:first-child {
  font-weight: bold;
}

/*selector of AnalyticalTable*/
.analytical-table ~ [data-component-name='AnalyticalTableScaleModeHelperHeader'] {
  font-weight: bold;
}

```
