### ISSUE TITLE
Toast doesn't appear on document

### ISSUE THREAD

**Issue by vinniimiranda** [SAP/ui5-webcomponents-react#519]
**Describe the bug**
I am trying do display a toast when an user clicks in certain button, but the toast doesn't appear

**To Reproduce**
![image](https://user-images.githubusercontent.com/33462844/82075582-d4fe4480-96b2-11ea-8787-d53198397dc3.png)

**Expected behavior**
Show up the toast message

**Comment by MarcusNotheis** [comment]
Hi @vinniimiranda,
the `Toast` component has an imperative API to show up - it will never show just because it is part of the DOM.
In order to display the Toast, you have to get a ref to the toast (e.g. via React-`ref` or `id`) and call the `show()` method there. I prepared a litte example in this codesandbox using the `ref` approach:
https://codesandbox.io/s/summer-breeze-z9rc7?file=/src/App.js

Best regards,
Marcus

**Comment by vinniimiranda** [comment]
Hi, thanks for the quickly response.

I didin't see this ins the docs, anyway its's working now.

Thanks!

**Comment by MarcusNotheis** [comment]
Good to hear,I'll add it to the docs as well.
