### ISSUE TITLE
[Analytical Table] First visible row.

### ISSUE THREAD

**Issue by bcagliari** [SAP/ui5-webcomponents-react#5319]
### Is your feature request related to a problem?

I don't have an easy way to specify which table row should be the first to be displayed. Sometimes I don't want the first item to be the first visible item in the table, so I need to use one of the provided methods for scrolling to a specific index, but the animation is unwanted.

### Describe the solution you'd like

I would like the firstVisibleRow property (you can check here: https://experience.sap.com/fiori-design-web/analytical-table-alv/) to be implemented, so that I can implement the expected behavior. I want to be able to choose which is the first visible row in the table.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @bcagliari 

we improved the behavior of our `scrollTo` methods. After the linked PR is merged, it'll be possible to scroll initially, meaning that you can for example call the scroll event when mounting the component.

```jsx
 useEffect(() => {
    tableRef.current.scrollToItem(12, { align: 'start' });
  }, []);
```

Because of this improvement and also because we'd have to call the respective method internally anyway to enable the `firstVisibleRow` prop, we decided not to add this prop as it has no advantage compared to calling the method and would therefore only bloat the props of the `AnalyticalTable` even more.
