### ISSUE TITLE
AnalyticalTable: Trapped in infinite resizing loop, flickering scrollbars

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#5354]
### Describe the bug

By setting the dimensions `280.4x800` on an AnalyticalTable, I managed to trap it in an infinite loop where it seems to try to resize endlessly, making a horizontal scrollbar + a second vertical scrollbar appear and disappear.

### Isolated Example

https://codesandbox.io/s/thirsty-keldysh-xptf6d?file=/src/App.js

### Reproduction steps

1. You need a small, high-DPI display (like that of your laptop).
2. That's it. Opening the sandbox should directly show you the bug, both in side-by-side mode as well as fullscreen mode.

Some info on my setup:
Win 11
Chrome 119
Resolution: 3840x2160 @ 250% Scale (that of Windows, not of the browser)

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/110408767/c2ba99a4-8889-44d1-848a-058c57879036

### UI5 Web Components for React Version

1.21.0

### UI5 Web Components Version

1.18.0

**Comment by Lukas742** [comment]
Hi @ej612 

I was able to reproduce this issue (only on Windows using Chrome, with the given resolution and scaling), but only when using `v1.21.0`. When updating to `v1.23.2` ([codeSandbox](https://codesandbox.io/s/red-water-5jqsvl)) the issue was gone for me. 
Could you please check if that's the case for you as well? If not, please feel free to set up an internal call so I can take a look at the issue.
