### ISSUE TITLE
[UploadCollection]: [Unable to display image within the Dialog]

### ISSUE THREAD

**Issue by Lisalisa007** [SAP/ui5-webcomponents-react#5375]
### Describe the bug

When opening the dialog by clicking a button, the images in UploadCollection cannot be displayed. However, by directly setting the open attribute hard code of the dialog to true, the images can be displayed.

### Reproduction steps

1.When opening the dialog by clicking a button, the images in UploadCollection cannot be displayed.

### Expected Behaviour

When opening the dialog by clicking a button, the images in UploadCollection can be displayed.

### UI5 Web Components for React Version

1.21.1

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lisalisa007** [comment]
![Screenshot 2023-12-27 at 15 19 07](https://github.com/SAP/ui5-webcomponents-react/assets/152941064/c4f0c351-12cd-4dd9-83e0-d1fbef2b4c2e)

**Comment by Lukas742** [comment]
Hi @Lisalisa007 

please add a reproducible example, preferably by using this [codeSandbox ](https://codesandbox.io/p/sandbox/ui5-web-components-for-react-vite-template-rcpmd4) template.

**Comment by Lisalisa007** [comment]
<>
        <Button
          onClick={() => {
            setOpenUploadDialog(true);
          }}
        >
          button
        </Button>
        <Dialog
          className={classes.dialog}
          open={openUploadDialog}
          headerText={t('headerText')}
          footer={
            <Bar
              endContent={
                <>
                  <Button design="Emphasized" onClick={upload} disabled={!formName}>
                    {t('upload')}
                  </Button>
                  <Button design="Transparent" onClick={cancelUpload}>
                    {t('cancel')}
                  </Button>
                </>
              }
            />
          }
        >
          <FlexBox justifyContent="Center" alignItems="Center">
            <UploadCollection
              mode="SingleSelect"
              onDrop={function _a() {}}
              onItemDelete={function _a() {}}
              onSelectionChange={function _a() {}}
            />
          </FlexBox>
        </Dialog>
      </>

**Comment by Lukas742** [comment]
This is not a sufficient example, e.g. there are functions that aren't defined, you don't use an UploadCollectionItem and there are no clear steps to reproduce the issue. For me it's currently not even clear what you mean by "the images in UploadCollection cannot be displayed."

Please either use the codeSandbox template above to create the example or create a public GitHub repo that is showing the issue i a minimal way.

**Comment by Lisalisa007** [comment]
Sorry, I am unable to open the website（codeSandbox） you provided. 
I have the latest discovery here. When I  set noDataText='Upload package ', the image and style of this component are displayed normally. However, when I give noDataText to other strings, the image and style of this component cannot be displayed properly.
              <UploadCollection
                mode="SingleSelect"
                onDrop={onFileDrop}
                noDataText="Upload package"
                noDataDescription={t('SetupPrintingUploadFileDescription')}
              />
![Screenshot 2024-01-09 at 10 18 33](https://github.com/SAP/ui5-webcomponents-react/assets/152941064/11665a27-fe00-42ed-8d3d-c1a1640c7250)
              <UploadCollection
                mode="SingleSelect"
                onDrop={onFileDrop}
                noDataText="Upload from"
                noDataDescription={t('SetupPrintingUploadFileDescription')}
              />
![Screenshot 2024-01-09 at 10 23 51](https://github.com/SAP/ui5-webcomponents-react/assets/152941064/96332bdc-f0f5-43d6-971f-d8d0ce73e6bf)

**Comment by Lisalisa007** [comment]
![Screenshot 2024-01-09 at 10 18 33](https://github.com/SAP/ui5-webcomponents-react/assets/152941064/c65df009-1842-403f-b855-dff77d279cbf)

**Comment by Lisalisa007** [comment]
![Screenshot 2024-01-09 at 10 23 51](https://github.com/SAP/ui5-webcomponents-react/assets/152941064/b7b18642-5743-4eb3-b763-3e5bbf4f4ea4)

**Comment by Lisalisa007** [comment]
![Screenshot 2024-01-09 at 10 23 51](https://github.com/SAP/ui5-webcomponents-react/assets/152941064/ae68ebf8-927c-4c53-b1cf-a28fc26d2d09)

**Comment by Lukas742** [comment]
I tested it again with the given `noDataText` and the `noDataSecription` and still it's working as expected for me. 

<img width="620" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/9749730/a2a3a734-755c-45e2-9053-8fa7d4a45bdc">

___

Since you don't have access to codeSandbox I've created a [public GitHub repo](https://github.com/Lukas742/codesandbox_upload_collection_issue/tree/main) which you can use to reproduce the issue.

Init:
1. clone the [repo](https://github.com/Lukas742/codesandbox_upload_collection_issue/tree/main)
2. run `npm i`
3. run `npm start`

**Comment by Lukas742** [comment]
I just realized what the issue here is about. You're rendering the UploadCollection in a small container and therefore no image is displayed. This is the standard behavior of the [IllustratedMessage](https://sap.github.io/ui5-webcomponents-react/?path=/docs/user-feedback-illustratedmessage--docs) which is used as placeholder here. You can see that in our storybook as well, just go to the [Default story](http://localhost:6006/?path=/story/inputs-uploadcollection--default) and resize the screen.

Since this behavior is intended, I'm going to close this issue now. If you feel like the `size` of the `IllustratedMessage` should be customizable without having to set a `width` or `height`, please open a [feature request](https://github.com/SAP/ui5-webcomponents/issues/new/choose) in the ui5-webcomponents repo, since both the `UploadCollection` and the `IllustratedMessage` are developed there.
