### ISSUE TITLE
[token]: [The delete button of the token component is not working]

### ISSUE THREAD

**Issue by Lisalisa007** [SAP/ui5-webcomponents-react#5380]
### Describe the bug

Clicking the delete button on the token component cannot delete the token

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

delete button can working

### UI5 Web Components for React Version

1.21.1

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Lisalisa007 

the `Token` is meant to be used inside the `MultiInput` or `MultiComBox` component and not as standalone. That's why the internal `delete` event is not publicly available. The linked PR will adjust that in our documentation by removing the standalone story of the `Token` and adding it as subcomponents of the respective parent components.

**Comment by Lisalisa007** [comment]
But, I used Token inside the MultiInput or MultiComBox, also cannot delete the token. But in previous versions, this token could be deleted and cannot be deleted now

**Comment by Lukas742** [comment]
Please try to provide more context when creating issues. "Does not work" does not help us find the cause or tell us how to reproduce the problem. 

Since everything works as expected for me, I will leave the issue closed until we get a minimal, reproducible example. You can use this [codeSandbox template](https://codesandbox.io/p/devbox/ui5-web-components-for-react-vite-template-rcpmd4?file=%2Fsrc%2FApp.jsx) for that.

**Comment by Lisalisa007** [comment]
Sorry, I am unable to open the website（codeSandbox） you provided.
<MultiInput
                      readonly
                      onTokenDelete={e => deleteToken(e, 'skus')}
                      style={{ width: '45rem' }}
                      onValueHelpTrigger={openSKUDialog}
                      showValueHelpIcon={true}
                      tokens={SKUs.map(item => (
                        <Token
                          data-skus={item.sku}
                          key={item.sku}
                          text={`${item.description} (${item.sku})`}
                        />
                      ))}
                    />

When I set readonly in MultiInput, the token cannot be deleted, but what I need is that when I set readonly, the token can also be deleted.
In previous versions（0.25.6）, tokens could also be deleted during readonly.

**Comment by Lukas742** [comment]
Hi @Lisalisa007 

no problem, in a simple case like this, an inline example is sufficient. For more complex issues, you could also use one of our templates and create a public GitHub repo we can take a look at. 

The `readonly` behavior in 0.25.6 was wrong and actually the representation of the token in MultiInput with readonly state still is. You can find out more about it especially in this [comment](https://github.com/SAP/ui5-webcomponents/issues/4522#issuecomment-1387109472) but also in the issue in general. Since the `Token`, `MultiInput` and `MultiComboBox` are all web components, developed by the UI5 Web Components team, you can leave any additional questions or feedback in the linked issue as well.

I'll now mark this issue as duplicate as the linked one covers your problem as well. 

Duplicate https://github.com/SAP/ui5-webcomponents/issues/4522
