### ISSUE TITLE
Nextjs: IllustratedMessage - Warning: Extra attributes from the server: ui5-shellbar-item

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#5386]
### Describe the bug

If I try to load the `IllustratedMessage ` component clientsite I get the error: `Warning: Extra attributes from the server: ui5-shellbar-item`  ServerSite it wont even function....

With this "Warning" my Hooks do not work anymore.

Do you even use the Next.js `Image` component to provide the Images? This may be the problem for ssr rendering.
For clientsite the initial component loads and shows the component unti it throws this error and all my hooks do not work anymore.

### Isolated Example

No template

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.23.3

### UI5 Web Components Version

1.20.1

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
Hi @Lukas742,

do you need more informations?

A codesandbox is tricky. You may want to offer additional codesandbox templates?

BR

**Comment by Lukas742** [comment]
Hi @C3ntraX 

I probably won't get around to taking a closer look at the issue until sometime next week. 

Regarding codeSandbox: 
Offering a template for Next.js in an online editor is definitely a good idea, but unfortunately I can't say when we'll get to it yet. Until its available, it would be very helpful if the problem is reproduced in a public GitHub repo. You are welcome to use our [template](https://sap.github.io/ui5-webcomponents-react/?path=/docs/project-templates--docs) for this.

Regarding the Image component:
Since the `IllustratedMessage` is a web component, it is not possible for us to pass an `Image` component there.

**Comment by MarcusNotheis** [comment]
Hi @C3ntraX,

I think your issue is describing two individual problems (I'm not aware that the `IllustratedMessage` is using the `ShellBarItem`):

**`Warning: extra attributes from server: <<TAGNAME>>`**

We are aware of this warning, but as far as I know there is currently almost nothing we can do about it.
During server side rendering, we're rendering the outer markup of the web components, e.g. `<ui5-button>Click me</ui5-button>`. On the client, we're importing the Web Component's JavaScript and the custom element gets defined. During this process, the UI5 Web Components are adding the tag name (without any potential scoping suffix) to the element as attribute (`<ui5-button ui5-button>Click me</ui5-button>`).
This behaviour is causing this warning, but as far as I know we can safely ignore this warning (don't get me wrong, I would love to get rid of it 🙂 ).

@ilhan007: Would it be safe for the UI5 Web Components for React wrapper to add the respective original tag name to the web component during server side rendering? Or would this have some bad side effects as this "tag name attribute" is kind of marker for "the web component is ready"?

**IllustratedMessage / Hooks not working**

Could you give me some more details on this topic please? Are you using the `pages` or the `app` directory?
In case you're using the `app` directory, we started to document [common pitfalls](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-server-side-rendering--docs#common-pitfalls), maybe this helps?
Which kind of hook isn't working, is it a custom hook or some build-in hooks like `useState`?

**Comment by C3ntraX** [comment]
Hello @MarcusNotheis,

thanks for the invastigation. 
Im using the new App-Router.
Futhermore, the images are imported via "use client" directive. 
Im using the useEffect hook.
I think I did everything right. 
I can provide some code snippets in some minutes

**Comment by C3ntraX** [comment]
Its basicially this code which does not work, used in `Suspense` React component:

```
"use client";

import "@ui5/webcomponents-fiori/dist/illustrations/SimpleNotFoundMagnifier.js";
import {
   IllustratedMessage as UI5IllustratedMessage,
   IllustratedMessagePropTypes,
} from "@ui5/webcomponents-react";
import { useEffect, useState } from "react";

type IllustratedMessageProps = IllustratedMessagePropTypes & {
   delay?: number;
};

const IllustratedMessage: React.FC<IllustratedMessageProps> = ({ delay, ...props }) => {
   const [show, setShow] = useState(true);

   useEffect(() => {
      let timeout: NodeJS.Timeout;
      if (delay) {
         timeout = setTimeout(() => setShow(true), delay);
      }
      return () => {
         if (timeout) {
            clearTimeout(timeout);
         }
      };
   }, [delay]);

   if (show) {
      <UI5IllustratedMessage {...props} />
   } else {
      return <></>;
   }
};

export default IllustratedMessage;
```

```
<Suspense
       fallback={
          <IllustratedMessage  delay={500} />
       }>
          <SomeLoadingComponent />
</Suspense>
```

**Comment by MarcusNotheis** [comment]
Sorry for the late reply, but I finally managed to create codesandbox with an suspense example: https://codesandbox.io/p/devbox/nextjs-wcr-suspense-5pv6wv?file=%2Fapp%2Fpage.tsx

In the code snippet you shared in this thread, there are two errors:
1. The IllustratedMessage component is missing a `return` in the `if (show)` block
2. In the `Suspense fallback` props, the `name` property is missing for the IllustratedMessage.

I'm not sure whether these two are also present in your code or whether this was just a copy-paste mistake?
In case your code is not having these two issues, would you mind updating my sandbox so that we can reproduce the error? Thanks!

**Comment by C3ntraX** [comment]
I modified your example.

https://codesandbox.io/p/devbox/nextjs-wcr-suspense-forked-l4fvrr?file=%2Fapp%2Fcomponents%2FIllustratedMessage.tsx%3A23%2C1

The problems are still the same. 

I don't know, whats wrong with the code.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

I think this issue is not related to our components. It seems like that the `fallback` component of `Suspense` can't be stateful. I'm not really sure if this is intended or not, because I couldn't find anything about it in the Next.js or React documentation, but I found a similar issue in the React repo (https://github.com/facebook/react/issues/27716) which hasn't received an answer yet.

I removed all of our components from the fallback component and tried it with standard divs and the behavior is the same. I also implemented a simple button that is updating a state within the fallback component and while the app is suspended, updating state also doesn't work. --> [codeSandbox](https://codesandbox.io/p/devbox/nextjs-wcr-suspense-forked-jxkkt9?file=%2Fapp%2Fcomponents%2FIllustratedMessage.tsx)
