### ISSUE TITLE
[SelectDialog/ViewSettingsDialog] Add customizable footer property

### ISSUE THREAD

**Issue by ThiagoSzz** [SAP/ui5-webcomponents-react#5418]
### Is your feature request related to a problem?

When using the `SelectDialog` or the `ViewSettingsDialog` components, I am not allowed to use the customizable `footer` property that is present in the `Dialog` component. That can be a problem since I might need to have different button options or different button texts (in other languages, for example) in the footer of the component.

![image](https://github.com/SAP/ui5-webcomponents-react/assets/49589136/f40b8149-9fd9-4e58-9370-6d94c05b7361)

### Describe the solution you'd like

It would be great to have the option of passing a custom footer for the components via the `footer` property like:

```typescript
<SelectDialog
  headerText="Selecionar produtos"
  footer={
    <>
      <Button>Selecionar</Button>
      <Button>Cancelar</Button>
    </>
  }
>
...
</SelectDialog>
```

### Additional Context

![image](https://github.com/SAP/ui5-webcomponents-react/assets/49589136/17abcfd7-e557-43ff-a102-798642abd255)
![image](https://github.com/SAP/ui5-webcomponents-react/assets/49589136/e2486e4f-96df-4464-9887-d51fef9a0903)

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @ThiagoSzz 

the `ViewSettingDialog` is a web component developed by the UI5 Web Components team. Therefore, please open another [feature request](https://github.com/SAP/ui5-webcomponents/issues/new/choose) in their repo for this component. 

The `SelectDialog` is implemented according to [UX guidelines](https://experience.sap.com/fiori-design-web/select-dialog/), so it is not intended for the footer to be customizable. Mainly because of a11y and i18n, but also to ensure a consistent look and feel across all applications. 

I'll close this feature request now, if you have a specific use-case that can't be solved with the current implementation of the component, please let us know by describing exactly what is missing and why you need that feature.
