### ISSUE TITLE
AnalyticalTableColumnDefinition: Throwing errors when width === undefined

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#5424]
### Describe the bug

We have an `AnalyticalTable` and want to set the widths of the columns programmatically. To do that, we use the `width` property of `AnalyticalTableColumnDefinition`, which is typed like this:

![image](https://github.com/SAP/ui5-webcomponents-react/assets/110408767/ab02c4a9-0dc0-447b-838e-671154ad64ff)

However, when I set `width = undefined`, I get the following runtime error in the console:
![image](https://github.com/SAP/ui5-webcomponents-react/assets/110408767/a77b68bc-c029-43fa-9e1e-6eb243fad767)

> Warning: `NaN` is an invalid value for the `width` css style property.

When setting `width = null`, I have to suppress a typescript error, but there is no issue at runtime.

Thanks a lot in advance!

### Isolated Example

Let me know if you need one

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

**Comment by Lukas742** [comment]
Hi @ej612 

we have our width property typed as `width?: number;` which is similar but not exactly the same as your screenshot shows. I'm not sure why it adds `undefined` there, but it might be related to the IDE or TypeScript configuration you are using. To apply stricter rules for optional properties, you can use the TypeScript compiler option `exactOptionalPropertyTypes`, then undefined will throw an error. More about this [here](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes).

However, we still try to support passing `undefined` to optional properties and in most cases, it doesn't even make a difference if the property is not set at all or just passed `undefined`. 
I wasn't able to reproduce this issue though. Maybe the problem has already been fixed in a later version? If you can reproduce it with the latest version, could you please create a [codeSandbox](https://codesandbox.io/p/devbox/ui5-web-components-for-react-vite-template-rcpmd4) so we can add a check there?
