### ISSUE TITLE
[SF][AnalyticalTable] Expanded rows by default when grouped, sorting, filtering, column order and others

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents-react#5426]
### Is your feature request related to a problem?

This seems to be the current Analytical Table's ability.
- there is no ability to filter or sort through the entire table
- grouped rows are not expanded by default
- grouped rows have a button
- `groupBy` column is always the first column (`columnOrder` doesn't seem to work for this scenario)
- first column is displayed although there is nothing in it

![SCR-20240117-njyw](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/1c8bbfee-b464-433a-a7dd-eed463bccb79)

![SCR-20240117-nkax](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/0181f612-7529-4962-b23c-16c8bc5e8f44)

### Describe the solution you'd like

This is what we would like to have:
- toolbar with title, filter and sorting options
- expanded rows by default when there is grouping
- grouped row title should not have any action
- column order to be customizable rather than having the `groupBy` column going first (`columnOrder` doesn't seem to work for this scenario)
- remove the first column (not display even when it's empty)

![SCR-20240117-nepm](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/cd6e7db1-436b-4491-803c-bc180036bc47)

### Describe alternatives you've considered

The [simple table](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-table--docs) doesn't seem to have enough ability to do the above.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rchrdchn 

many of the features are already available, please see my comments below:

> there is no ability to filter or sort through the entire table

You can use the `globalFilterValue` prop for filtering the entire table. As far as I know, global sorting is not supported by any of the SAPUI5 tables and I also couldn't find anything about it in the guidelines. Also, I'm not sure how the behavior should be implemented, as we can't guess the priority of each column. You can look into our multi-sort plugin hook (`useOrderedMultiSort`) and/or implementing a custom [sortType](https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/useSortBy.md#table-options), maybe global sorting can be supported with them, but we don't plan adding it.

> grouped rows are not expanded by default

You can programmatically expand all rows or specific rows by leveraging the instance method `toggleRowExpanded` or `toggleAllRowsExpanded`, also you can hook into the table either via custom plugin hook or by using the [useControlledState](https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/faq.md#how-can-i-manually-control-the-table-state) `reactTableOption`. ([very basic example](https://codesandbox.io/p/devbox/gallant-lederberg-3c8lj4?file=%2Fsrc%2FApp.jsx%3A42%2C32-42%2C53))

> grouped rows have a button

We need to take a look at this. We will let you know if this behavior can be implemented in the `AnalyticalTable` as soon as we have checked the feasibility of the implementation.

> column order to be customizable rather than having the groupBy column going first (columnOrder doesn't seem to work for this scenario)

This is not possible with the current implementation of the table and enabling it would need a major refactoring of the whole component, which we don't have the capacity for it and even if could introduce undesired breaking changes or even bugs. That's why we unfortunately won't support this feature.

> first column is displayed although there is nothing in it

This is because you set the table to `AnalyticalTableSelectionMode.SingleSelect` with `AnalyticalTableSelectionBehavior` `Row` or `RowSelector` and is the intended design. If you want to remove the empty cell, use `AnalyticalTableSelectionBehavior.Row`, if you don't want to use selection at all use `AnalyticalTableSelectionMode.None` (default).

> toolbar with title, filter and sorting options

You can use the `header` or `extension` prop to achieve this.

**Comment by rchrdchn** [comment]
Thank you @Lukas742. I've taken a look at the above mentioned and have decided to go with the simple table to build the filter and sorting mechanism from scratch. Closing this issue.
