### ISSUE TITLE
[ShellBar]: Child Events in menuItems slot do not fire

### ISSUE THREAD

**Issue by f16r** [SAP/ui5-webcomponents-react#5440]
### Describe the bug

Button click event does not work.

Working "plain" webcomponents example:
https://codesandbox.io/p/sandbox/ui5-webcomponents-playground-forked-dw65ml?file=%2Findex.html%3A46%2C20

Not working react example:
https://codesandbox.io/p/sandbox/interesting-mendeleev-vrl3mw?file=%2Fsrc%2FApp.js%3A26%2C16

### Isolated Example

https://codesandbox.io/p/sandbox/interesting-mendeleev-vrl3mw?file=%2Fsrc%2FApp.js%3A26%2C16

### Reproduction steps

1. Open MenuItems Popover
2. Click button

### Expected Behaviour

onClick event fires, alert is displayed

### UI5 Web Components for React Version

1.23.1

### UI5 Web Components Version

1.20.1

### Browser

Chrome

### Operating System

Win 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @f16r 

`menuItems` are only supported by list items like `StandardListItem` or `CustomListItem`, all other elements or components can lead to unintended side effects. E.g. in this case there are two `List` components nested in each other, as the slot is wrapped inside a list and you render a list as well. I also tested it using plain ui5-webcomponents without our wrapper in React, and the result is the same. --> [codeSandbox](https://codesandbox.io/p/devbox/summer-pine-qwc3wm?file=%2Fsrc%2FMenuItems.jsx%3A51%2C12)

If you feel like it should be possible to customize the menu items more, please open a feature request in the [ui5-webcomponents](https://github.com/SAP/ui5-webcomponents) repo, since the component is developed there.
