### ISSUE TITLE
Filter Bar: Resetting filter values in the Adapt Filters dialog

### ISSUE THREAD

**Issue by marekviskup** [SAP/ui5-webcomponents-react#5534]
### Is your feature request related to a problem?

Currently the **Reset** button in the **Adapt Filters** dialog only restores the filter selections and not the filter values. Ideally both these changes should be restored to the previous state as this is also the expected behavior described in the Fiori guidelines.

![Reset - Adapt Filters](https://github.com/SAP/ui5-webcomponents-react/assets/23099172/72c9d0d4-4908-43ae-be40-b1a5963e87b6)

### Describe the solution you'd like

Values of the filter controls should be restored to the previous state after applying **Reset** in the **Adapt Filters** dialog.
Fiori guidelines for the Reset functionality: https://experience.sap.com/fiori-design-web/filter-bar/#resetting-filters

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @marekviskup 

unfortunately we don't plan to support this behavior, in fact we plan to reduce copying references even more, or even remove it completely in our next major release. In React it's not common copying references of elements and especially for uncontrolled `children` it becomes tricky as we have to know how each child is handling its `value`, selection state (e.g. for `Select`), etc.
Moreover, most of the behavior becomes redundant when fully controlling the `FilterBar` and all its filters. Since this should be the case for most applications, in our opinion, it's better to remove implementations that are not typical for React, rather than implementing them just because the SAPUI5 control (which has a completely different technology stack) does it as well.

This [PR](https://github.com/SAP/ui5-webcomponents-react/pull/5536/) adds an example for resetting the values inside the dialog in the [With Logic](https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-filterbar--with-logic) example. So once it's merged you can check it out in our [nightly/next Storybook](https://sap.github.io/ui5-webcomponents-react/main/?path=/docs/layouts-floorplans-filterbar--docs) that is always reflecting our main branch (though it's not guaranteed to be stable) and once released in our standard Storybook as well.
