### ISSUE TITLE
Testing: Some Tests breaking when migrating from 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by Vasu-p** [SAP/ui5-webcomponents-react#555]
**Describe the bug**
I had some tests written which broke. The tests broke for two things. 
1. Clicking on `CustomListItem` item for `List` component
2. Clicking on the `ToggleButton` component for `SegmentedButton` component

They both have something in common
Whenever a child element is clicked the parent element's some `on*` method is called.

For List, I was using `onItemClick` method. for SegmentedButton I was using the `onSelectionChange` method. 
They work properly in the app itself, it's just the tests which doesn't call those parent on* handlers when i do something like
`fireEvent.click(child)`

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.11
Operating System: OS X

**Additional context**
I am using React testing library for testing.

**Comment by MarcusNotheis** [comment]
Hey @Vasu-p,

thanks for reporting! Could you share a snippet of your test code which is failing?

**Comment by Vasu-p** [comment]
Ok. Let me see if I can make it work. I tried creating it the first time around using the code sand box template but it was throwing some error. Do you happen to know any sandbox which had tests in them working?

**Comment by MarcusNotheis** [comment]
I think you should be able to use this template: https://codesandbox.io/s/ui5-webcomponents-react-template-29l34?file=/src/App.js

**Comment by Vasu-p** [comment]
https://codesandbox.io/s/hungry-chandrasekhar-xtp0j
please have a look here on App.js and App.test.js files. 
If you use the combo box in browser you would be able to see console logs in the action handler.
But when you run the tests we can't see the console logs.

**Comment by MarcusNotheis** [comment]
Hi @Vasu-p,

I think the root cause of this issue is a combination of the testing-library, jest and the custom elements (web components).
I tried to trace down the issue using this test: https://codesandbox.io/s/blissful-shirley-bkqxs?file=/src/WebComponents.test.js

The click on the top node (combo-box) works perfectly fine, but clicking on elements which are inside the shadowRoot (item) doesn't really work.

My assumption would be that these kind of tests can only be successful if they run in a real browser, using e.g. puppeteer, karma or cypress.

I'll try if I can run some tests using cypress.

**Comment by MarcusNotheis** [comment]
I was able to run a test using [cypress](https://www.cypress.io/), but it feels very hacky.
This was my test script:
```js
describe('select item in combo box', () => {
    it('selects an item', () => {

        cy.visit('/');

        const combobox = cy.findByTestId('combo').should(e => {
            const [dom] = e.get();
            dom.shadowRoot.querySelector('ui5-icon').click()
        });
        const callback = cy.spy();
        cy.document().then((doc) => {

            doc.querySelector('ui5-combobox').addEventListener('change', callback)

            doc.querySelector('ui5-static-area-item')
              .shadowRoot
              .querySelector('ui5-responsive-popover ui5-list ui5-li')
              .shadowRoot
              .querySelector('li')
              .click();
              expect(callback).to.be.called;
          });
    });
})
```

In my opinion the issue is that the `ui5-combobox` shows different items in it's popover than the items which are passed by the developers. Basically, the combo box takes all combo box items which are passed into it and re-creates them in a static area part - therefore we can't find that test-id anymore.

@vladitasev Please correct me if I'm wrong :) Any ideas on how to improve testing experience here?

**Comment by Vasu-p** [comment]
@MarcusNotheis thank you so much for that investigation. I was wondering what kind of testing strategy you guys have in your projects which make use of web components?

**Comment by MarcusNotheis** [comment]
Hey @Vasu-p,
I took a quick look in the test code of the UI5 Web Components themselves - they are using (webdriver.io)[https://webdriver.io/]. But the test code looks quite similar to the cypress code above:
https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/test/specs/MultiComboBox.spec.js#L60-L116

For the Web Components React themselves we are only running unit tests on our custom components and simply trust that UI5 Web Components are working as expected.

I hope this helps a bit.

@MapTo0 @ilhan007 any addition insights into testing web components?

**Comment by Vasu-p** [comment]
Thanks @MarcusNotheis . I eventually solved it by calling the handle manually like so:
`fireEvent.change(comboBox, { target: { filterValue: '' } });`
Thanks for all the help and investigation. It's really nice of you :)
