### ISSUE TITLE
[SplitterLayout]: When resizing second splitter element with bar for the first time, second splitter element size gets set to 0

### ISSUE THREAD

**Issue by sdommel** [SAP/ui5-webcomponents-react#5595]
### Describe the bug

We have a splitter layout with three splitter elements, creating two splitter bars for resizing.

If we try to resize the second splitter element by drag and dropping the second splitter bar for the first time, it does not matter where we are dropping the second splitter bar, the size of the second splitter element is set to 0 and both splitter bars are right next to each other afterwards.

When we afterwards drag the second splitter bar again it works as expected and the second splitter element keeps its size.

### Isolated Example

https://stackblitz.com/edit/github-pfjtom?file=src%2FApp.tsx

### Reproduction steps

1. On initial load all three splitter elements are visible
2. Drag and drop the second splitter bar
3. Second splitter element is hidden and both splitter bars are located next to each other

### Expected Behaviour

When dragging the second splitter bar, the position where the user drops the bar should determine the size of the splitter element.

### UI5 Web Components for React Version

1.26.0

### UI5 Web Components Version

1.23.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @sdommel 

setting a fixed width for SplitterElements, that is combined larger than the width of the SplitterLayout is not supported as even without the described behavior, UX would suffer as it would lead to inaccessible elements inside the component. Also, using only fixed sizes for the elements and not setting a `width` or `height` (depending on orientation) on the `SplitterLayout` is not recommended as well, because in this case the last element will initially not spread to the available space, but only take up the space defined by `size` and only when interacted uses the full available space.

[Here](https://stackblitz.com/edit/github-pfjtom-yp5qcq?file=src%2FApp.tsx) you can find an example of what I mean.

So my recommendation are: 
- setting a fixed width to the SplitterLayout (to be more responsive use different values for different screen sizes)
- use a more dynamic approach by using dynamic values for `size` (e.g. `%`, `auto`), please note that if you only use % values, you must ensure that all sections add up to 100% and that if you use mixed values, a section set to `auto` is recommended.
- depending on your use case, make use of the `minSize` prop

Does this work for you?

**Comment by sdommel** [comment]
Hello Lukas,

yes when we calculate all the correct SplitterLayout and Element sizes, then the resizing works as well.

Thanks

**Comment by Lukas742** [comment]
Great! Thanks for the update :)
