### ISSUE TITLE
[SF][Text]: external styles not working on Text components

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents-react#5599]
### Describe the bug

When we add css styles through `className`  property of Text component, the added styles are overridden by `Text` internal styles.

### Isolated Example

https://stackblitz.com/edit/github-fwkd41-detgpv

### Reproduction steps

1. Go to [stackblitz](https://stackblitz.com/edit/github-fwkd41-detgpv) exmaple.
2. Inspect the text element with styles added.
3. See the added styles are overridden by internal styles.

### Expected Behaviour

External styles should work properly on `Text` component.

### Screenshots or Videos

<img width="1664" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/27538066/97af4aef-a04c-4c98-a3f5-1ac6e674d485">

### UI5 Web Components for React Version

1.26.0

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @ksblklu 

many of our components are still using `react-jss` for styling. Since these sources are created after css modules, they have precedence. We're currently in the process of refactoring all components to use css modules, but since this has not a high priority for us and "base" components like `Text` need to be the last components to be updated, it's best if you use a selector with a higher specificity ([example](https://stackblitz.com/edit/github-fwkd41-hcpb6p?file=src%2FApp.module.css,src%2FApp.tsx,node_modules%2Fvite%2Fclient.d.ts)). 

Also please note that while we offer a way to overstyle components, internal styles are not subject to semantic versioning. So they can change without notice, which can lead to strange behavior when overstyling components without proper visual tests.

**Comment by ksblklu** [comment]
Hi @Lukas742 
Thanks for the information, I'll use higher priority selectors to override the component styles as temporary solution.

**Comment by Lukas742** [comment]
Great :) 

We'll keep the issue open until the `Text` is using css modules as well.

**Comment by Lukas742** [comment]
Hi @ksblklu 

with [v1.28.0](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.28.0), you can now more easily override internal styles of `@ui5/webcomponents-react` components. You can find more information about this [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-styling--docs#explicitly-import-css-bundles).

Please note, that if you're using Vite, to not import the static files inside the `main.tsx` file, as they would then be added last and therefore would override styles with the same specificity. [Example](https://stackblitz.com/edit/github-2estqu?file=src%2Fmain.tsx,src%2FApp.tsx,src%2FApp.module.css)
