### ISSUE TITLE
Is it possible to click SideNavigationList to expand instead of clicking the arrow

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#560]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there is a sub-SideNavigationList inside a SideNavigationList, you have to click the arrow, then the sub-SideNavigationList can be expanded. '
<img width="245" alt="Screen Shot 2020-06-05 at 2 37 47 PM" src="https://user-images.githubusercontent.com/5527455/83844805-3c4f6780-a73a-11ea-9e0f-4c1d8f919bfa.png">

**Describe the solution you'd like**
I'd like to have the functionality if user clicks the SideNavigationList itself, then the 
sub-SideNavigationList will expand.

**Comment by MarcusNotheis** [comment]
Hey @rkl1994,
I would like to keep the current behaviour as it is to be honest. Otherwise it will be difficult to say what should happen when the user clicks on "Sales" - should the app select the sales section then or just expand the panel?
I also doubled checked with the [UI5 Implementation](https://ui5.sap.com/#/entity/sap.tnt.SideNavigation/sample/sap.tnt.sample.SideNavigation) and it is behaving in the exact same way.

What I could offer you is the following:
I can add an imperative API to the onClick event of the `SideNavigation` component which allows you to expand the selected panel in the click handler by yourself. Would that work for you?

**Comment by rkl1994** [comment]
Hi MarcusNotheis,

I would appreciate it if there would be an imperative API to do this.

Thank you.

**Comment by MarcusNotheis** [comment]
Hey @rkl1994,

the pull request which is adding this functionality is now basically ready for being merged.
Now I have heard that the UI5 Web Components Team is now working in a SideNavigation component as well which will replace our SideNavigation within the next two or three weeks.
Is this issue blocking you currently? Then I would merge my PR. Otherwise I would suggest that we wait for the UI5 Web Components Side Navigation to be released to avoid some back and forth in the APIs.
What do you think?

Best regards,
Marcus

**Comment by rkl1994** [comment]
Hi MarcusNotheis, 

For me, if the 'SideNavigation' component provided by UI5 Web Components Team will be ready before August, I can wait for them. 
Otherwise, I would appreciate it if you can merge it. 
So I can wait for 2-3 weeks. Thank you!

**Comment by rkl1994** [comment]
Hi MarcusNotheis,

One more thing is that I found this issue about SideNavigation: [issue](https://github.com/SAP/ui5-webcomponents/issues/1871)
The example provided in this issue doesn't contain the behavior that 'click the SideNavigationList to expand instead of clicking the arrow'. So will the UI5 Webcomponents team will add the behavior I want.

Thank you.

**Comment by MarcusNotheis** [comment]
Hey @rkl1994,
I just double checked with the colleague who develops the UI5 Web Component and this feature is already built-in in the new component: 
> Hello @MarcusNotheis
> 
> Currently the desired behaviour can be implemented inside the application using `ui5-side-navigation`. Every `ui-side-navigation-item` has `expandable` and `expanded` properties. When a selection-change occurs in the `ui5-side-navigation`, in the event detail you can find the pressed item as well as a second parameter `isArrowClicked`. When it is true, it means that the user has pressed the arrow and the expanded attribute will be set to true. On the other hand, if it is false, the application can toggle the item instead of doing a navigation which is the desired behaviour.
> 
> I just tested it out and it works as expected:
> 
> ```js
> $0.addEventListener("ui5-selection-change", event => {
>     if (!event.detail.isArrowClicked) {
>         event.detail.item.expanded = !event.detail.item.expanded;
>     }
> });
> ```
Hence I'm closing this issue now, please don't hesitate to reopen the issue in case there is more to do on our side.
