### ISSUE TITLE
[StepInput] `ValueState.Error` is ignored

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#5629]
### Describe the bug

We have a `StepInput`, and we want it to only accept numbers >= 0. We therefore set `valueState='Error'` if the input is < 0.
However, this only works the first time I click on the 'Minus' button. Any subsequent clicks will reset the valuestate to 'None'.

### Reproduction steps
+ Open your linked [StackBlitz template](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx)
+ Replace `App.tsx` with the following:
```tsx
import React from 'react';
import { StepInput, ValueState } from '@ui5/webcomponents-react';
function App() {
  const [delay, setDelay] = React.useState(0);

  const getValueState = () => {
    if (delay < 0) {
      return ValueState.Error;
    }
    return ValueState.None;
  };
  return (
    <StepInput
      value={delay}
      onChange={(event) => {
        const _delay = event.target.value || 0;
        setDelay(_delay);
      }}
      valueState={getValueState()}
    />
  );
}

export default App;
```
+ Click on the 'Minus' button once => valueState === 'Error' => Good
+ Click on the 'Minus' button again => valueState === 'None' => Bad

### UI5 Web Components for React Version

1.26.0

### UI5 Web Components Version

1.23.1

### Browser

Chrome

**Comment by Lukas742** [comment]
Hi @ej612 

since v1.26.1 of `@ui5/webcomponents-react` (v1.23.0 of `@ui5/webcomponents`) the `StepInput` offers a `valueStateChange` event which is fired when the internal value-state has changed. Also, it allows preventing the default behavior (internal validation) of the web component by calling `event.preventDefault` in the handler.

I've prepared an example that shows how you could refactor your example depending on your use-case. In this case, using `preventDefault` will likely be the simplest solution.

https://stackblitz.com/edit/github-1xuemb?file=src%2FApp.tsx
