### ISSUE TITLE
Filter Bar: Selected items not cleared after change in Adapt Filters dialog

### ISSUE THREAD

**Issue by marekviskup** [SAP/ui5-webcomponents-react#5652]
### Describe the bug

After a change of a filter value in the Adapt Filters dialog, clearing the filter bar doesn't result in previously selected filter items being removed.

Clear works fine unless the filter values are changed via Adapt Filters dialog.

### Isolated Example

https://stackblitz.com/edit/github-rc93m5-rtmizd?file=src%2FFilterBarView.tsx

### Reproduction steps

1. Click on **Adapt Filters** button
2. Click on **Show Values** button
3. Select _Option 1_ for _Filter 1_
4. Select _Option 1_ for _Filter 2_
5. Click on **OK** button
6. Click on **Clear** button

### Expected Behaviour

Both filters are cleared -> all selected options are removed from the filter components.

### UI5 Web Components for React Version

1.26.1

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @marekviskup 

I investigated this issue already and unfortunately it turned out to be more complex than anticipated. We'll probably need a new concept for the `FilterBar` in general as our current approach isn't really how one would implement this component in React. We'll probably discuss the possible options next week and I'll let you know when there's an update.

**Comment by Lukas742** [comment]
Hi @marekviskup 

quick update:
Internally we're currently copying properties of the input elements, which is leading to this error you're describing. Unfortunately, this is not only leading to problems, but is also hard to maintain, since we have to adjust this implementation every time the (internal) implementation of a UI5 web component changes. 
Because of this, we've decided to drop this functionality with our v2.0 release, but we will also add a prop that makes it possible to disable this behavior for our 1.x version.
