### ISSUE TITLE
[SF][TextArea in Dialog]: Escape key handler in text area resets the value before closing the dialog

### ISSUE THREAD

**Issue by Ankitadoshi** [SAP/ui5-webcomponents-react#5705]
### Describe the bug

We have a requirement where we have a test area field in a dialog. On closing the dialog, We need to check if the textarea field is dirty and throw a confirmation popup if it is dirty so that the user can choose if they want to discard the changes.
However, The dialog gets closed by esc key and when the user is focused on the text are field inside the dialog and presses esc, the changes in text area field are also reverted and the dialog closes. There is no way of knowing if the field was dirty.
we see that the textArea has keydown implementation where on esc, it reverts back to previous value. 
Is there a way we can override thus? 

### Isolated Example

https://codesandbox.io/p/sandbox/falling-water-nlfg9n?file=%2Fsrc%2FApp.js%3A13%2C34

### Reproduction steps

1. Go to https://codesandbox.io/p/sandbox/falling-water-nlfg9n?file=%2Fsrc%2FApp.js%3A13%2C34
2. Click on Open dialog button
3. Make some changes to the text area field and click on close button
4. Open the dialog again and see that the value is retained.
5. Now make some change in the text area value and press esc without focusing out.

Observe that the value gets reverted in the text area and the dialog closes. so the changes are lost (this can be seen via console logs)

### Expected Behaviour

There should be a way to override the keydown handler in Text area so that the changes are not always reverted

### UI5 Web Components for React Version

^1.23.3

### UI5 Web Components Version

^1.20.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Ankitadoshi 

we moved to [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) as our preferred web IDE/sandbox as it's not possible anymore to edit codeSandboxes with a free plan.

___

The `keydown` event of the `TextArea` is bubbling up to the `Dialog`, to prevent this you can call `event.stopPropagation()` in the respective handler. [Example](https://stackblitz.com/edit/github-f9fc7s?file=src%2FApp.tsx)

Since this is the standard behavior of JS event delegation, I'm going to close this issue.
