### ISSUE TITLE
[ObjectPage]: support the DynamicSideContent component inside the ObjectPage component.

### ISSUE THREAD

**Issue by bomasap** [SAP/ui5-webcomponents-react#5789]
### Describe the bug

We currently need to add a side panel within the ObjectPage component. However, when the dynamicSideContent is added as content of the ObjectPage, there are no tab actions in the ObjectPage header.

### Isolated Example

[ObjectPage](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--docs)
[DynamicSideContent](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicsidecontent--docs)

### Reproduction steps

1. Add dynamicSideContent inside the ObjectPage component as content. 
2. Add some ObjectPageSection as dynamicSideContent Main content
3. The tabs are not displayed in the Object header area. 

### Expected Behaviour

The tab actions should be in the ObjectPage Header.

### Screenshots or Videos

<img width="1785" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/169193249/3e124c0e-0aa9-456f-b8d3-3aacacbe28c3">

### UI5 Web Components for React Version

1.27.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

sf

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @bomasap 

the ObjectPage only accepts children of type [ObjectPageSectionType](https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/components/ObjectPage/index.tsx#L51), so if you're using `DynamicSideContent` as direct child of the component this is not supported. Otherwise, please add a reproducible example by using this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template.

**Comment by bomasap** [comment]
Hi @Lukas742 

Here is StackBlitz and reproduce this issue. https://stackblitz.com/edit/github-zwueh7?file=src%2FApp.tsx

**Comment by bomasap** [comment]
Hi @Lukas742 
Thank you for confirming the current limitations of DynamicSideContent. Given this, I would like to proceed with submitting a feature request to explore the possibility of extending its capabilities to meet our needs. I appreciate any guidance on the best way to submit this request.

Additionally, if there are alternative approaches or workarounds that could temporarily fulfill our requirements, I would be grateful for any suggestions. Our goal is to integrate DynamicSideContent as a child of ObjectPage, and any advice on how we might achieve this, even indirectly, would be very helpful.

![image](https://github.com/SAP/ui5-webcomponents-react/assets/169193249/c982f451-b9e1-4b75-a855-403ee7c8cbd1)

**Comment by Lukas742** [comment]
Hi @bomasap 

I couldn't find any specifications for this in our UX or accessibility guidelines. Additionally, supporting this feature would require a complete refactoring of the ObjectPage. Therefore, we unfortunately have to decline this feature request. 

If there are existing specifications for a11y, UX, or design, please guide me to the relevant resources (Please contact me internally if this is the case). Otherwise, consider submitting a request to the central design team and provide the Jira ID here. Should this topic be approved and specifications become available, we will reassess this request.

In my opinion, your best option to get this delivered timely is implementing it yourself though. You can probably use the `DynamicPage` with a [sticky](https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-dynamicpage--sticky-sub-headers) `TabContainer` as subheader and then define the desired content and scroll behavior yourself.
