### ISSUE TITLE
[Popover]: [Anything which comes under the Label component is not read by the screen reader also the focus is not set to the Label message.][Component Name]: [Bug Description]

### ISSUE THREAD

**Issue by sanjayC5373903** [SAP/ui5-webcomponents-react#5862]
### Describe the bug

 return (
    <>
      <Button    
        data-testid={`popoverBtn-${testid}`}        
        style={{ marginLeft: '0.5em' }}
        id={'openPopoverBtn'}
        icon="hint"
        design="Transparent"
        accessibleName={labelToolTip}
        tooltip={labelToolTip}
        onClick={handleButtonClick}
        onKeyDown={handleButtonKeyDown}
      />
      {createPortal(
        <Popover
          data-testid="iconPopoverBtn"
          id="iconPopoverBtn"
          verticalAlign="Bottom"
          initialFocus="iconPopoverBtn"
          ref={popoverRef}
          placementType="Right"
          onFocus={e => e.stopPropagation()}
          accessibleName={labelToolTip}
        >
          <Label data-testid="popOverLabelMessage">{message}</Label>
        </Popover>,
        document.body,
      )}
    </>
  );

### Isolated Example
--
### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

0.27.5

### UI5 Web Components Version

1.6.0

### Browser

Chrome

### Operating System

Windows11

### Additional Context

--

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by sanjayC5373903** [comment]
Hi @MarcusNotheis  
I prefer by using this template. added our code. https://stackblitz.com/edit/github-fl3jjf?file=src%2FApp.tsx,tsconfig.json
After pressing enter it is not reading the popover text even for the newer Version . it is reading only the btn-name ( info)

<img width="949" alt="MicrosoftTeams-image (1)" src="https://github.com/SAP/ui5-webcomponents-react/assets/170628934/2ffd315b-5905-44db-bf23-74c4a2ea3982">

I want the popover text to be read out by jaws when user clicks on the button

**Comment by Lukas742** [comment]
Hi @sanjayC5373903 

I don't have access to JAWS, so I wasn't able to test it with it but for Apple Voice Over and NVDA removing the `initialFocus` prop did fix the issue for me. Since the popover itself is not interactive, you shouldn't set the initial focus to it as only interactive elements are focusable. 

Here you can find the example that returned correct announcements for me: https://stackblitz.com/edit/github-fl3jjf-qnjwxj?file=src%2FApp.tsx,tsconfig.json

If you're still facing this issue with JAWS, or have additional questions regarding screen reader support of the `Popover` please let us know. We will then forward this issue to the [ui5-webcomponents repo](https://github.com/SAP/ui5-webcomponents), since the component is developed there.
