### ISSUE TITLE
[Button][MessageBox]: Button focus outline is different compared to previous version of UI5WC

### ISSUE THREAD

**Issue by tapanprakasht** [SAP/ui5-webcomponents-react#5872]
### Describe the bug

Button focus outline is different compared to previous version of UI5WC.

**UI5WC 1.14.0 version has white dotted line** 
![ui5_1_14_0](https://github.com/SAP/ui5-webcomponents-react/assets/4947384/ea53e2ab-d4e7-46e1-8184-6d2bd708ca2b)

After upgrading to **UI5WC 1.23.3 version, it has black solid line** 

![ui5_1_23_3](https://github.com/SAP/ui5-webcomponents-react/assets/4947384/74c798c7-0be7-4dc0-bd6e-831f1b66d299)

### Reproduction steps

Sample app created in codesandbox and shared below

**Ui5WC-1.23.3** -> https://codesandbox.io/p/sandbox/ui5wc-1-23-3-4xskyj
**Ui5WC-1.14.0** ->  https://codesandbox.io/p/sandbox/ui5wc-1-14-0-5j5l89

### UI5 Web Components for React Version

1.26.2

### UI5 Web Components Version

1.23.3

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by shubhamnazare** [comment]
Hi @Lukas742 & @ilhan007

This issue is still reproducible with `ui5/webcomponents: 1.24.8` and `ui5/webcomponents-react: 1.29.6`. The border is while solid instead of white dotted. Could you please validate from your side and confirm the same?

Thanks!

**Comment by Lukas742** [comment]
Hi @shubhamnazare 

since this is a duplicate, please raise this bug in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/8480).
Also, I've [checked](https://stackblitz.com/edit/github-hwvxh9?file=package.json,index.html) the behavior and it seems like the border is dotted, but not white. 

You can link the example in the original issue as well. https://stackblitz.com/edit/github-hwvxh9?file=package.json,index.html

**Comment by shubhamnazare** [comment]
Hi @Lukas742 

Thanks for the quick response!
Could you please try with `ui5-webcomponents-react`? Since our project uses `ui5-webcomponents-react` and the sandbox example is also in React, maybe the issue could be with `ui5-webcomponents-react`. If yes, then we can continue the conversation here because the original issue is in ui5-webcomponents repository.

**Comment by shubhamnazare** [comment]
@Lukas742 Could you please let me know what am I doing wrong here? - https://stackblitz.com/edit/vitejs-vite-sscnqt?file=src%2FApp.jsx

I have the correct versions yet I still see the issue.

**Comment by Lukas742** [comment]
You're using a different theme (Horizon or `sap_horizon`) and there the focus outline is implemented like that by design. The issue is about the deprecated Belize (`sap_belize`) theme.

**Comment by shubhamnazare** [comment]
@Lukas742 Thanks for pointing out! I had no idea about the themes.

Regarding the color being still black, should I create a new issue or will you continue to use the [original issue](https://github.com/SAP/ui5-webcomponents/issues/8480)?

**Comment by Lukas742** [comment]
No problem :)

If you don't use the Belize theme then I don't think it's necessary to report this as Belize is deprecated anyway and isn't even available anymore in v2.

**Comment by shubhamnazare** [comment]
Hi @Lukas742

Does this mean that there will be no future support with belize theme in 1.x series?

**Comment by Lukas742** [comment]
Hi @shubhamnazare 

no, the Belize theme is still supported by v1. It was only removed in v2.

**Comment by shubhamnazare** [comment]
Hi @Lukas742

After our team's internal discussion, we wish to have border dotted and white just like before. Should I create another issue or shall we re-open the existing one?

**Comment by Lukas742** [comment]
Hi @shubhamnazare 
if you want to see this fixed for the Belize theme, then please open an issue in the [ui5-webcomponents repo](https://github.com/SAP/ui5-webcomponents) since the `Button` is developed there. Please keep in mind that the support for version 1 will be discontinued by the end of the year. You can use this example: https://stackblitz.com/edit/github-jz3rcw?file=index.html

For other themes the border is implemented by design and therefore isn't planned to be changed.
