### ISSUE TITLE
FilterBar: filterfields width does not get adjusted to screen width and empty space is seen in the remaining area

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents-react#5890]
### Describe the bug

UX designers have reecommended that the filter items width should get adjusted to diferrent small screen size.

### Reproduction steps

1. go to https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-filterbar--default&args=hideFilterConfiguration:!false;hideToggleFiltersButton:!true;hideToolbar:!false;showRestoreOnFB:!false;showResetButton:!false;showGoOnFB:!true;showClearOnFB:!false&globals=viewport:mobile2
2. there is empty space seen on the right of the filter fields. Highlighted in yellow box in the attached screenshot

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/90389521/df917bc2-3633-47c8-a539-24394a82c9d1)

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @pppwr7 

sorry for the late reply. I've checked with our design specifications and the current implementation is intended. Only if `hideToolbar={true}` is used, the filters should expand to the available width. Also, if used on mobile, the filters are only accessible via the filters dialog (screenshot 1 & 2) and there they are shown in a list that takes up the whole screen size. 

If you want to stretch the filters to the whole screen width for some resolutions, you could achieve that with the `filterContainerWidth` prop. E.g. setting it to `100%`.

I've also checked how [SAPUI5](https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.filterbar.FilterBar/sample/sap.ui.comp.sample.filterbar.DynamicPageListReport/code) is implementing this and there the behavior is the same (`useToolbar: true`). (screenshot 3)

screenshot 1 & 2:
<img width="367" alt="image" src="https://github.com/user-attachments/assets/664ff83b-efcb-44e7-9422-2057e0186097">
<img width="425" alt="image" src="https://github.com/user-attachments/assets/ed4ee366-2c6d-4432-9f8d-326164460644">


screenshot 3:
<img width="381" alt="image" src="https://github.com/user-attachments/assets/986d9669-e909-4d54-a4da-efe5e26054f6">

Since the behavior is intended and full width filters can also be achieved via `filterContainerWidth`, I'm going to close this issue.
