### ISSUE TITLE
Menu: ACC read as button

### ISSUE THREAD

**Issue by surjadeep** [SAP/ui5-webcomponents-react#5918]
### Describe the bug

 The type of menu component is read as button.

### Isolated Example

https://stackblitz.com/edit/vitejs-vite-vykgzp?file=src%2FApp.tsx

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Type of the input should be read properly.

### UI5 Web Components for React Version

1.28.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

CBC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @surjadeep 

this is the exact same question I already answered on [Slack](https://openui5.slack.com/archives/CSQEJ2J04/p1718181669253339). Is there something unclear, or do you need further assistance? In general, please keep it in one channel, because creating the same issue in multiple instances makes support harder than it needs to be.

> you can use the accessibilityAttributes to achieve this. (see [docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-button--docs#attributes---methods))
https://stackblitz.com/edit/vitejs-vite-xsy2rf?file=src%2FApp.tsx

Also, I've adjusted the title because this issue is not about the menu, but about the a11y attributes of the button.

I'm closing this issue now, if there are still questions or feedback, please add them here as we also monitor closed issues.
