### ISSUE TITLE
MessageView: item is truncated in dialog and doesn't allow switching to details view

### ISSUE THREAD

**Issue by lochannimje** [SAP/ui5-webcomponents-react#5990]
### Describe the bug

In Safari browser, information/error message is not showing fully, In other browsers, able to see the complete message. The issue is there in web component itself. Kindly do help us here!
<img width="340" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/65588981/76969b19-f185-40ca-9b46-87a90b29c466">
![image](https://github.com/SAP/ui5-webcomponents-react/assets/65588981/8bfe4591-a11a-487a-8576-9d5b6223b944)

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

It should show the complete message, or the message should go in next line with scrollbar provided.

### Screenshots or Videos

<img width="340" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/65588981/76969b19-f185-40ca-9b46-87a90b29c466">

![image](https://github.com/SAP/ui5-webcomponents-react/assets/65588981/8bfe4591-a11a-487a-8576-9d5b6223b944)

### UI5 Web Components for React Version

1.16.3

### UI5 Web Components Version

1.14.0

### Browser

Safari

### Operating System

ios

### Organization

SAP Labs Ltd, Bengaluru

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @lochannimje 

Please follow the guidelines for opening issues. "[Component Name]: [Bug Description]" doesn't give information of the affected component and neither of what the issue is about.

Also, please add a reproducible example, preferably by using this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template.

**Comment by lochannimje** [comment]
Hi @Lukas742 
please click the link: https://sap.github.io/ui5-webcomponents-react/?path=/story/user-feedback-messageview--message-view-in-dialog
and then click on Open Dialog 

<img width="514" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/65588981/6422d96d-6e23-4534-94b4-d8cfa7452adb">

you can see the highlighted message, it is not showing fully, can see dots there.
Expected behaviour: It can show the message fully.

**Comment by Lukas742** [comment]
This is not related to the `MessageView` but the Dialog as it has a `width` of `400px` defined in our example. The linked PR will adjust this. 
So, in your application you can adjust the behavior of the Dialog to your use-case.

**Comment by lochannimje** [comment]
The above issue comes in Safari browser, for other browser it is working as expected. Please me over here!!

**Comment by Lukas742** [comment]
Hi @lochannimje 

maybe Safari makes the text a bit bolder, or calculates the dimension of the font somehow differently, but the root cause of this is still the same (at least in our Storybook).
We're setting a `width` (only in our documentation, __not__ in the component itself) of `400px` and since the text is longer than that, it gets truncated.  
In your application, it's up to you to decide what dimensions you want to use for the Dialog.

https://github.com/SAP/ui5-webcomponents-react/assets/9749730/8071447a-ac8b-443e-9421-a025960280e5

If there's a different issue with the component, please add a reproducible example.

**Comment by pppwr7** [comment]
Hi [Lukas742](https://github.com/Lukas742),
I see that the Title control is used to display the text in the MessageView in https://github.com/SAP/ui5-webcomponents-react/pull/5993/files. Can't we set the 'wrappingType' property to 'Normal' in the Title control? This could solve the issue for us.

**Comment by Lukas742** [comment]
Hi @pppwr7 

unfortunately not, since this behavior is by design. You can see the same behavior in the SAPUI5 implementation (just change one of the titles to a very long one). Titles should be short and meaningful, for further information you can use the detail view.

In case you want to open a feature request for the wrapping behavior, please first open a ticket in central design and include the ID in the feature request.

**Comment by pppwr7** [comment]
Hi @pppwr7,
In the  SAPUI5 implementation,  they have feature to enable navigation icon for long text, on click of which one can view the full text in details page.
![image](https://github.com/SAP/ui5-webcomponents-react/assets/90389521/c1daa266-feda-4edc-aa95-2ef0ea5d1b6c)

**Comment by Lukas742** [comment]
Hi @pppwr7 

I couldn't find this behavior in the specs, but as it makes sense in my opinion and to be consistent with the SAPUI5 implementation, we decided to include this as well. The linked [PR](https://github.com/SAP/ui5-webcomponents-react/pull/6015) will fix this.

**Comment by lochannimje** [comment]
Hi @Lukas742,
May I know the release version for the above changes.
