### ISSUE TITLE
[RadioButton]: [When we navigate to the Radio Button using arrow keys (Left, Right, Top & Bottom) on AnalyticalTable and when we try to select the Radio Button by pressing Space, Enter and F2 we are unable to select it]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents-react#6041]
### Describe the bug

When we navigate to the Radio Button using arrow keys (Left, Right, Top & Bottom) on AnalyticalTable and when we try to select the Radio Button by pressing Space, Enter and F2 we are unable to select it.

I am attaching a video for your better understanding.

https://github.com/SAP/ui5-webcomponents-react/assets/66779051/6e3fe640-31fa-414a-9384-47e08e701160

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

When we navigate to the Radio Button using arrow keys (Left, Right, Top & Bottom) and once we reach to the radio button and try to select radio button by pressing Space, Enter and F2 we must select the radio button.

<img width="599" alt="mark radio button" src="https://github.com/SAP/ui5-webcomponents-react/assets/66779051/543c6f5a-5cd7-423f-9895-cc87f7894941">

### UI5 Web Components for React Version

0.27.5

### UI5 Web Components Version

1.6.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @jadhavarjun 

currently, it's only possible to focus on custom interactive elements inside a cell by pressing Tab. Although our `AnalyticalTable` doesn't offer an edit mode out of the box, I believe it should still be possible to 'enter' the cell and focus on the interactive content by pressing F2.

We'll most probably need a new concept for this, so we'll treat this issue as feature request. 

Since we're currently very busy with preparing our 2.0 release, it may take some time before we can work on this feature. If you need this urgently, it's likely possible to create a custom plugin hook to achieve it. In that case, please provide a detailed description of the desired behavior. I can then check if it's feasible to implement as a plugin hook.

**Comment by jadhavarjun** [comment]
As of now i am closing this issue in future if I need   help I will raise issue.
