### ISSUE TITLE
There is no document about Internationalization

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents-react#605]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Description of the issue**
There should be documentation about how to configure message bundle assets and how to internationalize an app.
I know the base repository has relative docs. Could you kindly organize these documents and give some references?

**BTW**
I imported all assets files I can found, but I still got a few message bundle errors.
![image](https://user-images.githubusercontent.com/4338219/87651697-cd781c00-c785-11ea-8ea1-586bd8c181b2.png)

Can you give me some instructions?

**Comment by MarcusNotheis** [comment]
Hey @SunnyWind,

which version of the UI5 Web Components React are you currently using?
`i18n` is unfortunately broken in the `0.9.x` releases but fixed starting with `0.10.0-rc.2`.
When using the `0.10.x` versions, `i18n` for all components should work fine.

What I have on my list for our documentation is now: 
1. document the required import statement (`import '@ui5/webcomponents-react/dist/Assets';`)
2. Reference to the UI5 Web Components i18n documentation
3. Describe additional steps on top of the ui5 documentation which are required for adding custom i18n translations

Do you have anything to add to this list?

**Comment by SunnyWind** [comment]
Hi @MarcusNotheis ,

Thanks for your feedback.

I'm using 0.9.x version.
Looking forward to the stable version of 0.10.x.

It would be great if you can explain the part of [Efficient asset bundling](https://sap.github.io/ui5-webcomponents/playground/docs/assets/) in the document. Personally, this document doesn't explain this behaviour well.

Regards

**Comment by MarcusNotheis** [comment]
Thanks for the input.

I've now prepared [this document](https://github.com/SAP/ui5-webcomponents-react/blob/docs/i18n/docs/5-Internationalization.stories.mdx). Is this what you would have expected? (please note that the custom translations chapter is not working yet as we need to wait for the release of `@ui5/webcomponents@1.0.0-rc.8`).

Regarding the Efficient Asset Bundling: Unfortunately that topic is not very easy because you will have to eject your react-app in order to change the bundling behaviour. Anyhow, I'll try to make a documentation for that as well.

**Comment by MarcusNotheis** [comment]
And here's the documentation for the bundling: https://github.com/SAP/ui5-webcomponents-react/blob/docs/i18n/docs/6-Efficient-Bundling.stories.mdx

Pull request is open and will be released as part of `0.10.0`.
