### ISSUE TITLE
AnalyticalTable: Filtering in tree table

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#621]
**Describe the bug**
Filtering looks a bit buggy for tree data. Multiple bugs?

**Isolated Example**
https://codesandbox.io/s/crimson-breeze-lhbmu?file=/src/App.js
**To Reproduce**
1) filtering for children data shows no data
- add a filter for column 1 or 2 with value "6" in the first table
=> result: no data is shown. Expected to see the row with id 6 in tree form e.g. the parent still exists there
- removing the filter shows the original data => this is good

2) filtering for a parent removes children when clearing the filter
- add a filter for column 1 or 2 with value "1" in the first table
- removing the filter shows the original data but no children exist under parent 1 => bug?

3) filtering on column with a custom Cell value provides no way of filtering on what is shown to user
- add a filter for column 1 with value "t" in the second table
=> no data is shown. Is this what the `filter` prop is for on the [AnalyticalTableColumnDefinition.ts](https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/main/src/interfaces/AnalyticalTableColumnDefinition.ts) interface is for? 

**Expected behavior**
explained above

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.11
Operating System: windows
Browser: edge (chromium)

**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @stevetsanders,

yes, I think here are a couple of issues :) 

First of all let me start with point 3, filtering on custom cell values.
Yes, this is exactly what the `filter` prop in a column is for. You can add a function here that will be used as filter function with the signature `(row, cellId, filterValue)` that should return a boolean.
You can find an example in the [react-table examples](https://react-table.tanstack.com/docs/examples/filtering)

The second issue (removing children from parent after filtering) seems to be a bug in react-table. I've already created an issue on the react-table repo some time ago: https://github.com/tannerlinsley/react-table/issues/2309

The first issue seems to be a shortcoming of react-table as well, but as far as I have understood the issue this will not be fixed in the current version but in the upcoming version of react-table. https://github.com/tannerlinsley/react-table/issues/2064

Best regards,
Marcus

**Comment by MarcusNotheis** [comment]
Hey @stevetsanders, 
the author of the react-table library just closed both issues as they are not fixable in the current version of react-table. As soon as his v8 is ready (which will fix the filtering issues) we'll upgrade.
I'm closing this issue for now, please feel free to reopen in case you think there is more to on side.
