### ISSUE TITLE
Expose type ListSelectionChangeEventDetail

### ISSUE THREAD

**Issue by Nils-Schiwek** [SAP/ui5-webcomponents-react#6224]
### Is your feature request related to a problem?

I want to add an event-handler function to the onSelectionChange prop of a List. The TypeScript signature of the List wants me to use a function `ListPropTypes.onSelectionChange?: (event: Ui5CustomEvent<ListDomRef, ListSelectionChangeEventDetail>) => void` 
While Ui5CustomEvent and ListDomRef are exported correctly, I am not able to use ListSelectionChangeEventDetail

```typescript
            <List onSelectionChange={handleSelect} mode="SingleSelect">
              {filteredList.map((text, id) => {
                return <StandardListItem key={id}>{text}</StandardListItem>;
              })}
            </List>

const handleSelect = (event: Ui5CustomEvent<ListDomRef, ListSelectionChangeEventDetail>): void => {
    const text = event.detail.selectedItems[0]?.textContent;
    setText(text);
};
```

When I try to import ListSelectionChangeEventDetail, I get the error message: `Module '"@ui5/webcomponents-react"' has no exported member 'ListSelectionChangeEventDetail'.ts(2305)`

I would like to be able to import `ListSelectionChangeEventDetail` from '@ui5/webcomponents-react' without errors.

### Describe the solution you'd like

I would like to be able to import `ListSelectionChangeEventDetail` from '@ui5/webcomponents-react' without errors.

### Describe alternatives you've considered

I am able to import from 

`import { ListSelectionChangeEventDetail } from '@ui5/webcomponents/dist/List.js';`

But the standard config is not picking it up.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Nils-Schiwek 

we recommend handlers by leveraging the TypeScript ["Lookup" or "Indexed Accessed"](https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html) types. This way you don't need to import each "DomRef", "detail" and "UI5CustomEvent" type.

E.g.:
```
const handleSelectionChange: ListPropTypes['onSelectionChange'] = (e) => {
```

https://stackblitz.com/edit/github-nnjjki?file=src%2FApp.tsx

Previously, we proxied some types and enums, but this meant only more maintenance on our end, so we've decided to drop this with our v2. That's why we don't plan to implement proxies for ui5wc `detail` interfaces.
