### ISSUE TITLE
[FilterBar]: Support enter key to trigger search

### ISSUE THREAD

**Issue by saurabhmehta02** [SAP/ui5-webcomponents-react#6280]
### Is your feature request related to a problem?

If we are using the component in the FilterBar or as search property (search={}), the search should be triggered when the user presses the Enter key.
This is also mentioned in the fiori guidelines - https://experience.sap.com/fiori-design-web/filter-bar/
"In the manual update mode, the search results are updated only when the users click Go or press Enter on their keyboard."

Currently the FilterBar component doesn't trigger search when user presses enter key.
We have some key customers complaining about this behavior. Kindly look into this request.

### Describe the solution you'd like

When user presses enter key, "onGo" event should get triggered.

### Organization

SAP Labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @saurabhmehta02 

since developers have full control over the `search` component that is passed to the FilterBar, this behavior is already possible, but has to be implemented on app side, as we don't have a dedicated "manual" or "live" mode.

Also, not only the search field should be submitted when pressing enter in the manual update mode, but all other `Input` components as well.

I've created a small example showing two options of how this could be achieved: https://stackblitz.com/edit/github-6rkos5?file=src%2FFilterBarKeyDownSubmit.tsx,src%2FApp.tsx,src%2FFilterBarFormSubmit.tsx
