### ISSUE TITLE
[DynamicPageTitle]: React elements from actions prop re-render on browser resize

### ISSUE THREAD

**Issue by stanleychh** [SAP/ui5-webcomponents-react#6327]
### Describe the bug

**Issue:** When resizing the browser window, all React elements passed through the actions prop are being re-rendered unexpectedly. This behavior is causing performance issues or unintended side effects during resizing.
```
<DynamicPageTitle 
   actions=[<Component1>, <Component2>, <Component3> ]
    ....
/>
```

### Isolated Example

https://stackblitz.com/edit/github-edkpyt?file=src%2FApp.tsx

### Reproduction steps

1. Create a `DynamicPage` component with a `DynamicPageTitle` sub component
2. Pass a stateless component to actions prop, also add log when component got rendered
3. Resizing the browser and observe the logging.

### Expected Behaviour

If the component itself doesn't change, there is no need to re-render.
This cause performance issue when there are a lot of React elements pass as the prop

### UI5 Web Components for React Version

1.29.9

### UI5 Web Components Version

1.24.8

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

MAC

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @stanleychh

React’s reconciliation process is optimized. For example, React compares the previous and next state of the DOM and only updates the parts that have actually changed, even though the components may be rerendered. Additionally, triggering an update when resizing is most probably necessary for the overflow behavior. There might be a better way to implement this, but since the v1 (React only) `Toolbar` is deprecated, we are prioritizing other topics.

That's why I’m closing this issue for now. However, if you notice any real performance issues that could affect users, feel free to reopen it.
