### ISSUE TITLE
Form: different label arrangement depending on the selected theme

### ISSUE THREAD

**Issue by saynesy** [SAP/ui5-webcomponents-react#6340]
### Describe the bug

Depending on the selected theme, the position of the label changes, which makes the **labelSpan** property in Form non-functional.

I've noticed that for some themes, the **--ui5-v2-1-2-form-item-layout** CSS variable is not defined which may lead to such a problem.

### Isolated Example

https://stackblitz.com/edit/github-jewrmx?file=src%2FApp.tsx

### Expected Behaviour

Have the same layout of items inside the form according to the given **layout** and **labelSpan** props in all themes.

### UI5 Web Components for React Version

2.0.2

### UI5 Web Components Version

2.1.2

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @saynesy,
thanks for reporting! I think this issue has already been fixed by the UI5 Web Components Team in https://github.com/SAP/ui5-webcomponents/pull/9800, but as far as I know this fix has not been released yet.
I'll keep the issue open until the UI5 Web Components will ship their next release.
