### ISSUE TITLE
ProgressIndicator: Progress bar's semantic color is wrong in [Horizon High Contrast Dark Theme]

### ISSUE THREAD

**Issue by Xidai** [SAP/ui5-webcomponents-react#6412]
### Describe the bug

In Horizon High Contrast Dark theme, the semantic colors stay unchanged when I change the valueState. The screenshots below are taken from documentation v2, and the issue occurs in both v1 and v2. 

valueState="Positive":
<img width="672" alt="image" src="https://github.com/user-attachments/assets/aa10617a-82b1-4aa5-b4ee-fde43f7b7602">

valueState="Negative":
<img width="453" alt="image" src="https://github.com/user-attachments/assets/80b6f93a-dc03-464b-90f3-93fd9a378382">

valueState="Critical":
<img width="486" alt="image" src="https://github.com/user-attachments/assets/e770c29c-8b7e-4a77-a5fd-1385f103d726">

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

2.1.1 and v1

### UI5 Web Components Version

~2.2.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Xidai 

this is by design, you can see the same behavior for most components implementing semantic colors. Also, SAPUI5 implements these colors in the same way. (e.g. SAPUI5 [ProgressInicator](https://sapui5.hana.ondemand.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.m.sample.ProgressIndicator&sap-ui-xx-sample-lib=sap.m&sap-ui-xx-sample-origin=.&sap-ui-xx-dk-origin=https%3A%2F%2Fsapui5.hana.ondemand.com&sap-ui-theme=sap_horizon_hcb&sap-ui-rtl=false&sap-ui-density=sapUiSizeCompact))
