### ISSUE TITLE
[ObjectStatus]: role set to 'link' but screen-reader description read out as button

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents-react#6437]
### Describe the bug

We have a situation where the `ObjectStatusInvisibleDescriptionContainer` is labeled as "Object Status Button" because it has `active` property set. However, since we use this object status as a link that opens a page, we want to remove "button" from the value of `ObjectStatusInvisibleDescriptionContainer`. Please help us make this change.

### Isolated Example

https://stackblitz.com/edit/github-gm162t?file=src%2FApp.tsx

### Reproduction steps

Can be found in the StackBlitz example linked above

### Expected Behaviour

The issue is that `role` is set to `link` since the url opens in a new tab on click. However, the accessible name says `button` since `active` property is set. This is contradicting and misleading to screen reader users. So please provide a way to add "link" instead of "button" in the `ObjectStatusInvisibleDescriptionContainer` value.

### UI5 Web Components for React Version

1.29.10

### UI5 Web Components Version

1.24.6

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by rama1990br** [comment]
<img width="1727" alt="Screenshot 2024-10-02 at 5 32 55 PM" src="https://github.com/user-attachments/assets/e4abd4c0-6b4c-4e6b-ba8c-53c8964964d2">

**Comment by Lukas742** [comment]
Hi @rama1990br 
there are no specifications for the `ObjectStatus` component to be treated as a link. According to the current specifications, it should either be a `button` (`active={true}`) or a `div` with `role="group"`.

To implement this change, the request would need to go through the Inner Source process and be aligned with the SAP Central Design team first. If you're a SAP employee, please raise a BLI with the central design team and include the ticket number here for reference. Feel free to contact me internally if you need the current specifications or guidance on how to create a BLI for the central design team.
If you're not a SAP employee, then please provide these informations so I can forward them to the design team:

- Stakeholder (optional)
- Comprehensive description of the use-case.
  - Why is this feature needed?
  - Who are the users (type of user, persona)
  - User Story (As a [user], I want [action] so that [value].)
- Are there any alternatives you've considered? If so, why aren't they sufficient?
