### ISSUE TITLE
AnalyticalTable: Scroll position not maintained on growing table with groupBy and infiniteScrolling enabled

### ISSUE THREAD

**Issue by fushizen** [SAP/ui5-webcomponents-react#6439]
### Describe the bug

On using an Analytical Table with `infiniteScrolling` and `groupBy` enabled, on scroll to load more data, the scroll position jumps back to the top of the table

### Isolated Example

https://stackblitz.com/edit/ui5wcr-at-bvsfmh?file=src%2FApp.tsx

### Reproduction steps

1. Open the sandbox
2. Scroll to the end of the grouped table
3. Scroll position jumps to the top of the table on load of more data

### Expected Behaviour

On scroll to load more data, scroll position should remain stationary on the page.

### UI5 Web Components for React Version

~1.29.11

### UI5 Web Components Version

~1.24.10

### Browser

Chrome, Edge, Firefox

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @fushizen 

this behavior occurs because of two reasons:

1. The table is programmatically expanding all rows, when the data is fetched, this internal table state is reset per default and that's why the table is scrolling to the top. To prevent this you can use `autoResetExpanded: false`.
2. Different to "normal" tables, a grouped table does add new rows not necessarily at the end of the previous rows and therefore even with `autoResetExpanded: false` the scroll position can be off. Unfortunately, this is one of the reasons we don't recommend using grouping in combination with infinite scrolling. Some other limitations can be found in this [PR](https://github.com/SAP/ui5-webcomponents-react/pull/6431), where we, i.a., outline this limitation more prominently.

When loading new data, you can try updating the scroll position yourself, by leveraging the `scrollTo` or `scrollToItem` method. ([docs](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/data-display-analyticaltable-recipes--docs#how-to-scroll-to-a-specific-rowoffset))

As there is unfortunately no design concept for this behavior and grouping was even deprecated for the SAPUI5 table, I'm going to close this issue now. If you have additional questions or feedback, please feel free to still post them here, as we also monitor closed issues.
