### ISSUE TITLE
[DynamicPage]: Icon is hidden in page header

### ISSUE THREAD

**Issue by hxempty** [SAP/ui5-webcomponents-react#6469]
### Describe the bug

Refresh page ,share icon is hidden when I adjust the width of page.

### Reproduction steps

1.When I adjust page width,we can see the page is normal.
![image](https://github.com/user-attachments/assets/37d41709-287d-4db3-9f66-ff384e331514)

2.Refresh the page ,we can see that share icon is hidden in the header. In the case ,the page width is about 960px.
![image](https://github.com/user-attachments/assets/989ce47e-65bb-4026-bf16-b27d50f1653b)

You can try the enviroment 
removed

### UI5 Web Components for React Version

1.26.1

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @hxempty, this is a public repo, so internal links shouldn't be posted here, even if they're inaccessible. I’ve removed the link.  
Please follow our issue template and provide an isolated, reproducible example of the issue. If the issue can't be reproduced outside of your setup, we can take a look at your application. The reason is that debugging an existing app with all its overhead is much more time-consuming for us and usually doesn't offer any advantage over an isolated example.
