### ISSUE TITLE
AnalyticalTable: Multiple a11y issues with the row expansion button in analytical tree table

### ISSUE THREAD

**Issue by fushizen** [SAP/ui5-webcomponents-react#6516]
### Describe the bug

Using axe devtools (a plugin used by the internal A11y team to check for issues) In the analytical tree table, the indicator to expand the tree table row has 2 critical a11y issues:

1. On expanding the row, there is the issue `ARIA attribute is not allowed: aria-expanded="true"`

![image](https://github.com/user-attachments/assets/6c5169d1-4980-4146-8167-c635a723efa1)

3. The row expansion button has the issue `Ensure buttons have discernible text`

![image](https://github.com/user-attachments/assets/351a57a0-55f4-4d77-a8a6-f05130c7fbcb)

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/v1/?path=/story/data-display-analyticaltable--tree-table

### Reproduction steps

1. Go to the storybook for analytical table - tree table
2. Open axe devtools in dev console
3. Described issues are present

### Expected Behaviour

Component to not have a11y issues detectable by the tool

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/c850b4ba-2675-462d-9d55-ddc0128f40c7)

![image](https://github.com/user-attachments/assets/0b09ad98-cfb5-426d-9797-bbf5548374e0)

### UI5 Web Components for React Version

1.24.x

### UI5 Web Components Version

1.24.x

### Browser

Edge

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @fushizen 

> On expanding the row, there is the issue ARIA attribute is not allowed: aria-expanded="true"

This attribute is redundant, but since the button (inside the `span`) isn't focusable via keyboard navigation, it shouldn't affect users. Nonetheless, we'll remove it.

> The row expansion button has the issue Ensure buttons have discernible text

The surrounding `span` has an `aria-label` that describes the interaction. Additionally, as the button isn't focusable via keyboard navigation, there shouldn't be an issue for users.

___

In general, please try to follow the [Testing Accessibility](https://sap.github.io/ui5-webcomponents/docs/advanced/accessibility/#testing-accessibility) guidelines and ensure that there's an actual accessibility concern present.
