### ISSUE TITLE
[Toolbar]: [Style is not applied if the style was passed through className]

### ISSUE THREAD

**Issue by jamesPodo** [SAP/ui5-webcomponents-react#6638]
### Describe the bug

Style is not applied if the style was passed in className.

### Isolated Example

https://stackblitz.com/edit/github-7dyw9x-zvlp9s?file=src%2FApp.tsx,src%2Findex.css

### Reproduction steps

define style in css file, and pass className when creating Toolbar Component.

### Expected Behaviour

style is applied correctly

### Screenshots or Videos

![Screenshot 2024-11-18 at 4 01 05 PM](https://github.com/user-attachments/assets/89ebf401-f6ec-424e-9b91-46a0984a8169)

### UI5 Web Components for React Version

1.29.13

### UI5 Web Components Version

1.24.13

### Browser

Chrome

### Operating System

Mac OS

### Organization

SAP SE

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @jamesPodo 

the `className` including the styles are applied, but they're overridden by the component styles because of the injection order. 

![image](https://github.com/user-attachments/assets/2f4a5f7b-755c-4604-9c30-215456959a81)

You can set the `staticCssInjected` prop of the `ThemeProvider` to `true` and import the static style sheet yourself:

https://stackblitz.com/edit/github-7dyw9x-zqacwu?file=src%2FApp.tsx,src%2Fmain.tsx

You can find out more about this [here](https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/knowledge-base-styling--docs#applying-styling-via-classname-or-style).

In V2 we wrapped all styles in a CSS layer, but we don't plan downporting this feature.
