### ISSUE TITLE
[NotificationListItem]: Overflow action menu clicks Notification 

### ISSUE THREAD

**Issue by wvudako** [SAP/ui5-webcomponents-react#6723]
### Describe the bug

import {  Menu,  NotificationListItem} from '@ui5/webcomponents-react';

Your Storybook: https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/data-display-notificationlist--docs

The notification UI itself seems clickable with mouse/background changing on hover. Furthermore an action menu can be provided. When opening the menu via the overflow action button the notification is clicked not only resulting in the onClick action being performed which is not expected in my opinion but also before the menu is opened, so the event cannot even be stopped from bubbling.

```
      <NotificationListItem
        onClick={() => console.log('nli click')}
        menu={<Menu onBeforeOpen={() => console.log('menu open')} />}
      />
```

A workaround would be much appreciated

### Isolated Example

https://stackblitz.com/edit/github-3nnpxdjk?file=src%2FApp.tsx

### Reproduction steps

1. Click menu in NotifiactionListItem
2. See console that onClick is executed
3. See console that onClick is executed is before menu onOpen

### Expected Behaviour

Either call menu onOpen first to be able to prevent it from bubbling or not call NotificationListItem onClick at all, I dont think there is a usecase for that. 
Not having the NotificationListItem appear as clickable per default would also be a possible solution, but we actually like the design. I did not find any guidelines in Fiori for this 

### UI5 Web Components for React Version

2.4

### UI5 Web Components Version

2.4

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @wvudako 

`NotificationListItem` are not meant to be used as standalone, but only as part of the `NotificationList`. 

The `click` event is a native event wrapped by React (`SyntheticEvent`) and is not customized, wrapped, etc. by the web component or by our wrapper. Therefore, the `SyntheticEvent` is added to the `ui5-li-notification` element and since React internally registers all events to its root, the native `PointerEvent` is registered there. This means that i.a. event propagation is not handled by us.

You can use the `item-click` (`onItemClick`) event of the `NotificationList` to handle clicks on each list item, this event is not invoked if the overflow button is pressed. https://stackblitz.com/edit/github-3nnpxdjk-vlkskxhb?file=src%2FApp.tsx

If you have to rely on the `click` event, please describe your use-case. I'll then forward this issue to the UI5 Web Components team, so that they'll can have a look.

**Comment by wvudako** [comment]
While I dont understand the technical details I am sure you would change this behaviour if possible, so I take it is not. Therefore this solution is acceptable, but I would request at least documentation of this behaviour on this component (and e.g. Menu that I assume behaves the same way)
