### ISSUE TITLE
ToolbarButton | DynamicPageTitle | ActionSheet: [v2] ActionSheet does not open with ToolbarButton in DynamicPage actionsBar

### ISSUE THREAD

**Issue by fushizen** [SAP/ui5-webcomponents-react#6739]
### Describe the bug

On using a `Toolbar` and `ToolbarButton` inside the `actionsBar` property for `DynamicPageTitle` as the opener for an `ActionSheet`, the `ActionSheet` does not open.

Using a plain `Button` without the `Toolbar` components works as expected, and the `ActionSheet` opens (added in the provided isolated stackblitz example). However, this is not usable as the `actionsBar` is not rendered properly unless a `Toolbar` is used as the child component.

### Isolated Example

https://stackblitz.com/edit/github-3ajh2g-mygubrle?file=src%2FApp.tsx

### Reproduction steps

1. Open the example
2. The `ActionSheet` does not open on click of the `ToolbarButton`

### Expected Behaviour

Using a `ToolbarButton` we should be able to open an `ActionSheet` from the `actionsBar` of a `DynamicPageTitle`

### UI5 Web Components for React Version

2.4.0

### UI5 Web Components Version

2.4.0

### Browser

Chrome, Edge

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @fushizen 

the `ToolbarButton` is an abstract [UI5 web component](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/knowledge-base-faq--docs#what-are-abstract-ui5-web-components), therefore the actual element the popover should be rendered at is inside the shadow root. Usually, you should be able getting the reference of the element inside the shadow root by calling `getDomRef()` on the `ui5-toolbar-item`, but there was a bug which was only fixed in version 2.5.0. 

Additionally, since v2.5.0 of `@ui5/webcomponents(-react)` the `ToolbarButton` offers the `detail.targetRef` property in its `click` event. The linked PR will outline this in our documentation. Until it's available you can use this example as guidance: https://stackblitz.com/edit/github-3ajh2g-1pzavsyz?file=src%2FApp.tsx,package.json

Unfortunately, there's currently still a bug if a popover should be opened inside the overflow popover of the Toolbar, please see the respective issue for more details: https://github.com/SAP/ui5-webcomponents/issues/10370
