### ISSUE TITLE
[SF_ACC][ObjectStatus]: still show default stateAnnouncementText after setting stateAnnouncementText

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents-react#6773]
### Describe the bug

still show default stateAnnouncementText in the DOM after setting stateAnnouncementText
<img width="1785" alt="Image" src="https://github.com/user-attachments/assets/4f9341d8-3b89-408e-b985-a1525163c4bd" />

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

when setting stateAnnouncementText, should only show the setting value in the dom

### UI5 Web Components for React Version

2.5.0

### UI5 Web Components Version

2.5.1

### Browser

Chrome, Edge

### Relevant log output

```shell

```

### Organization

SAP SuccessFactors

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @GongRichard 

this behavior is by design, the `stateAnnouncementText` only replaces the announcement for the state announcement (e.g. "Invalid entry" for `state` `"Negative"`).

In case you require a different behavior, this request would need to go through the Inner Source process and be synchronised with the SAP Central Design team first. Please raise a BLI to the central design team and include the ticket number here for reference.

**Comment by GongRichard** [comment]
Checked ui5 sample, it's same behavior. 
Close it as expected behavior.
