### ISSUE TITLE
It fails to load

### ISSUE THREAD

**Issue by bsrdjan** [SAP/ui5-webcomponents-react#916]
```shell
$ npx create-react-app ui5-react --template @ui5/webcomponents-react-seed  

$ npm start
```

<img width="879" alt="Screenshot 2020-11-06 at 12 01 11" src="https://user-images.githubusercontent.com/1697847/98359216-20712a00-2028-11eb-8f38-05d83781baf5.png">

**Comment by MarcusNotheis** [comment]
Hey @bsrdjan,
thanks for reporting! As far as I know, you have to run `npm run mock` in order to start the project locally. `npm start` is indented for the deployed version.
@LuisValgoi: Can we make that clearer in the documentation? Or maybe we can rename `mock` to `dev` so that it's more clear the this script is intended for development?

**Comment by LuisValgoi** [comment]
Hey Marcus, yes, exactly. The developer has to run yarn mock when there is no backend.

I Will try to let things more clear in the DOCs.

**Comment by bsrdjan** [comment]
Thanks!
